### ISSUE TITLE
Consider turning off "Clear cookies and site data when you quit Chromium"

### ISSUE THREAD

**Issue by ianpan870102** [Eloston/ungoogled-chromium#1012]
Under `chrome://settings/content/cookies` there's a knob for `Clear cookies and site data when you quit Chromium`. In order to not have to re-enter passwords for google/facebook/twitter/github acounts every time one re-opens Chromium, one has to manually turn this knob off.
This is against most people's intuition, despite this being a privacy-centric chromium distribution. I'd like to suggest that we turn this knob off by default.

**Comment by PF4Public** [comment]
> In order to not have to re-enter passwords for google/facebook/twitter/github acounts every time one re-opens Chromium, one has to manually turn this knob off.

Changing this option should persist across restarts. Isn't it saved on your system?

**Comment by ianpan870102** [comment]
Thanks for the reply.

> Isn't it saved on your system?

Yes it is, and it indeed persists across restart. For me personally, the only time I have to turn off the knob is if I reinstall the browser (or upgrade it). 
I opened this issue because I was thinking from a new user's perspective. I, for one, struggled quite a bit when I first used ungoogled-chromium 2 months ago.

**Comment by PF4Public** [comment]
That's a two-way street. After flipping this setting, next comes a new bug report, saying something along the lines: "You're advertising this to be a somewhat secured browser, but how come by default cookies are preserved? Nonsense! Fix this!"

**Comment by ianpan870102** [comment]
True that, closing issue.

**Comment by solarkraft** [comment]
> After flipping this setting, next comes new bug report, saying something along the lines: "You're advertising this to be a somewhat secured browser, but how come by default cookies are preserved? Nonsense! Fix this!"

The browser is advertised as ungoogled. The very few people who want further reaching privacy settings can set them. The vast majority of users will be surprised and frustrated that the browser doesn't work like expected.

**Comment by PF4Public** [comment]
> The vast majority of users will be surprised

Do you have any proof baking that claim? Belonging to a set does not make this set vast by default, unless we are speaking "subjective".

**Comment by networkException** [comment]
I do see value in improving the "out of box experience" in this, especially because, as Paul pointed out, it doesn't have much to do with removing a dependency on Google services.

To not upset people who want a more locked down experience by default we could provide an option / (or at least a) tutorial on first startup, although this begs the question about the scope of the project (patchset or browser distribution) again.

**Comment by solarkraft** [comment]
> Do you have any proof baking that claim?

It is a strong intuition due to the fact that no mainstream browser does this, most notably the one this project intends to be a drop-in replacement for. People understandably think it's a bug that needs fixing (#812, #1352) because this change does not conform to the expectation of receiving "Chromium, but without a dependency on Google".  

The readme explicitly states the intent to *not* push an own vision on users beyond removing Google dependencies. I don't think objective 2 ("ungoogled-chromium retains the default Chromium experience as closely as possible") conflicts with objective 1 ("ungoogled-chromium is Google Chromium, sans dependency on Google web services"). 

As much as I support objective 3 ("ungoogled-chromium features tweaks to enhance privacy, control, and transparency"), in this case it clearly conflicts with objective 2. Presumably anticipating such a case the author even explicitly qualifies it with "however, almost all of these features must be manually activated or enabled". That's not the case with this change. 

> To not upset people who want a more locked down experience by default we could provide an option / (or at least a) tutorial on first startup

While of course it's important to support privacy focused use cases, consider the following:

1) How many people have the expectation of a more locked down experience when downloading ungoogled-chromium, especially when the readme prominently states that it's intended to be very similar to the original?

2) Of the people who want their cookies to auto-clear, how many need to be told that it's not the default and how to change it? After all this is likely the behavior of most browsers they've used before. Since there's a good chance that one of these browsers was Chromium based they likely even already know the *exact* setting. People who want their cookies saved aren't aware of the setting because they never had to change it. 

The reason I care about this so much is that I would like to be able to, with a good feeling, be able to recommend Ungoogled Chromium because it's so easy to switch to. First impressions count a lot and making somebody "WTF" (and literally lose data, even if it's just logins) is not a very good one. People are often not very invested in getting a piece of software to work (anecdotal evidence), so a response like "okay, this doesn't work, I guess I have to go back to Chrome/Chromium" is probably not uncommon.

**Comment by PF4Public** [comment]
> One reason I care about this so much is that I would like to be able to recommend Ungoogled Chromium as something that is easy to switch to. First impressions count a lot and making somebody "WTF" (and literally lose data, even if it's just logins) doesn't make a good one. People are often not very invested in getting a piece of software to work (anecdotal evidence), so a response like "okay, this doesn't work, guess I have to go back to Chrome/Chromium" is probably not that uncommon.

That is a good reasoning, thank you for sharing. Indeed removing cookies is not a big deal if one's profile is empty (there is not much to delete after all), but this could be a significant issue if one switches from a different browser and takes the profile with. 

@solarkraft Do you have other such incoherences in mind?

Maybe we should consider reverting this and reviewing other things to comply with project goals. Also #1979 is the must have to lower the amount of duplicated issues from newcomers.

**Comment by PF4Public** [comment]
> and literally lose data

I was thinking about it and it occurred to me: given that user had installed Chromium and used it with default settings, are these settings not preserved into profile so that later starting ungoogled-chromium, which sees those settings and complies with them, which results in no data loss?

**Comment by flatsiedatsie** [comment]
Could this be re-opened? I was also surprised by this ideosyncrasy.

**Comment by rdbo** [comment]
I agree that this should be reopened. After all, just deleting cookies doesn't make a browser hardened against online tracking. For those that want to go that extra mile, you'd still have to do many tweaks in order to get the browser truly private (e.g modifying user agent, spoofing hardware information, disabling almost all (if not all) JavaScript, etc).

Since the browser does not do any of that by default, I don't see why cookies are that big of an issue, specially since they are not used exclusively for tracking, but also for keeping important data like your access tokens for websites you've logged in.

Furthermore, most users (myself included) expect the browser to keep their information after closing all windows, since that is the default behavior on almost all browsers out there. I have used Ungoogled Chromium for some periods of times, then switched to other browsers once in a while. Every time I reinstall it, I forget that it automatically deletes the cookies and go search it up again.

I also think that the user skill maters a lot in this situation: a regular user probably won't know how to enable the cookies back in the settings or even that they have to do it in the first place, whereas someone who wants a hardened browser most likely does. It's a little questionable whether a regular user will end up using this browser or not, but I don't see why not keeping the setting disabled by default.

With that being said, I really think this should be reconsidered
@ianyepan would be nice to have the issue reopened for further discussion

**Comment by PF4Public** [comment]
>With that being said, I really think this should be reconsidered
> […] nice to have the issue reopened for further discussion

@rdbo You propose further discussion, yet you didn't address the statement which led to the closure of this issue.

I can move this issue into discussions if it helps.

**Comment by rdbo** [comment]
@PF4Public Yeah, I think that would be a good idea. I think that this topic deserves another look.

**Comment by PF4Public** [comment]
@rdbo Actually it would be better if you start the discussion yourself by presenting your bullet points as a starting point for the discussion.

**Comment by flatsiedatsie** [comment]
As a privacy professional I can concur that removing cookies is not really a privacy protecting feature, and if anything creates a false sense of security. The "identity resolution" industry is so far beyond this now.

More pragmatically for anyone finding this: I tried adding `"deleteDataPostSession":false` to `/etc/chromium/policies/managed/your_name_here.json`, but it didn't seem to work. The search continues.

**Comment by PF4Public** [comment]
> privacy protecting feature

Not stated as objective of ungoogled-chromium by default.

**Comment by rdbo** [comment]
Discussion: https://github.com/ungoogled-software/ungoogled-chromium/discussions/2653

**Comment by flatsiedatsie** [comment]
I still haven't found a way around this, and would appreciate any suggestion.

I tried to 'hack' around the issue by storing at least the username in the browser's local storage, but.. that didn't work either. Local storage is also cleared. Which.. makes sense.

I also tried to copy session files back into place before restarting the browser, but haven't had success there yet. Chromium just seems to create new sessions instead, ignoring the older files.

One solution is to switch back to normal Chromium, but from an ideological perspective I would really prefer to use this browser instead.

**Comment by rdbo** [comment]
@flatsiedatsie `chrome://settings` -> Privacy and Security -> Site settings -> Third-party cookies -> "Clear cookies and site data when you close all windows", toggle that off.
`chrome://settings/cookies` should take you to that path also
We are discussing about making this the default setting on #2653 if you wanna take a look

**Comment by flatsiedatsie** [comment]
@rdbo thanks for the suggestion, I know all about it :-)

As mentioned earlier in this thread, I'm trying to automate this process during an installation. I can't manually change this in the UI unfortunately.

I have, however, discovered something (through a lot of trial an error). I had a custom user data dir set in the startup parameters. Apparently this causes the policies file (in `/etc/chromium/policies/managed/`) to be ignored.

I resolved it be adding a policy parameter. Now the `deleteDataPostSession` policy setting is applied.

```
 --user-data-dir=/home/pi/foo/bar/chromium/ \
 --policy {"AllowFileSelectionDialogs": false, "AudioCaptureAllowed": false, "AutoFillEnabled": false, "PasswordManagerEnabled": false, "deleteDataPostSession":false} \
```

**Comment by discoveryX64** [comment]
> Under `chrome://settings/content/cookies` there's a knob for `Clear cookies and site data when you quit Chromium`.

I'm not sure if it is a recent update or something but I cannot redirect to `chrome://settings/content/cookies` when I paste it. All it does is redirect to the home page of settings.

> @flatsiedatsie `chrome://settings` -> Privacy and Security -> Site settings -> Third-party cookies -> "Clear cookies and site data when you close all windows", toggle that off. `chrome://settings/cookies` should take you to that path also. 

I tried this as well and when I tried to look for the setting it did not appear in the page that it told me to follow.

I tried looking for a flag and that seemed to help on some sites but Netflix (the site I'm having an issue on) seems to not let me search for shows, and randomly logs me out

If anybody can help me, that would be greatly appreciated

**Comment by touba-denrael** [comment]
@discoveryX64 this `https://github.com/ungoogled-software/ungoogled-chromium/issues/2873#issuecomment-2121309815` might be [at least partially] helpful.
