### ISSUE TITLE
Searx.me needs to be substituted

### ISSUE THREAD

**Issue by wchen342** [Eloston/ungoogled-chromium#1041]
Someone brought this up [in my repo](https://github.com/wchen342/ungoogled-chromium-android/issues/19) that `searx.me` no longer exists, so either we need another instance or another search engine.

**Comment by Megver83** [comment]
I suggest using search.disroot.org, it's the best instance I've seen so far

**Comment by Madis0** [comment]
Instances can change at any time and experiences will wary. For example, I tried the suggested engine and got no results two times in a row (third time worked).

**Comment by wchen342** [comment]
Actually when I tried to add `Qwant` in latest build I noticed that it was already added in UC, just not got listed as search engine in any of the languages. I will make a PR here when I have time.

**Comment by dietofworms** [comment]
How can we decide which instance to have as default? There are a number of them on `https://searx.space/` and after reviewing many discussions about it online, nobody really has a definitive answer. 

Outside of doing some sort of filtering based on jurisdiction, cryptcheck TLS grade, and perhaps other fields, we are arbitrarily choosing one over another.

**Comment by coughingmouse** [comment]
I've seldom used searx instances—mainly searx.me—because it was often unusable. 

I'm currently using [MetaGer](https://metager.org) and it seems to be quite functional. Not only have I not ever yet experienced it not showing any results, but its search results with queries in East Asian languages (tested Korean and Japanese) is superior over both default SearX search and with their inconvenient language specification settings set. I expect it to be equivalently better in European Asian language queries and have better chance to improve, considering it's developed in European Asia. It seems it's developed mainly by German devs, so there may be some German jargon here and there, but being an open source software under AGPLv3, I suggest it as a candidate.

**Comment by Ahrotahn** [comment]
Yeah, it's probably time to remove it.  The main instance has been down for a while and users can add their preferred instance as a custom search engine.
