### ISSUE TITLE
Chrome security fix tracking?

### ISSUE THREAD

**Issue by dm17** [Eloston/ungoogled-chromium#1045]
The classic argument against non-mainstream browsers is the mainstream (FF & Chrome) have big security teams rolling out patches the quickest. How long does ungoogled-chromium typically take to apply upstream security patches? (And I guess a subset would be a comparison between upstream security patches of chrome vs chromium.)
Thanks!

**Comment by jstkdng** [comment]
The real question is how long it takes us to remove the tracking stuff that gets added on each release as all security stuff is done on the chromium side.
The answer to that is there is no fixed time since everyone here helps when they have free time.

**Comment by Eloston** [comment]
Short answer: It depends. At the time of writing, maybe 1-2 weeks for major updates, less for small revisions. Please note that these numbers have a large variance, and change over time.

Longer answer:

First, Chrome is just Chromium, with some more Google-specific changes (notably Google API keys, Widevine DRM). There is very little difference in amount of code, and no difference in versioning between them.

Small Chromium revisions are quick because there usually isn't any code we need to change, aside from the Chromium version to build with.

Major updates can take some time because the Chromium codebase can change quite a bit. In addition, Google has been making changes that make our patches grow larger (notably Safe Browsing), which increases the time it takes to update.

In addition, everyone here is an anonymous independent contributor. There is no formal organization of any kind, and definitely no obligations from anyone.

Let us know if you have more questions.
