### ISSUE TITLE
Change OBS instructions for ubuntu/debian repos to use apt-key add

### ISSUE THREAD

**Issue by bheru27** [Eloston/ungoogled-chromium#1071]
*IMPORTANT: Please ensure you have read SUPPORT.md before continuing*

Hello all, 

While installing the package in Ubuntu using the OBS provided repos, I noticed the following (the same applies to debian):

**Add repository and install manually ** ->
`sudo wget -nv https://download.opensuse.org/repositories/home:ungoogled_chromium/Ubuntu_Focal/Release.key -O "/etc/apt/trusted.gpg.d/home:ungoogled_chromium.asc"`

Adding the file to `/etc/apt/trusted...` directly is a bad practice.

\The following command is a good approach using apt-key:

`wget -qO - https://LINK/Release.key | sudo apt-key add -`

The change applies to both Ubuntu and Debian install methods, this also removes the need to wget with sudo.

Link of the OBS: https://software.opensuse.org/download/package?package=ungoogled-chromium&project=home:ungoogled_chromium

* I found this solution because apt-key was not recognizing the key and I had trouble adding keys until I added it with the command I provided

**Comment by braewoods** [comment]
We didn't write those instructions. They are generated by OBS.

**Comment by Eloston** [comment]
Yeah, that should be reported to OBS. I don't think there's much we can do about it.

@braewoods In the meantime, would it make sense to add a note about this in the ungoogled-chromium-debian README? Tangentially related, it seems the links to get the package files directly in OBS are pretty useless because they don't provide links to dependencies; would it be better to add a link to a page to download all such debs directly, or should we simply note the broken links?

**Comment by notpushkin** [comment]
@braewoods May I kindly ask you to reconsider? [`apt-key add` is actually deprecated](https://gist.github.com/notpushkin/1cbdd3cbab0cf3570f87b7f2c0cb852d) so OBS instructions are arguably better.

**Comment by braewoods** [comment]
@notpushkin Reconsider what? I never stated a preference for either one.

**Comment by notpushkin** [comment]
@braewoods Sorry, I've mis-directed my comment – it was for @bheru27 of course :)

**Comment by Eloston** [comment]
Closing because fix is pending upstream.
