### ISSUE TITLE
Tab crash when playing sound/video

### ISSUE THREAD

**Issue by nerd** [Eloston/ungoogled-chromium#1083]
**Describe the bug**
Any tab when media (video/sound) plays, will crash with the code `RESULT_CODE_UNINSTALL_USER_CANCEL`.
I have tried recompiling/reinstalling, as well as deleting my `~/.config/chromium` folder.
This is NOT an issue when using Firefox or Google Chrome Beta.
(if you need any logs I will need guidance in getting them)

**To Reproduce**
1. Go to any page with sound/video ([example](https://dreamcatalogue.bandcamp.com/album/--18))
2. Press play (if applicable; silent autoplay videos are affected as well)
2. Tab will crash with code `RESULT_CODE_UNINSTALL_USER_CANCEL`

**Expected behavior**
The tab will successfully play the media and not die

**Environment (please complete the following information):**
 - OS/Platform and version: Gentoo, x86_64, kernel `5.7.5-gentoo`
 - ungoogled-chromium version: `83.0.4103.116`

**Comment by perfect7gentleman** [comment]
confirm

**Comment by perfect7gentleman** [comment]
dmesg shows the following error
```
[226352.834976] Code: 48 8b 04 25 00 00 00 00 0f 0b 48 8b 04 25 00 00 00 00 0f 0b 48 8b 04 25 08 00 00 00 0f 0b 48 8b 05 27 ff 03 00 48 89 44 24 58 <48> 8b 04 25 00 00 00 00 0f 0b 48 8d 05 e9 cf 02 00 4c 89 f7 48 c7
[226803.606675] Media[23426]: segfault at c ip 000055b18b39b6ae sp 00007f389c774c60 error 6 cpu 0 in chrome[55b18a9a4000+7fc7000]
[226803.606678] Code: ff ff bb 06 00 00 00 e9 15 fc ff ff 31 db e9 0e fc ff ff cc cc cc cc cc cc cc cc cc 41 57 41 56 41 54 53 50 49 89 f6 49 89 ff <c7> 46 0c 01 00 00 00 8b 0f ff c9 83 f9 0e 77 35 b8 02 50 01 00 48
```

**Comment by xsmile** [comment]
This should be related to ffmpeg 4.3, see https://bugs.gentoo.org/728624.

**Comment by PF4Public** [comment]
Looks like this issue is easily fixed with a patch. Should I include it in my ebuild?

**Comment by perfect7gentleman** [comment]
testing

**Comment by nerd** [comment]
seems to work for me as well @PF4Public

**Comment by Eloston** [comment]
Closing because issue is solved.

@PF4Public I just created https://github.com/ungoogled-software/contrib; it would be nice to include your patch there. If you'd like, I can grant you write access to the repo.

**Comment by PF4Public** [comment]
@Eloston This patch is taken from mainline Gentoo chromium. And I think I can easily include it into contrib as it could be really useful on other platforms/environments, but I doubt I can use it.

I have simplified my workflow as much as I could, because otherwise I had to dedicate a lot of my time on maintaining Gentoo ebuild of unggogled-chromium (that is mostly because of the source-based nature of Gentoo and implications thereof). I'm fine with the time I'm spending on it right now, but would better not increase it. My worflow at the moment is that I simply copy needed patches from Gentoo and place them in my repo, which is rather easy and fast. Using an intermediate repo in my workflow would mean that I have to copy this patch to the said repo, commit, push, update reference to this repo in my ebuild, handle extraction and patch selection. All of this is exactly what I was willing to avoid by simplifying my workflow, by editiong the ebuild, that I have "inherited" from Ian Moone. Those are actually also the reasons outweighing the benefits of creating Gentoo-targeted repo under ungoogled-software in my opinion.

Having all this said, I do wish to commit this patch to contrib repo for the benefit of community. Come to think of it… what are the odds, someone outside Gentoo using ffmpeg 4.3 and needing this patch?

**Comment by Eloston** [comment]
@PF4Public It's better to think of contrib like GitHub Gists; it's not super formal and just a place for you to put stuff you think will be useful for others. You probably don't want to integrate contrib into your workflow. There's no obligation to use it either. I'm just trying to make others aware of contrib because I want to see if it helps.
