### ISSUE TITLE
Add a new repo ungoogled-software/contrib

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#1085]
Inspired by [this blog post](https://drewdevault.com/2020/06/06/Add-a-contrib-directory.html), I think we should incorporate this idea in the form of a new repo `ungoogled-software/contrib`.

The target audience includes those who maintain their own ungoogled-chromium-based browsers. Some potential use cases include:

* Someone wrote some scripts around the Python utilities to automate some workflow
* Someone has a patch fixing some system library dependency that is useful for others
* Someone wrote a new feature or script that doesn't conform to ungoogled-chromium's contribution guidelines and standards, but others may find useful.

To clarify the purpose and usage a bit more, I quote the blog post above:

> The contrib [repo] is used as an unorganized (or, at best, lightly organized) bin of various useful things **contrib**uted by the community around the software, but which is not necessarily a good candidate for being a proper part of the software. Things in contrib should not be wired into your build system, shouldn’t be part of your automated testing, shouldn’t be included in your documentation, and should not be installed with your packages. contrib entries are not supported by the maintainers, and are given only a light code review at the most. There is no guarantee whatsoever of workitude or maintenance for anything found in contrib.

(I highly recommend reading the blog post for more)

What do you guys think?

**Comment by mbakke** [comment]
Good idea.  I recently "forked" some of the Debian `system/*` patches for Guix, and will happily move them out of Guix to a shared repository.

Another useful addition would be a script to remove non-free files, related to #1054.

**Comment by Eloston** [comment]
Done https://github.com/ungoogled-software/contrib

**Comment by Eloston** [comment]
Pinning this for a little bit for increased visibility. I think several ideas or contributions in the past that were shut down or ignored could have matured via contrib. Hopefully this improves the quality-of-life for both developers and users.

**Comment by jstkdng** [comment]
Just a question, why create another repository instead of adding a contrib folder here?

**Comment by Eloston** [comment]
@jstkdng Few reasons:

* This repo contains code that is used by all platform repos. Contrib can contain anything, and I suspect a number of contrib stuff will be related to specific platforms, configurations, or workflows. If contrib was just feature changes to Chromium, then I suppose merging it into this repo would make sense.
* This repo has relatively high contribution standards, whereas contrib has pretty relaxed standards. This also means it's better to allow more people to directly write to contrib or accept PRs to contrib, which is easier to do when it's a separate repo rather than a directory on this repo. In fact, this happens to be the same reason that motivated the creation of the ungoogled-software organization and platform repos.

**Comment by wchen342** [comment]
I think there will be need for sub-folders that can apply to different platforms/configurations, like those of Linux/Windows/Android. Also what will be the acceptance guildline for `contrib`?

**Comment by Eloston** [comment]
@wchen342 I neglected to include the two following paragraphs from the blog post that I think will answer your questions:

> Nevertheless, it is often useful to have such a place to put various little scripts, config files, and so on, which provide a helpful leg-up for users hoping to integrate the software with some third-party product, configure it to fit nicely into an unusual environment, coax it into some unusual behavior, or whatever else the case may be. The idea is to provide a place to drop a couple of files which might save a future someone facing similar problems from doing all of the work themselves. Such people can contribute back small fixes or improvements, and the maintenance burden of such contributions lies entirely with the users.
> 
> If the contributor wants to take on a greater maintenance burden, this kind of stuff is better suited to a standalone project, with its own issue tracking, releases, and so on. If you just wrote a little script and want somewhere to drop it so that others may find it useful, then contrib is the place for you.

(For the record, these paragraphs are already quoted in contrib's README.)

Essentially, contrib should not be a burden to contribute to. Therefore, I don't think any one structure should be mandated because it might be troublesome to fit some contributions to any one directory structure. There's not really an acceptance guideline; just don't accept stuff that's unreadable.

**Comment by wchen342** [comment]
Personally I think the idea of "making a repo that we just put all kinds of non-standard/third-party solutions in" is kind of too vague and will probably end up with something hard to deal with once the repo grows. I have used another open-source project maintained by Google (I will not name the project) and they have a `contrib` submodule which ended up growing into a huge componenet that has too many things, both useful and not, large and small, mixed together. They ended up breaking apart that module and moved those functionalities into other standard submodules when they overhauled the whole project and removed that `contrib` submodule.

To be clear, I am not against the idea because it will probably fit this project, but I am trying to express my concern about how it can be maintained and organized. I believe the idea will work better if the project has a large enough community that can keeps maintaining the codebase and gives feedback. An example is Archlinux, which has Arch User Repository (AUR) that is almost a `contrib` repo and when a package in AUR gets enough votes from users it can be moved from AUR into the official main repo. However that is based on a team of ~50 trusted users oversees AUR as well as a large user base.

Also I notice the license at the end is public domain. Does that mean things added to `contrib` is not going to appear back in main repo?

**Comment by Eloston** [comment]
I see your point, but I don't think that project is using `contrib` in the same way that I envision it. I will not allow any code or official documentation (except the Wiki) reference anything in contrib. If something in contrib really grows that large, then the developer(s) should maintain it in its own repo. If they want to see it included in ungoogled-chromium, then they should work to get it included in ungoogled-chromium.

contrib is not *really* part of ungoogled-chromium. It's an accessory to ungoogled-chromium solely for the community. It is to enable the community to share and interact among themselves in a new way, that goes beyond:

* users searching old issues for solutions
* users creating new issues asking for help
* users browsing the Wiki for solutions (which doesn't really cover anything beyond common problems)

At minimum, I'd expect users to publish patches or scripts to accommodate some workflow or configuration they use. If we're lucky, maybe someone wants to publish and maintain a feature change for Chromium. If we're even luckier, someone else may mature it enough for us to include in this repo or platform repos. Yes, this is a pretty specific and optimistic scenario, but it's not hard to think of new ways that people could interact.

Finally, let's consider the development situation. Right now, we have very little development outside of regular Chromium releases or improvements to platform repo infrastructure. I think it's because of two reasons:

1. Developers have to pass a pretty high bar in order to make any meaningful changes to Chromium, not even considering ungoogled-chromium's standards.
2. Developers working on ungoogled-chromium, or users of ungoogled-chromium, are able AND willing to write their own scripts to enable their own workflows. I don't think such people are too common, given the scope of this project.

If contrib becomes large and messy like that of your unnamed project, then that means development interest is higher than I thought. That'd be great news. But I'd need to see the situation first before finding some way to handle it.

> Also I noticed the license at the end is public domain. Does that mean things added to contrib is not going to appear back in main repo?

Not necessarily. The default public domain license is there just to enable maximum freedom without worrying about licensing. If someone does not want that, the contrib README already advises them to specify a license. Regardless, I don't expect this to become an issue given the nature of contrib.

**Comment by wchen342** [comment]
> contrib is not really part of ungoogled-chromium. It's an accessory to ungoogled-chromium solely for the community.

I see. That actually makes much more sense now. I was think `contrib` as a regular repository where interactions are mainly between developers and users but your idea is more like communications between users and users (and some of the users are developers, of course). It will be interesting to see how this will work on Github since traditionally (I think) the scenarios you mentioned are done through platform like forums.

> Developers have to pass a pretty high bar in order to make any meaningful changes to Chromium, not even considering ungoogled-chromium's standards.

This I completely agree. If there wasn't @xsmile's building script for me to start with there may be no `android` version now. I think maybe we can add some kind of "Development Guide" to the wiki so people have some basic ideas what parts are Chromium consists of, how Chromium is actually built and what do those tools do (like `gn` and `ninja`), since the official documents are way too concise.

**Comment by Eloston** [comment]
> I think maybe we can add some kind of "Development Guide" to the wiki so people have some basic ideas what parts are Chromium consists of, how Chromium is actually built and what do those tools do (like gn and ninja), since the official documents are way too concise.

This is a good idea. Overall, I actually think the official docs are pretty good (especially the new documents that live under `docs/` in the Chromium source code), but there's just so much information that it's overwhelming. It'd be pretty nice to have a "Development Guide" that's specialized for ungoogled-chromium. It may also be a handy reference for ourselves.
