### ISSUE TITLE
forcing https on localhost 

### ISSUE THREAD

**Issue by jacques-andre** [Eloston/ungoogled-chromium#1113]
**Describe the bug**:

Whenever I try access my localhost development server it automatically redirects me to `https:localhost` rather than `http:localhost` I have also tried to use `127.0.0.1` but it also redirects me to `https:127.0.0.1` rather than `http:127.0.0.1`.

**I have tried all solutions** on [this](https://stackoverflow.com/questions/25277457/google-chrome-redirecting-localhost-to-https) stack overflow page although they are not working even after I clear my history. 

[I have tried to remove hsts entries for both localhost and 127.0.0.1 but it is not working](https://i.stack.imgur.com/CJXEh.png).

**This is extremely annoying and frustrating.**

**To Reproduce**:

Have a development server running, I am using [go-fiber](https://github.com/gofiber/fiber) and navigate to `localhost`. You will see that `https` is enforced rather than `http`

**Expected behavior**:

I want to be able to access my development server with the default being `http` rather than `https`

**Screenshots**:

[https://imgur.com/InOPhw7](https://imgur.com/InOPhw7)

**Environment**:

 - OS/Platform and version: MacOs Catalina 10.15.5
 - ungoogled-chromium version: Version 84.0.4147.89 (Official Build) (64-bit)

**Comment by wchen342** [comment]
Should be the effect of [this patch](https://github.com/Eloston/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/default-to-https-scheme.patch). If you know how to compile then remove the patch and recompile should solve the problem.

**Comment by Kein** [comment]
But why was this patch accepted without local exclusions in a first place?

**Comment by Eloston** [comment]
Well, that's because we didn't think of that use case in the original PR: #628.

We have a number of options, but each have their own problems:

1. Add an exclusion for `localhost` and all loopback addresses (including both IPv4 and IPv6). This would solve this issue specifically, but requires a developer to implement the change. Also, are there other situations where the protocol should be HTTP by default? What about private IP addresses?
2. Add a flag to toggle HTTPS by default. Probably similar amount of work as the first option, but can also address use cases where the user would want HTTP for most pages they visit. However, it doesn't satisfy users who want HTTP only for localhost.
3. Add some whitelist for domains and IP addresses that should be HTTP-only. This is possible via a freeform chrome://flags field value, but would require the most amount of work to implement.
4. Remove the patch entirely. Solves this issue, but it discards the efforts in #628.

If I had to choose, I'd go for Option 4 because I think the change for HTTPS by default is debatable at best, and it kinda conflicts with the objectives of ungoogled-chromium. However, I have no strong preference for any option.

Thoughts?

**Comment by Kein** [comment]
Option 4 has still a workaround in a form of an extension and seems like the fastest to "implement" and solve the issue. The rest 3 require someone to work out and maintain a solution so they seems less feasible in a long ru

**Comment by jacques-andre** [comment]
I think option 2 could work. I am already using [https everywhere](https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp) which doesn't force `https` on localhost so it's not like I would be missing out on having enforced `https` on sites other than `localhost`

**Comment by jacques-andre** [comment]
any updates?

**Comment by Eloston** [comment]
Going to go with Option 4 until someone is interested in implementing the other options.

**Comment by tie** [comment]
@Eloston I’m interested in implementing this feature (again), as well as maintaining it as long as I’m mentioned somewhere in the discussion. I’ll look into implementing Option 2 or 3 this weekend.

FWIW I didn’t consider adding exclusions because I’m using self-signed certs generated with [mkcert](https://github.com/FiloSottile/mkcert). Unless you are developing HTTP-only service, I strongly recommend using TLS connections since they are [required for HTTP/2](https://stackoverflow.com/q/46788904) and the [upcoming HTTP/3](https://blog.chromium.org/2020/10/chrome-is-deploying-http3-and-ietf-quic.html) protocols. Those have some features (e.g. [server push](https://en.wikipedia.org/wiki/HTTP/2_Server_Push)) you can’t test on good ol’ HTTP/1 over TCP.

**Comment by Kein** [comment]
3 seems most flexible if you want to put work into the feature

**Comment by tie** [comment]
@Kein agreed. I’ll probably go with the second option then, and users who want more fine-grained control could use some third-party extension.

The issue with extensions like HTTPS Everywhere is that they don’t enable HTTPS, uh, everywhere. Usually it’s just a database of sites known to support HTTPS. Unlisted sites will still be accessed over an insecure connection by default. See also: [HTTPS by default](https://github.com/Rob--W/https-by-default#chrome--chromium), similar patch for Omnibox.
