### ISSUE TITLE
Widevine files described in FAQ actually don't work [Windows x64]

### ISSUE THREAD

**Issue by framilano** [Eloston/ungoogled-chromium#1120]
I'm talking about [this procedure ](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#windows)

I place the files correctly in my WidevineCdm folder but still they don't work as described, chrome://components still says 0.0.0.0 near Widevine module version.

**Comment by Eloston** [comment]
It also shows 0.0.0.0 for me on Linux. Have you tried testing on a DRM-protected stream, like this one? https://bitmovin.com/demos/drm

**Comment by framilano** [comment]
> It also shows 0.0.0.0 for me on Linux. Have you tried testing on a DRM-protected stream, like this one? https://bitmovin.com/demos/drm

Tried with Spotify and Disney Plus, they both don't work, I tried moving WidevineCdm from https://chromium.woolyss.com/ and yes their files work.

They probably took them from an offline chrome installer though

**Comment by Eloston** [comment]
@maljaroudi Since you wrote the instructions, would you be able to clarify?

Also @framilano, what browser version are you running?

**Comment by maljaroudi** [comment]
@Eloston Thanks for the ping. 

@framilano I will try to clarify the instructions, since i tried to fresh install and the widevine version was updated, in addition to the services you mentioned working.

If you installed your program using the installer on the release page, your chromium setup folder would be under user/AppData/Local/Chromium/Application. 
I am using the latest release provided in that page, so you can follow what i did.

1- I downloaded the latest widevine version which was [4.10.1582.2 ](https://dl.google.com/widevine-cdm/4.10.1582.2-win-x64.zip)
2- Navigated to the chromium install folder , in my case i used the installer on the release page so the folder would be USER\AppData\Local\Chromium\Application\84.0.4147.105
**(Be sure to go inside the version directory)** if you used the portable, just find the version folder.

3- I created the folder "WidevineCdm", and placed the manifest.json and LICENSE files under it. 
4- Also inside the WidevineCdm folder, i created a subfolder named "_platform_specific". Inside the platform specific folder, i created a sub folder named "win_x64" and placed the rest of the files inside that folder.

Your widevine should now be working. 

Future note, those links might be outdated, please refer to the instructions to get the latest widevine version.

**Comment by framilano** [comment]
> @maljaroudi Since you wrote the instructions, would you be able to clarify?
> 
> Also @framilano, what browser version are you running?

84.0.4147.105-1.1, not the installer one but _windows.zip

**Comment by framilano** [comment]
> @Eloston Thanks for the ping.
> 
> @framilano I will try to clarify the instructions, since i tried to fresh install and the widevine version was updated, in addition to the services you mentioned working.
> 
> If you installed your program using the installer on the release page, your chromium setup folder would be under user/AppData/Local/Chromium/Application.
> I am using the latest release provided in that page, so you can follow what i did.
> 
> 1- I downloaded the latest widevine version which was [4.10.1582.2 ](https://dl.google.com/widevine-cdm/4.10.1582.2-win-x64.zip)
> 2- Navigated to the chromium install folder , in my case i used the installer on the release page so the folder would be USER\AppData\Local\Chromium\Application\84.0.4147.105
> **(Be sure to go inside the version directory)** if you used the portable, just find the version folder.
> 
> 3- I created the folder "WidevineCdm", and placed the manifest.json and LICENSE files under it.
> 4- Also inside the WidevineCdm folder, i created a subfolder named "_platform_specific". Inside the platform specific folder, i created a sub folder named "win_x64" and placed the rest of the files inside that folder.
> 
> Your widevine should now be working.
> 
> Future note, those links might be outdated, please refer to the instructions to get the latest widevine version.

I'm not using the installer though, I'm using the _windows.zip version, so I assume my chromium root folder is wherever I extract my files.
But I just realized I was downloading widevine version 1.4.9.1088 and not 4.10.1582.2 , and that's it, that was actually the problem. I assumed the first version appearing in the version.txt was the latest. Now it works perfectly with version 4.10.1582.2

Sorry for wasting your time guys, have a nice day!

**Comment by holwes** [comment]
> But I just realized I was downloading widevine version 1.4.9.1088 and not 4.10.1582.2 , and that's it, that was actually the problem. I assumed the first version appearing in the version.txt was the latest. Now it works perfectly with version 4.10.1582.2
> 
So how do I know the current version of Widevine? In the FAQ there is written that you first download https://dl.google.com/widevine-cdm/current.txt to determine the current version. But this is obviously wrong...?!

**Comment by maljaroudi** [comment]
> > But I just realized I was downloading widevine version 1.4.9.1088 and not 4.10.1582.2 , and that's it, that was actually the problem. I assumed the first version appearing in the version.txt was the latest. Now it works perfectly with version 4.10.1582.2
> 
> So how do I know the current version of Widevine? In the FAQ there is written that you first download https://dl.google.com/widevine-cdm/current.txt to determine the current version. But this is obviously wrong...?!

Someone committed new changes to the wiki and changed the file url you need to access. 
try the old one here: https://dl.google.com/widevine-cdm/versions.txt . Use the version at the end of the file to download it.
Google stopped updating the current.txt file long time ago.
