### ISSUE TITLE
Gray out the subdomain

### ISSUE THREAD

**Issue by Madis0** [Eloston/ungoogled-chromium#1170]
**Is your feature request related to a problem? Please describe.**
A visual difference between example-evil.com, example.evil.com, example.com and evil.com

**Describe the solution you'd like**
Gray out the subdomain, similar to Firefox, Opera, IE and Vivaldi.

**Describe alternatives you've considered**
Bold the primary domain, though that could make things more confusing

**Additional context**
See also https://github.com/brave/brave-browser/issues/11604

**Comment by Eloston** [comment]
What kind of problem are you trying to solve with this change?

**Comment by Madis0** [comment]
Chromium browsers emphasize the host as the most important part of the URL while the four other browsers I mentioned emphasize the base domain. I think the base domain is much more important to the user, as the subdomain can easily be faked (`bank.com.evil.com`) and the user might not even bother reading it fully.

Also, better emphasis on the main domain if the subdomain is long.

**Comment by Luka-Filipovic** [comment]
It makes sense to me.

**Comment by sijanec** [comment]
I think that would introduce even more relying on external sources and confusion.

How would UC know what to gray out in www.example.co.uk?

www seams reasonable, but how would UC know that co.uk is a public domain extension? An external list of public domain extensions would be required, otherwise www.example would be greyed out and only co.uk would stand out.

I like to see the whole hostname distinguished. I don't even like how FF and C intensively grey out the path.

The way cookie permissions are configured using a publicsuffix.org list already seems like a bad idea.

**Comment by Eloston** [comment]
I agree with @sijanec, the specifics of this request becomes complicated. Also, I'm not very convinced this would be a useful change, especially considering the kinds of users we attract. If I see a working implementation of this and the various cases identified (such as what @sijanec pointed out), then I'll reconsider.
