### ISSUE TITLE
Updating Chromium removed all of my extensions

### ISSUE THREAD

**Issue by 537** [Eloston/ungoogled-chromium#1178]
Is this normal? Is there a way to get them back?

**Comment by PF4Public** [comment]
Please, be more specific and provide us with some information so that we could help you.

BTW, this is why an Issue template is suggested to be filled out automatically upon creating a bug in this repository:
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - OS/Platform and version:
 - ungoogled-chromium version:

**Additional context**
Add any other context about the problem here.

**Comment by 537** [comment]
My bad, I just went from 80.0.3987.149-2.1 to 84.0.4147.135 (both 64-bit). I'm on Windows 10. After updating, I launched Chromium with no extensions but my bookmarks were there.

**Comment by wchen342** [comment]
Maybe because you skipped too many versions? What if you upgrade to v81->v82->v83->v84?

**Comment by 537** [comment]
I honestly don't know how I fixed it but... I fixed it.
