### ISSUE TITLE
Missing imagein reader mode

### ISSUE THREAD

**Issue by ghost** [Eloston/ungoogled-chromium#1221]
When using reader mode (flag #enable-reader-mode) in Chromium there should be an underlined letter A image, instead it just displays .

I'm using the latest windows x64 build, an example URL to use the experimental reader mode is here:
https://www.eapoe.org/works/poems/ravent.htm

**Comment by Eloston** [comment]
Are you still having this problem?

**Comment by seth1** [comment]
Sorry for the late response, I lost a machine.
Yes the problem is still there in this file:
https://github.com/tangalbert919/ungoogled-chromium-binaries/releases/download/87.0.4280.67-1/ungoogled-chromium_87.0.4280.67-1.1_windows-x64.zip
I have not tested other builds. I am using Windows 10.
Here is what I see:
![image](https://user-images.githubusercontent.com/17210111/104109406-22a76d00-5293-11eb-9172-dd5d1e48afc3.png)
