### ISSUE TITLE
Auto-page Translation Question

### ISSUE THREAD

**Issue by dm17** [Eloston/ungoogled-chromium#1234]
This isn't as much of a feature request as it is a request for ideas / help from ungoogled-chromium users:

Why can't an extension be made that does the same as Google Translate using the offline packs? I see there used to be a DeepL translation extension for browsers, but support for it has been dropped. Any ideas on if this is possible & how it would work? Perhaps I'm overlooking something that is already out there? Putting web pages through translate.google.com doesn't work well, and seems like a bad idea for stores & restaurants anyway. Obviously page translation is imperative for international travelers.
I'm thinking this community would have the best feedback for this question since I think ungoogled-chromium is the best.

Thanks!

**Comment by bkil** [comment]
At a minimum, there should be a setting to choose an online translation service. There exist quite a few alternatives for many language pairs - DeepL included.

There already exist a few frameworks on which you may build offline translator applications for your own language pairs. However, the quality of all of these home-brew translators will be appalling, unless you are also willing to fund someone full time who is fluent in each language pair for fine tuning and ongoing maintenance.
- https://en.wikipedia.org/wiki/Comparison_of_machine_translation_applications

Although, I think still think that offering a minimal viable offline alternative having a lesser quality would still be better than nothing.

**Comment by dm17** [comment]
> At a minimum, there should be a setting to choose an online translation service. There exist quite a few alternatives for many language pairs - DeepL included.
> 
> There already exist a few frameworks on which you may build offline translator applications for your own language pairs. However, the quality of all of these home-brew translators will be appalling, unless you are also willing to fund someone full time who is fluent in each language pair for fine tuning and ongoing maintenance.
> 
> * https://en.wikipedia.org/wiki/Comparison_of_machine_translation_applications
> 
> Although, I think still think that offering a minimal viable offline alternative having a lesser quality would still be better than nothing.

Thanks... But what do the online services have that the offline ones can't? It seems when the Google Translate app on Android uses the offline dictionaries - its translations are just as good.

**Comment by bkil** [comment]
Sorry for not making myself clear. Basically, by "offline" I meant "offline libre software" and that basically means roll your own which is by definition much inferior in this context.

Surely your device is Turing complete and it has ample storage and processing power to translate anything on its own with potentially excellent accuracy _in theory_. Although, they do [declare](http://www.techspice.com/latest-news/google-translate-android-app-adds-offline-support/) that the offline version is not as comprehensive as the full thing (due to both processing and intellectual property protection restrictions), I believe you that its performance is adequate.

What the proprietary alternatives offer are "secret sauce", continued maintenance and server provisioning to reduce load on your hardware and battery. All of these cost time and money to achieve.

So then again, from a software development standpoint, your request for "just making an extension pack that works the same as Google" would take a multi-million dollar project to even get in the same ball park - it's not as if you asked for an extension that can compute logarithms.

**Comment by dm17** [comment]
Let ms see if we can define a few facts, or rule them out as lies:
-- Google Translate (for Android) is OSS (on the client side)
-- It works offline
-- It has language packs that work offline
-- So a fork / derivation could be made to work without Google Services
... And theoretically, that offline, language-packing-using, stand-alone software could be used within a browser extension for web pages... Somehow :)

**Comment by bkil** [comment]
Could you please share some references?

**Comment by dm17** [comment]
Just a theoretical place to start. If Google Translate can work well enough offline, then it could be forked to work as a browser extension + some magic that translates web page text in place.

**Comment by bkil** [comment]
Google Translate and/or its offline dictionary was never free open source source software. Sorry, I don't have time for taking part in unreferenced, speculative conversations anymore, but I wish you find the answer for whatever you are looking for.

**Comment by mzso** [comment]
It's unclear for me. But was Google Translate excised from this browser?

**Comment by dm17** [comment]
> It's unclear for me. But was Google Translate excised from this browser?

It was even from chromium

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently — closing.
If you have any more information to add, please continue the discussion in #1892

**Comment by dm17** [comment]
https://news.ycombinator.com/item?id=33792447 - some useful discussion for those researching how to implement offline translation
