### ISSUE TITLE
An easy solution for incremental building when ninja fails

### ISSUE THREAD

**Issue by playgithub** [Eloston/ungoogled-chromium#1245]
In practice, `downlad & extract & patch` almost always succeed, `ninja` sometimes fails after a long time building.
What about to split `build.py` as below:
* build-download.py
* build-extract-patch.py
* build-ninja.py

**Comment by Luka-Filipovic** [comment]
I did something similar.
- prepare_src.py/sh - Downloads, extracts, domain substitution
- apply_patches.py/sh - Apply/Update patches
- build.py/sh - flags, GN, ninja build

**Comment by playgithub** [comment]
* Donwload is slow
* If patches failed, it should be extracted and patched again
* build might take a long time to fail

Better to make steps as below?
1. download
2. extract & patch
3. build

**Comment by Luka-Filipovic** [comment]
> 1. prepare_src.py/sh - Downloads, extracts, domain substitution
> 2. apply_patches.py/sh - Apply/Update patches
> 3. build.py/sh - flags, GN, ninja build
Note: this is not suitable for UC build process (I'm working on something different that is quite a bit based on UC) since dom sub is done after patches.

> Better to make steps as below?
> 
> download
> extract & patch
> build

Extract is (with my dl speed ~100mbps) much slower than download so that's why I put download and extract in one script and do it only once. Patch script should be modified so it can be rerun if it fails. And finally it all passes, there's build script at the end.
Not sure where to put domain sub. One option is at the bottom of patch script, and it would be great if patch script could check if domsub was already executed so it would reverse it, reverse all previous patches, apply new patches, apply domainsub.

**Comment by playgithub** [comment]
> it would be great if patch script could check if domsub was already executed so it would reverse it, reverse all previous patches, apply new patches, apply domainsub.

I think it's not easy to do this on structureless text.
If possible a ninja-ready ungoogled-chromium git repo is the easiest way.

**Comment by wchen342** [comment]
> > it would be great if patch script could check if domsub was already executed so it would reverse it, reverse all previous patches, apply new patches, apply domainsub.
> 
> I think it's not easy to do this on structureless text.
> If possible a ninja-ready ungoogled-chromium git repo is the easiest way.

What I usually do is just using `rsync` to make a copy before applying patches/domain substitution so if anything went wrong I just rsync back the original files. But this requires you have enough storage space.

Btw it is good to separate the downloading part. I am doing a complete unattended build on remote machines and I need to wrap the downloading part in a retry block, otherwise if it fails all the following steps will fail.

**Comment by jstkdng** [comment]
You could also use a git repository, and just switch to another branch before applying patches/domain substitution. Not sure if that would be fast.

**Comment by playgithub** [comment]
The chromium git repo is very big, `git clone` form a recent commit is criticial.
But it seems that `git clone` doesn't support this.
As a workaround, after a small experiment, `git init` & `git fetch` & `git pull` seems to be able to do s.th. like `git clone --from commit`.

**Comment by jstkdng** [comment]
I meant to download the chromium release source, extract it then git init. Commit everything and do the patches/domain substitution.
