### ISSUE TITLE
Requesting arm64 macos build

### ISSUE THREAD

**Issue by sneak** [Eloston/ungoogled-chromium#1255]
I've a new M1 MacBook Air and would like to run Ungoogled Chromium in the native arch for performance.

This might be the wrong repo for this (I know there's only source here and the builds are all community) but perhaps the people who know how to build this will see it here.

**Comment by petersmagnusson** [comment]
It would have to be done as a cross-compile from an intel mac with target arm64 mac.  The google tooling for building vanilla chromium does not work natively yet - for example, if you try to get them to work you'll notice they don't yet handle the arm64/arm64e issue in copying a system python executable into venv.

**Comment by zinozzino** [comment]
I built a macOS Universal ungoogled-chromium 87.0.4280.88-1.1 with following the instruction from [this repo](https://github.com/ungoogled-software/ungoogled-chromium-macos). I will request a pull request to update the `build.sh` soon.
Here is the [link](https://drive.google.com/file/d/1JpU-gRTIsO4z5WegiN09kfBhd_9DeyZK/view?usp=sharing)

**Comment by Mouvedia** [comment]
@zinozzino could you share the changes you have made to cross compile it?

**Comment by zinozzino** [comment]
> @zinozzino could you share the changes you have made to cross compile it?

I did not cross compile because i compiled on my M1 mac, but you can follow the instruction from [this link](https://chromium.googlesource.com/chromium/src.git/+/master/docs/mac_arm64.md#building-for-arm-macs). according to that, all you need to do is adding `target_cpu="arm64"` on `args.gn`.

All i have to do for compile on M1 is that I removed the LLVM pre-built binary from `downloads.ini` and [built clang from scratch](https://chromium.googlesource.com/chromium/src/+/master/docs/clang.md#using-plugins). here is detailed instruction.

```sh
$ xcode-select --install
$ brew install -s cmake
$ # at ./ungoogled-chromium/build/src
$ ./tools/clang/scripts/build.py --without-android --without-fuchsia --use-system-cmake
```

**Comment by Mouvedia** [comment]
If you experience https://github.com/pyenv/pyenv/wiki/Common-build-problems#build-failed-error-the-python-zlib-extension-was-not-compiled-missing-the-zlib try pyenv/pyenv#1737

**Comment by PF4Public** [comment]
Is this still an issue? If so, please file this issue with the corresponding platform repo: [ungoogled-software/ungoogled-chromium-macos](https://github.com/ungoogled-software/ungoogled-chromium-macos)
