### ISSUE TITLE
Reapplication of patch fails during rebuilding of chrome on OSX

### ISSUE THREAD

**Issue by se4u** [Eloston/ungoogled-chromium#126]
I have been trying to compile the `ungoogled-chrome` on my osx system today, and the latest stumbling block seems to be the application of patches when the compilation fails. I am using the 
`master` branch for building. I have tried to change `quiltrc` to force the application of patches, but I thought that I should report the issue as well.

```
2016-11-26 17:39:34,710 - WARNING: Sandbox patches directory already exists. Trying to unapply...
Removing patch ../patches/ungoogled-macos/fix-cups-on-10.12.patch
Restoring printing/backend/print_backend_cups.cc

Removing patch ../patches/ungoogled-macos/disable-symbol-order-verification.patch
Restoring chrome/chrome_dll.gypi

Patch ../patches/ungoogled-macos/disable-warnings-as-errors.patch does not remove cleanly (refresh it or enforce with -f)
2016-11-26 17:39:35,426 - ERROR: Quilt returned non-zero exit code: 1
Traceback (most recent call last):
  File "build.py", line 59, in <module>
    exit(main())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1

/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/_sitebuiltins.py(26)__call__()
-> raise SystemExit(code)
(Pdb) Traceback (most recent call last):
  File "build.py", line 59, in <module>
    exit(main())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1
```

**Comment by se4u** [comment]
I was able to get past this error by adding the `-f` flag to the `quilt pop` command that is executed in the `QuiltPatchComponent` here 

```
-            result = self._run_subprocess([self.quilt_command, "pop", "-a"],
+            result = self._run_subprocess([self.quilt_command, "pop", "-af"],
```

IMO adding a verbose flag in the `pop` and `push` command would also be useful. 
Alternatively a `.quiltrc` file can be used as follows:

```
QUILT_POP_ARGS="--color=auto -f"
QUILT_PUSH_ARGS="--color=auto -f"
```

**Comment by Eloston** [comment]
You're trying to rebuild? In that case, make sure you comment out some lines in `build.py` so it won't re-extract the source code and then try to unapply patches. `build.py` should be treated as an example build script.

If you didn't do that, then you can try to salvage your sandbox by moving the `out` directory somewhere else, setup the sandbox again without building, move the `out` directory back, and then just run the build command.

(FYI, this design isn't friendly to end-users, so this is one of several reasons why #125 exists.)

Also I wouldn't recommend using the `-f` flag. That just makes things messier. But if it works for you, that's fine.

**Comment by se4u** [comment]
Hi Eloston, I was finally able to get time to report my experience with building `ungoogled-chromium`. I also give a patch for a small `TODO`. Hopefully this feedback will be useful in designing the build system, or for future issues about installation on osx. Thanks again for this great project, I had first wanted to build `chromium` 6 months ago to remove google specific components when I first found out that [chrome and chromium run involuntary marketing research on all computers and send the result back to google](https://bugs.chromium.org/p/chromium/issues/detail?id=318572).

1. While running quilt the environment variables `QUILT_SERIES` and `QUILT_PATCHES` are passed to the `quilt` program in calls like these:
```python
result = self._run_subprocess([self.quilt_command, "push", "-a"],
                                      append_environ=self.quilt_env_vars,
                                      cwd=str(self._sandbox_dir))
```
it will be great if these two variables are printed out because they change the default behavior of quilt of looking for a `series` file, which is what most documentation online says that quilt is looking for. I wasted some time at this step when quilt was throwing up at this step and I was trying to debug quitl and I could not find the `series` file.

2. The rebuilding of chromium fails currently, for example if there is an error at the `quilt push` stage, and I rebuild the code, then the build crashes at the `quilt pop` stage, which is frustrating because that means I have to delete the build folder and start again.

3. Currently the OSX build guides people to use the `g++-4.9` compiler. This is bad/wrong advice. The [chromium developers have moved to clang for linux and osx](https://chromium.googlesource.com/chromium/src/+/master/docs/clang.md) and I can attest that clang is much faster than `g++`. Furthermore I was unable to finish building using `g++` but that might just be because of error on my part. 

We can switch from `g++` to `clang` by changing the files `buildlib/macos.py` and `resources/macos/patches/ungoogled-macos/fix-libcxx-archive-build-script.patch`
```patch
-        gxx_compiler = shutil.which("g++-4.9")
+        gxx_compiler = shutil.which("clang-3.9")
```

```patch
-+CXX=g++-4.9
++CXX=clang-3.9
```

Also I found that I was unable to compile chromium using the macport's version of clang, instead, I directly downloaded [Clang for Mac OS X](http://llvm.org/releases/3.9.0/clang+llvm-3.9.0-x86_64-apple-darwin.tar.xz) from LLVM's website.

4. Checking the macOS SDK version is definitely important. I did not know about the SDK requirement in the beginning and I can confirm that chromium can not be built with `SDK 10.12`, because I wasted a lot of time with errors like `unexpected token: !tapi-tbd-v2` etc.
Please add the following code to `buildlib/macos.py` in place of the `TODO` to check for SDK version 

```patch 
- # TODO: Maybe add check for macOS SDK version
+ assert subprocess.run("xcrun --show-sdk-version", shell=True, stdout=subprocess.PIPE, universal_newlines=True).stdout.strip() in ["10.10",]
``` 

5. Finally, it would be pretty sweet if there was a way to bypass the step where 7,000 files are untarred from the chromium source code and put into a source hierarchy. This step takes 4 minutes _only_ but it occurs fairly early in the build process and it's hard to skip this step, so even this step doesn't take a long time in the grand scheme, some people might have to rerun this step a number of times during debugging and that can be frustrating.

```
2016-11-27 02:36:35,626 - INFO: Extracting source archive into building sandbox...
2016-11-27 02:36:35,626 - DEBUG: Appending resources/common/cleaning_list
2016-11-27 02:40:40,895 - ERROR
```

**Comment by Eloston** [comment]
>  I had first wanted to build chromium 6 months ago to remove google specific components when I first found out that chrome and chromium run involuntary marketing research on all computers and send the result back to google.

Well welcome to the club! I actually started hacking on Chromium for similar reasons starting around version 25 or something, but decided to create this project  much later on.

> it will be great if these two variables are printed out because they change the default behavior of quilt of looking for a series file, which is what most documentation online says that quilt is looking for. I wasted some time at this step when quilt was throwing up at this step and I was trying to debug quitl and I could not find the series file.

I didn't think about printing the variables because they aren't something that change. If you look at `common.py`, the constructor of `QuiltPatchComponent` class defines `quilt_env_vars`. `_sandbox_dir` is defined in the constructor of `Builder`. (FYI, these are the ancestor classes for the macOS builder).

I never really anticipated anyone to have problems with the patching system and attempt to go about the way you did to figure it out.

> The rebuilding of chromium fails currently, for example if there is an error at the quilt push stage, and I rebuild the code, then the build crashes at the quilt pop stage, which is frustrating because that means I have to delete the build folder and start again.

Rebuilding is more challenging because there's no function for cleaning up the sandbox. Re-running `build.py` without any modifications will just try to stomp over what's already there. Because I never really thought anyone else would do rebuilding other than me, I would just manipulate the files as I needed (e.g. modify stuff in `resources`, and then modify `build.py` to run only certain steps). Whenever I changed my patches and wanted to rebuild, I would use `developer_utilities/quilt_patches.py` as a quilt proxy that takes care of the environment variables for me.

To use buildlib effectively for other situations, one basically has to know what it's doing at each step. This is why the design document exists, but it's supposed to be a general overview and not a replacement for reading the source code.

Also, I have this line in the building document:
```
Currently, there is no command-line-configurable build script. You must create a script or modify build.py to use buildlib.
```
This is supposed to imply that `build.py` is the means for the user to use `buildlib`. It's not a general-purpose script that uses `buildlib`.

> Currently the OSX build guides people to use the g++-4.9 compiler. This is bad/wrong advice. The chromium developers have moved to clang for linux and osx and I can attest that clang is much faster than g++. Furthermore I was unable to finish building using g++ but that might just be because of error on my part.

I think you're confused. `g++` is only used for building a static version of `libc++` that's required for building the rest of the macOS build. Clang is used for everything else. This is more evident in the gyp flags for macOS, and somewhat in buildlib. When I was working on macOS support with 9Morello (in another issue report), we discovered that Google couldn't get clang to build `libc++` properly (and neither could we), so we tried `g++` and it worked.

> Also I found that I was unable to compile chromium using the macport's version of clang, instead, I directly downloaded Clang for Mac OS X from LLVM's website.

FYI, `buildlib` does this for you and extracts it to the proper location. Or maybe it doesn't in the latest tag. I can't remember when I implemented this change, but I know I did it.

> Checking the macOS SDK version is definitely important. I did not know about the SDK requirement in the beginning and I can confirm that chromium can not be built with SDK 10.12, because I wasted a lot of time with errors like unexpected token: !tapi-tbd-v2 etc.
Please add the following code to buildlib/macos.py in place of the TODO to check for SDK version

Forgot to document that. Also thanks for the code snippet!

> Finally, it would be pretty sweet if there was a way to bypass the step where 7,000 files are untarred from the chromium source code and put into a source hierarchy. This step takes 4 minutes only but it occurs fairly early in the build process and it's hard to skip this step, so even this step doesn't take a long time in the grand scheme, some people might have to rerun this step a number of times during debugging and that can be frustrating.

This is supposed to be a one-time deal. Unless you accidentally screwed up some files or you screwed up when using `quilt`, there should be no need to re-extract the source code again. Like I mentioned earlier, you're supposed to modify `build.py` to do what you need it to do.

Well it seems you had a pretty rough time trying to get ungoogled-chromium to build, and mostly all of it is due to a poorly designed user interface and lack of documentation. Many thanks for your feedback as that'll help me design the new build system.
