### ISSUE TITLE
Ungoogled Chromium Does Not Support WebGL

### ISSUE THREAD

**Issue by MrTeeXD** [Eloston/ungoogled-chromium#1267]
**Describe the bug**
So, I tried to use a website called StreamRaiders and when I wanted to join a Battlefield, an error pops up saying "Your browser does not support WebGL"

**To Reproduce**
There is no steps to reproduce

**Expected behavior**
I expected Ungoogled Chromium to run WebGL Games well instead of making the website throw that kind of error

**Screenshots**
![chrome_oVQGmYWthJ](https://user-images.githubusercontent.com/37266538/100529848-032d1700-31f4-11eb-9ef6-ceda55d5bcc1.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Windows 10 64Bit Build 20H1
 - ungoogled-chromium version: 86.0.4240.183-1

**Comment by mbakke** [comment]
Do the experiments listed here work for you?

https://experiments.withgoogle.com/search?q=webgl

**Comment by MrTeeXD** [comment]
I have tested and some of them dont work

**Comment by mbakke** [comment]
That is a Windows-specific packaging problem, you could try filing an issue over at https://github.com/ungoogled-software/ungoogled-chromium-windows

(IOW https://get.webgl.org/ works on GNU/Linux, so it's unlikely to be related to the ungoogled patches from this repository)

**Comment by MrTeeXD** [comment]
Alright, I am now gonna file a issue there and closing this.

**Comment by tnaftali** [comment]
Hi, this is happening for me on Linux, specifically on Debian 10 Buster.

> Version 90.0.4430.212 (Developer Build, ungoogled-chromium) built on Debian buster/10, running on Debian buster/10 (64-bit)

Is there a fix?

**Comment by mattalexx** [comment]
[SketchUp](https://app.sketchup.com/app?hl=en):

![Screen](https://i.imgur.com/GeX54uu.png)

**Comment by PF4Public** [comment]
Please try https://get.webgl.org/. I see no issues:
![image](https://user-images.githubusercontent.com/10319700/173114203-9bcafcd3-357c-4d39-b75b-6251b3b59146.png)

Also please mention your OS/platform.

**Comment by mattalexx** [comment]
> Also please mention your OS/platform.

Oops, added.

The https://get.webgl.org/ works.

**Comment by euromoon** [comment]
Also happening with me, no WebGL application works on `Linux 6.1.1-1-MANJARO` and `ungoogled-chromium-bin 108.0.5359.124-1` from AUR.

Log messages from `chrome://gpu`:
```
GpuProcessHost: The GPU process exited normally. Everything is okay.
GpuProcessHost: The GPU process exited normally. Everything is okay.
GpuProcessHost: The GPU process exited normally. Everything is okay.
GpuProcessHost: The GPU process exited normally. Everything is okay.
[9181:9181:0114/175632.560084:ERROR:angle_platform_impl.cc(43)] : Display.cpp:1004 (initialize): ANGLE Display::initialize error 0: Internal Vulkan error (-3): Initialization of an object could not be completed for implementation-specific reasons, in ../../third_party/angle/src/libANGLE/renderer/vulkan/RendererVk.cpp, initialize:1430.
GpuProcessHost: The GPU process exited normally. Everything is okay.
[9236:9236:0114/175632.623364:ERROR:angle_platform_impl.cc(43)] : Display.cpp:1004 (initialize): ANGLE Display::initialize error 0: Internal Vulkan error (-3): Initialization of an object could not be completed for implementation-specific reasons, in ../../third_party/angle/src/libANGLE/renderer/vulkan/RendererVk.cpp, initialize:1430.
[9236:9236:0114/175632.623520:ERROR:gl_display.cc(508)] : EGL Driver message (Critical) eglInitialize: Internal Vulkan error (-3): Initialization of an object could not be completed for implementation-specific reasons, in ../../third_party/angle/src/libANGLE/renderer/vulkan/RendererVk.cpp, initialize:1430.
[9236:9236:0114/175632.624136:ERROR:gl_display.cc(920)] : eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[9236:9236:0114/175632.624400:ERROR:gl_ozone_egl.cc(23)] : GLDisplayEGL::Initialize failed.
[9236:9236:0114/175632.634390:ERROR:viz_main_impl.cc(186)] : Exiting GPU process due to errors during initialization
GpuProcessHost: The GPU process exited normally. Everything is okay.
[9261:9261:0114/175632.710429:WARNING:vaapi_wrapper.cc(792)] : VAAPI video acceleration not available for disabled
[9261:9261:0114/175632.710560:ERROR:gpu_init.cc(523)] : Passthrough is not supported, GL is disabled, ANGLE is
```

**Comment by rsoyxihnark** [comment]
also happening on https://earth3dmap.com/3d-globe/

**Comment by ZsoltHevesi** [comment]
Still happening as of June 29/2024

**Comment by James-E-A** [comment]
Seeing this issue as well with Ungoogled Chromium 141.0.7390.107 on Windows 11 with an AMD Radeon HD 7570M GPU (stock in HP EliteBook 8470p laptop).

OS build 26100.7171, and I *am* running the latest available version of the GPU driver (15.201.1301.0).

> # get\.webgl\.org
>
> Hmm. While your browser seems to support WebGL, it is disabled or unavailable. If possible, please ensure that you are running the latest drivers for your video card.

<details>
<summary>“Problems Detected” from `chrome://gpu`</summary>

*   WebGPU has been disabled via blocklist or the command line.
    Disabled Features: webgpu

*   WebGL2 has been disabled via blocklist or the command line.
    Disabled Features: webgl2

*   Accelerated rasterization has been disabled, either via blocklist, about:flags or the command line.
    Disabled Features: rasterization

*   Accelerated video encode has been disabled, either via blocklist, about:flags or the command line.
    Disabled Features: video_encode

*   Accelerated video decode has been disabled, either via blocklist, about:flags or the command line.
    Disabled Features: video_decode

*   WebGL has been disabled via blocklist or the command line.
    Disabled Features: webgl

*   Gpu compositing has been disabled, either via blocklist, about:flags or the command line. The browser will fall back to software compositing and hardware acceleration will be unavailable.
    Disabled Features: gpu_compositing

*   Accelerated 2D canvas is unavailable: either disabled via blocklist or the command line.
    Disabled Features: 2d_canvas

*   8.17.10.\* AMD drivers are buggy: [298968](http://crbug.com/298968), [1069262](http://crbug.com/1069262)
    Disabled Features: accelerated_2d_canvas,
        accelerated_webgl,
        accelerated_video_decode,
        accelerated_video_encode,
        gpu_tile_rasterization,
        accelerated_webgl2,
        accelerated_gl,
        vulkan,
        accelerated_webgpu,
        skia_graphite,
        webnn,
        direct_rendering_display_compositor
    Please update your graphics drive via this link

*   8.17.10.* AMD drivers trigger hangs in video stack: [1160623](http://crbug.com/1160623)
    Disabled Features: accelerated_video_decode

*   Some drivers are unable to reset the D3D device in the GPU process sandbox
    Applied Workarounds: exit_on_context_lost

*   Disable KHR_blend_equation_advanced until cc shaders are updated: [661715](http://crbug.com/661715)
    Applied Workarounds: disable(GL_KHR_blend_equation_advanced),
        disable(GL_KHR_blend_equation_advanced_coherent)

*   Zero-copy DXGI video hangs or displays incorrect colors on older AMD drivers: [623029](http://crbug.com/623029), [1025427](http://crbug.com/1025427)
    Applied Workarounds: disable_dxgi_zero_copy_video

*   NV12 DXGI video displays incorrect colors on older AMD drivers: [644293](http://crbug.com/644293)
    Applied Workarounds: disable_nv12_dxgi_video

*   Expose WebGL's disjoint_timer_query extensions on platforms with site isolation: [808744](http://crbug.com/808744), [870491](http://crbug.com/870491)
    Applied Workarounds: enable_webgl_timer_query_extensions

*   Don't use video processor scaling on non-Intel, non-NVIDIA GPUs and older AMD GPUs: [993233](http://crbug.com/993233)
    Applied Workarounds: disable_vp_scaling

*   Hardware overlays fail to work on older AMD drivers: [932879](http://crbug.com/932879), [1025427](http://crbug.com/1025427)
    Applied Workarounds: disable_direct_composition_video_overlays

*   dynamic textures fail to work on AMD GPUs: [1029855](http://crbug.com/1029855), [1050666](http://crbug.com/1050666)
    Applied Workarounds: disable_nv12_dynamic_textures

*   Limit D3D11VideoDecoder to 11.0 due to crashes on AMD: [1012464](http://crbug.com/1012464)
    Applied Workarounds: limit_d3d11_video_decoder_to_11_0

*   Software overlays fail to work reliably on AMD devices: [1161215](http://crbug.com/1161215), [1160217](http://crbug.com/1160217)
    Applied Workarounds: disable_direct_composition_sw_video_overlays

*   Windows hardware decoding doesn't support a set of legacy AMD GPUs: [822644](http://crbug.com/822644), [1187900](http://crbug.com/1187900)
    Applied Workarounds: disable_accelerated_av1_decode,
        disable_accelerated_vp8_decode,
        disable_accelerated_vp9_decode

*   Only enable video processor super resolution on Intel Gen10+ GPUs and NVIDIA GPUs with 530+ drivers: [1318380](http://crbug.com/1318380)
    Applied Workarounds: disable_vp_super_resolution

*   Disable Media Foundation Clear Playback on older AMD drivers.
    Applied Workarounds: disable_media_foundation_clear_playback

*   Only enable video processor auto HDR on NVIDIA GPUs with 550.50+ driver: [1445741](http://crbug.com/1445741)
    Applied Workarounds: disable_vp_auto_hdr

*   Disable SVC video encoding on AMD GPUs that can't change bitrate in SVC mode: [1439689](http://crbug.com/1439689)
    Applied Workarounds: disable_svc_encoding

*   Disable VP9 k-SVC video decoding on non-Intel GPUs: [1508379](http://crbug.com/1508379)
    Applied Workarounds: disable_d3d11_vp9_ksvc_decoding

*   Block all NPU drivers except Intel driver versions >= 32.0.100.3053 for WebNN: [341327464](http://crbug.com/341327464)
    Applied Workarounds: disable_webnn_for_npu

*   Disable overlay promotion for clear video quads when their MPO quads would move: [40677119](http://crbug.com/40677119)
    Applied Workarounds: disable_video_overlay_if_moving

*   Forcing RGB10A2 overlay due to MSFT bug, this enables HDR to take overlay path for AMD: [394610795](http://crbug.com/394610795)
    Applied Workarounds: force_rgb10a2_overlay_support

*   Disable software bitrate control for H.264 encoding on AMD GPUs on Windows.: [417752242](http://crbug.com/417752242)
    Applied Workarounds: disable_h264_accelerator_sw_brc

*   D3D12 video encoder produces video streams with artifacts on AMD GPUs.: [40275246](http://crbug.com/40275246)
    Applied Workarounds: disable_d3d12_video_encoder
</details>

**Comment by James-E-A** [comment]
A simple workaround, worked for me to at least get websites that nominally require WebGL working, (wasn't too easy to find since it didn't show up searching the flags for "webgl"), obviously will have whatever caveats:

`chrome://flags/#ignore-gpu-blocklist`

**Comment by eurmn** [comment]
​I previously had this issue on Manjaro, but it seems resolved for me now. I've switched to CachyOS and WebGL is working fine on both my devices.
​If you are still experiencing this, make sure your vulkan and mesa drivers are installed. It might also be worth trying the linux-cachyos kernel from the AUR to see if the issue persists with a different kernel (maybe there's something to do with cpu specific patches).
