### ISSUE TITLE
Always crash on every tab on Windows

### ISSUE THREAD

**Issue by hronro** [Eloston/ungoogled-chromium#1301]
**Describe the bug**
I installed ungoogled-chromium from [scoop](https://github.com/lukesampson/scoop) package manager, and it always crash on every tab.

**To Reproduce**
1. Go to any page
1. Tabs crashes

**Expected behavior**
The tab shouldn't crash.

**Screenshots**

https://user-images.githubusercontent.com/15059605/103122329-b6394500-46ba-11eb-8ef2-7edc41a102e6.mp4

**Environment (please complete the following information):**
 - OS/Platform and version: Windows 10 1809
 - ungoogled-chromium version: 87.0.4280.67-1

**Comment by CANADIANPIG** [comment]
Sadly I am experiencing the same issue. The issue occurred right after I set up a junction for my user profile due to having a small SSD. A fresh install using the repos available fails, but installing it using chocolatey package manager works fine. Sadly, the choco version is not a viable alternative due to not being recognized by windows as a web browsing program and cannot be set to default. 

Version 88.0.4324.182
Windows 10 Home v. 20H2

**Comment by Jestar342** [comment]
Same with 89.0.4389.90-1

**Comment by PF4Public** [comment]
Is this still an issue? If so, please file this issue with the corresponding platform repo: [ungoogled-software/ungoogled-chromium-windows](https://github.com/ungoogled-software/ungoogled-chromium-windows)

**Comment by hronro** [comment]
Sorry for the late update, this issue seems like only happens when ungoogled-chromium is installed via scoop.

Check the related issue here: https://github.com/lukesampson/scoop-extras/issues/5479
