### ISSUE TITLE
Ungoogled Chromium: Updates

### ISSUE THREAD

**Issue by KrowofAgony** [Eloston/ungoogled-chromium#1317]
I have noticed that Ungoogled Chromium has been updated for what I have circled, yet here is my gripe with it. Software updating tools such as UCheck picks up the software in their server (it may be a bit broken), and these haven't been updated to the latest build of Chromium. As an IT Student, this could be a major problem. It is similar to what I am facing with VPN Unlimited (still have NOT updated their Chrome/Chromium extension).

I would appreciate it if you have the latest build of Ungoogled Chromium. Chromium is constantly updating (see: https://chromium.woolyss.com/), and there should be NO EXCUSE why it has NOT been updated. I do enjoy this browser and I would like to see it being updated.

The workaround (as far as I know of) to this problem is to allow UCheck to download/install Chromium. This does NOT have the Ungoogled dependencies.

Please see the images that are listed below:

![Ungoogled Chromium](https://user-images.githubusercontent.com/7153059/104038376-09bf8e80-51a3-11eb-8bc7-2a6344f9c106.png)

![ucheck error ungoogled chromium 1-8-2021](https://user-images.githubusercontent.com/7153059/104038820-8f433e80-51a3-11eb-9041-3d67e339a202.png)

Thank you!

**Comment by catthou** [comment]
This is one of the most bizarre complaints I've seen, considering that your question is answered right there on the page:

> IMPORTANT: These binaries are provided by anyone who are willing to build and submit them. ... each download page lists the GitHub user that submitted those binaries.

Those binaries are not officially maintained versions of UC. The UC project itself isn't really established to provide pre-compiled binaries, only to help establish the environment where you can compile UC yourself. One of the major beneifts of self-compiled code is security; the downloads page also reads, "authenticity cannot be guaranteed." - indicating that the binaries there are not seriously vetted. It's not a coincidence that one of the reasons people don't trust ordinary chrome and even chromium, is because so many of its components are closed-source or provided to chromium precompiled. If you choose to trust the binaries listed on that page, you're doing so counter to the fundamental principle of UC, and at your own risk and at the mercy of those people who would be willing to provide such compiled binaries (both in terms of security and up-to-datedness). If you find your particular OS is falling too far behind current release for your liking, consider private messaging the user who compiled it offering them some kind of compensation to provide an update.

**Comment by blackbeardth** [comment]
@KrowofAgony they devs are not at all obligated to provide updates. it is not like brave or firefox, UC is just a community project. (although updates have been fairly regular)
