### ISSUE TITLE
Version 53 build failure on Debian stretch.

### ISSUE THREAD

**Issue by bradx954** [Eloston/ungoogled-chromium#132]
`warning: unknown warning option '-Wno-undefined-var-template'; did you mean '-Wno-undefined-internal'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-nonportable-include-path'; did you mean '-Wno-gnu-include-next'? [-Wunknown-warning-option]
../../printing/backend/print_backend_cups.cc:243:21: error: use of undeclared identifier 'cupsGetPPD'
    ppd_file_path = cupsGetPPD(name);
                    ^
../../printing/backend/print_backend_cups.cc:256:21: error: use of undeclared identifier 'cupsGetPPD2'
    ppd_file_path = cupsGetPPD2(http.http(), name);
                    ^
2 warnings and 2 errors generated.
[9649/19401] CXX obj/device/bluetooth/device_bluetooth.bluetooth_remote_gatt_characteristic.o`

This seems to be the issue 

> ../../printing/backend/print_backend_cups.cc:243:21: error: use of undeclared identifier 'cupsGetPPD'

Version:
53.0.2785.116-1.2

**Comment by bradx954** [comment]
This is more likely an issue with cups or the chromium source code but would like to hear about possible fixes or workarounds.

**Comment by Eloston** [comment]
Chromium 53 is going to be phased out very soon. If you want, you can use a snapshot of the repo at 1a246c50b9c78a95c024442156d244baff26c54a and build Chromium 54 (which is what I'm using right now). I haven't tagged 54 because I didn't finish porting to all of the platforms. But I just discovered that Chromium 55 released, so I'm currently in the middle of upgrading the patches to that.

**Comment by bradx954** [comment]
Thanks for getting back to me. This will work great thanks. I look forward to 55 being available in the future.
