### ISSUE TITLE
[Windows] please provide pre built binaries in release section from latest code

### ISSUE THREAD

**Issue by Snowden-rgb** [Eloston/ungoogled-chromium#1322]
**Is your feature request related to a problem? Please describe.**
Well, it is really a very bad experiencing for newbies or noobs to first install ungoogled chromium and update, often the prebuilt binaries from volunteers are a month old and can't match up to the latest code, also they can be harmful or tampered( a small possibility)
**Describe the solution you'd like**
provide pre built binaries/packages in release section matching up to the latest code

**Comment by wchen342** [comment]
There are binaries available for certain platforms in their corresponding platform repo (Debian/Ubuntu, Fedora, Android), and Guix has a general build for any Linux-based system. What platform are you on?

I believe this has been discussed before and splitting platforms into their separate repos was the conclusion. The reason why there is not a centralized binary release is because each platform has different additional steps/patches/dependencies so they need different updates after the main repo gets updated. For example, if you go to the [Debian](https://github.com/ungoogled-software/ungoogled-chromium-debian) and [Arch](https://github.com/ungoogled-software/ungoogled-chromium-archlinux) repo you will see that they have different patches and different way of building. If you go to the [Android](https://github.com/ungoogled-software/ungoogled-chromium-android) repo you can see it is even more different from Linux ones. Also different platforms are maintained by different people in addition to the main repo, so this results in a complicated situation and that is why we do not compile all versions together and put them here.

**Comment by Snowden-rgb** [comment]
i agree, but the only os left behind in this case is windows 10,all other os'es have builds from latest code, so there is a need for windows automated builds

**Comment by Gxtod** [comment]
Here you can download the **Ungoogled** assembly for **Win64** from **Marmaduke** https://chromium.woolyss.com/#windows-64-bit

**Comment by Snowden-rgb** [comment]
> 
> 
> Here you can download the **Ungoogled** assembly for **Win64** from **Marmaduke** https://chromium.woolyss.com/#windows-64-bit

It is based on ungoogled chromium, but it still has widevine module installed, which is not a part of vanilla ungoogled chromium

**Comment by jacob755** [comment]
somenody please build  32 bit version

**Comment by Eloston** [comment]
Windows code has been updated along with binaries. Closing.

**Comment by Snowden-rgb** [comment]
> 
> 
> Windows code has been updated along with binaries. Closing.

how do we update?
