### ISSUE TITLE
Problem building on Windows: GN bootstrapping problem

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#137]
[I'm having troubles trying to boostrap GN via the `bootstrap.py` script.](https://gist.github.com/Eloston/2647cff8f48322ace02e6ae93c255568)

Here's what I did to get to this point:
* Pull the current state of the master branch
* Setup the build dependencies according to BUILDING.md
  * Used `builder.path_overrides` in `build.py` for `python`, `bison`, `gperf`, `patch`, and `ninja`
* In `bootstrap.py` within the `check_call()` definition, add `kwargs["shell"] = True` right before the `subprocess.check_call` function call.
* EDIT: Open a VS 2015 Developer Console and invoke `build.py` with it (this sets environment variables for the bootstrap script)

Then the build fails with that error linked above. Does anyone have any ideas?

**Comment by nopjmp** [comment]
It looks like it's a bug upstream that they fixed recently. I'm able to replicate it on my system. I'll see if I can figure something out.

**Comment by nopjmp** [comment]
I got it fixed. The bootstrap.py file needed to be updated. I'm fixing up the other parts of the Windows build now as well and will submit a pull request with my changes once I'm done.

**Comment by waqas** [comment]
Any progress on Windows build? I am checking this every few hours since last couple of weeks :)

**Comment by nopjmp** [comment]
Not much progress except it's at least building to linking. There was a wierd patch problem because git converted the LFs to CRLFs on the line endings. I got a linker error yesterday probably because I kept stopping the build.

It takes several hours on my machine to compile and can be quite annoying to deal with. I'd check back next week or this weekend instead of what you are doing.

**Comment by Eloston** [comment]
@waqas In the future, you can just click the "subscribe" button on the side to listen to notifications.

@nopjmp GNU patch from MSYS2 (which I tell users to use) seems to be fine with different line endings. What are you using to apply patches?

**Comment by nopjmp** [comment]
@Eloston I forgot about the subscribe button. I'm using GNU patch from MSYS2 the problem is the patches were never applied due to how Python was working. Switching to -i and providing the full path resolved the issue. I'm going to try to build again tonight and see if I can fix my problems.

Sent from my android device.

-----Original Message-----

**Comment by Eloston** [comment]
@nopjmp The subscribe button message wasn't for you. Anyways, it's puzzling that you needed to invoke patch that way, because it worked fine before by passing the patch data in via stdin (and it still did when I attempted to build and got that error)

**Comment by nopjmp** [comment]
@Eloston I should have known about it when telling wasqas. There was no error that was the problem, it just didn't actually patch anything until I switch to the other method.

Building now

**Comment by nopjmp** [comment]
Everything built. creating a branch and pushing individual commits for review this might take a bit.

**Comment by Eloston** [comment]
Fixed in #147.
