### ISSUE TITLE
Raspberry Pi Zero W (architecture: armv6l) Segmentation Fault

### ISSUE THREAD

**Issue by nestukh** [Eloston/ungoogled-chromium#1409]
**Bug Description**
Ungoogled Chromium and Ungoogled ChromeDriver install fine on Raspberry Pi Zero W (using current Raspberry Pi OS), but can't run: they produce general error -11 on Selenium via Python and "segmentation fault" on the command line.
Normal `chromium-browser` and `chromedriver` run fine with no problems.
Same Ungoogled Chromium and Ungoogled ChromeDriver run fine on Raspberry Pi 3B+ (armv7l).

**To Reproduce**
Install them on a raspberry pi zero with the usual Debian commands (here optimized to minimize problems):
```
echo 'deb https://download.opensuse.org/repositories/home:/ungoogled_chromium/Debian_Buster/ /' | sudo tee /etc/apt/sources.list.d/home:ungoogled_chromium.list > /dev/null
curl -fsSL https://download.opensuse.org/repositories/home:ungoogled_chromium/Debian_Buster/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home:ungoogled_chromium.gpg > /dev/null
sudo chmod a+r /etc/apt/trusted.gpg.d/home:ungoogled_chromium.gpg
sudo chmod a+r /etc/apt/sources.list.d/home:ungoogled_chromium.list
sudo apt update <&-
sudo apt-get purge -y chromium* <&-
sudo apt install -y ungoogled-chromium* <&-
sudo apt install -y --reinstall ungoogled-chromium* <&-
```
then try `chromedriver --version` and `chromium --version`. 
I.e., `chromedriver --version` produces:
`segmentation fault`

**Expected behavior**
`chromedriver --version` should output (copied from a raspberry pi 3b+):
`ChromeDriver 88.0.4324.182 (73ee5087001dcef33047c4ed650471b225dd8caf-refs/branch-heads/4324@{#2202})`

**Environment**
 - OS/Platform and version: current Raspberry Pi OS, current kernel 5.10.11+, armv6l, on Raspberry Pi Zero W.
 - ungoogled-chromium version: current 88.0.4324.182

**Additional context**
Normal chromium packages (installable via `sudo apt-get install -y chromium-browser chromium-chromedriver <&-`) return:
`chromium-browser --version`:
`Chromium 86.0.4240.197 Built on Raspbian , running on Raspbian 10`
and
`chromedriver --version`:
`ChromeDriver 86.0.4240.197 (95c2dcda508cfa603b9a5575bda23ab5f3da1383-refs/branch-heads/4240@{#1425})`

**Comment by nestukh** [comment]
months later this bug is still valid. Why no input from the devs?

**Comment by Eloston** [comment]
Usually this issue tracker is for general questions, not platform-specific ones. So it's likely this issue got overlooked. I cleared that up in the docs yesterday.

The Raspberry Pi Zero W runs a ARMv6 ISA, but it seems that ungoogled-chromium is built with ARMv7: https://build.opensuse.org/package/show/home:ungoogled_chromium/ungoogled-chromium-buster. On the other hand, Raspberry Pi 3b+ runs with a ARMv8 ISA, so ungoogled-chromium runs fine on it.

I'm not sure how the official Chromium packages are built. Since we follow upstream's changes, it's likely that just our build configuration differs.

BTW, the Pi Zero W only has 512 MB of RAM. That's gonna be pretty tight for any modern web browser.

**Comment by DevOps-Arts** [comment]
hi guys i can run any linux app on raspberry pi zero contact with me on gmail : [cybersecurty922@gmail.com](mailto:cybersecurty922@gmail.com)
skype: live:rehmanazhar922

i created my custom raspberry pi zeo image of armel architecture armel can run all

all the raasp os are armhf thats why error : armv7

Pakistani Hacker: Pakistan zindabaad!
