### ISSUE TITLE
Simplify disable-domain-reliability.patch

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#1464]
See suggestion here: https://github.com/bromite/bromite/issues/986#issuecomment-793151943

We should compare existing patch & new patch to confirm change is effectively the same or better.

**Comment by Ahrotahn** [comment]
I spent some time looking into it and can confirm that seems to be all that is needed.  

I don't know the history for the existing changes; maybe the reason for being so extensive was worry that it would become part of safe browsing's metastasis?  At any rate there hasn't been any changes since then that would indicate it would be used outside of it's current context.  

If another unreachable code warning isn't a problem then the change could be further simplified to just inserting the return at the top of the function, but I think @csagan5's proposal is the better way to go.  If a failsafe is needed then the change to `uploader.cc` at the end of the current patch could be kept so that reports would be discarded in the event one somehow gets made.

**Comment by Eloston** [comment]
> I don't know the history for the existing changes; maybe the reason for being so extensive was worry that it would become part of safe browsing's metastasis?

I think that's one reason. I believe another implicit rule is to de-bloat the browser. The current patch does a pretty good job by removing the baked-in configs, and also some configs hard-coded in the C++ code.

There is a trade-off between debloating and maintenance burden. Finding the balance is tricky, but perhaps if the patch does not change often, it might be okay to keep it as-is. Continuing this thinking, the new change might reduce runtime burden if we prevent another unnecessary service from starting.

>  If a failsafe is needed then the change to uploader.cc at the end of the current patch could be kept so that reports would be discarded in the event one somehow gets made.

Yeah, I agree. Combining with my previous statements, we could simplify the patch by replacing all the C++ changes with the suggested change (but keeping the `uploader.cc` change). I am thinking that keeping the changes to GN and Python code can still reduce some bloat.

**Comment by Ahrotahn** [comment]
I don't see an issue with keeping the current patch.  There's no harm in being thorough.  
The only downside is the maintenance burden as you mentioned. But there aren't many changes in the patch's history more significant than updating the line offsets, so it hasn't been an issue yet and doesn't look like it would be any time soon.  

Maybe the change in that thread could be added to the existing patch and a comment could be added at the top noting the redundancy and that the most important changes are in `service_factory.cc` and `uploader.cc`.  If any significant work needs to be done in the future on any other section then they could simply be removed.

**Comment by csagan5** [comment]
I added that extra block to the patch, and some other small changes; see https://github.com/bromite/bromite/blob/90.0.4430.59/build/patches/ungoogled-chromium-Disable-domain-reliability.patch

**Comment by PF4Public** [comment]
In the end, were suggested here changes implemented or not? Is this issue resolved or not?

**Comment by csagan5** [comment]
I am using the modified version in Bromite; it is up to you whether to also use that or keep the current version.
