### ISSUE TITLE
Wiki error on CDM

### ISSUE THREAD

**Issue by methanoid** [Eloston/ungoogled-chromium#1470]
Says

Copy this Widevine CDM plugin's content to your Chromium "WidevineCdm" folder like this following structure, on windows:
(screenshot)
WidevineCdm/
  ├── LICENSE.txt
  ├── manifest.json (Note this file contains the Widevine version or even the file paths ^^)
  │
  ├── _platform_specific/
  │   ├── widevinecdm.dll
  │   ├── widevinecdm.dll.sig

But screenshot structure and text structure disagree AND there is an extra file which isnt mentioned "widevinecdm.dll.lib"

And it doesnt seem to work in EITHER fashion..... :-(

**Comment by vairag22** [comment]
>  But screenshot structure and text structure disagree AND there is an extra file which isnt mentioned "widevinecdm.dll.lib"

The file structure is correct and is valid for all Chromium-based browsers. _WidevineCdm_ folder should be placed inside the directory where Chromium files are present. The screenshot does not match because screenshot is of Chrome not Chromium, but one can get the idea how files should be arranged. The wiki you are mentioning is this: https://chromium.woolyss.com/#widevine right? This wiki is not maintained by Eloston or ungoogled-chromium team. Leave a comment on that page or contact the person who maintains it. And ignore the _widevinecdm.dll.lib_ file, it is useless.

> And it doesnt seem to work in EITHER fashion..... :-(

If you can't get ungoogled-chromium to work maybe try using the builds provided on that site (see top section of the website). There are many variants available including ones with preconfigured DRMs and codecs. I personally use Marmaduke's build (Portable version).

**Comment by methanoid** [comment]
@vairag22 thank you :)  I tried copying the exact files from Marmadukes to the Eloston one and still wont work so maybe they forgot to build with the toggle on.  I'll switch to Marmaduke's, thanks

Any tips for how to safely import my profile without having to re-do all my extensions etc?? ;)

**Comment by vairag22** [comment]
>@vairag22 thank you :) I tried copying the exact files from Marmadukes to the Eloston one and still wont work so maybe they forgot to build with the toggle on. I'll switch to Marmaduke's, thanks

you're welcome (^~^)

> Any tips for how to safely import my profile without having to re-do all my extensions etc?? ;)

1. You have to reinstall all the extensions from scratch. [Wiki](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#can-i-install-extensions-or-themes-from-the-chrome-webstore) and some good [privacy and extension recommendations](https://chromium.woolyss.com/#privacy)
2. For managing passwords you can use Bitwarden, it is available for almost every os and browser.
3. For bookmarks the best you can do is import them by going to _chrome://settings/importData_
4. Sadly sync is not available but I take it as a safety feature, so there's that, and if you really want to sync your saved articles use Pocket (yes, it is that crap that comes bundled with firefox).

btw, if your problem has been solved then consider closing the issue.
