### ISSUE TITLE
Does Ungoogled Chromium include FLoC code?

### ISSUE THREAD

**Issue by ceodoe** [Eloston/ungoogled-chromium#1474]
Is the current FLoC origin trial included in Ungoogled Chromium? How will it be handled once trials are over and it's fully implemented and ready to go in Chromium? Sources mention the code for this trial made it into Chromium (and not just Chrome), and thus I would assume it would propagate downstream to this project. I searched the internet and this issue tracker, but found no mention of Ungoogled's stance on this controversial inclusion in Chromium.

https://www.eff.org/deeplinks/2021/03/google-testing-its-controversial-new-ad-targeting-tech-millions-browsers-heres

https://source.chromium.org/chromium/chromium/src/+/master:components/federated_learning/?q=federated%20learning&ss=chromium%2Fchromium%2Fsrc

https://github.com/WICG/floc/issues/25

**Comment by Ahrotahn** [comment]
The code *exists*, but field trials should not be active unless your version of chromium was built with `fieldtrial_testing_like_official_build=is_chrome_branded`.  Most builds should be made with `fieldtrial_testing_like_official_build=true`, which oddly enough disables the field trials (More info [here](https://source.chromium.org/chromium/chromium/src/+/refs/tags/89.0.4389.114:testing/variations/README.md) and [here](https://source.chromium.org/chromium/chromium/src/+/refs/tags/89.0.4389.114:components/variations/service/BUILD.gn;l=9)).

It also seems to (in it's current implementation) check `https://adservice.google.com/settings/do_ad_settings_allow_floc_poc` for permission to start the trial, so even if the field trials are somehow enabled ungoogled-chromium's domain substitution would prevent that from going through.  

It might be a bit too early to implement a patch right now to remove this since there will likely be a lot of changes to this code in the upcoming releases, but it wouldn't be too difficult to implement a patch before it becomes enabled by default.  

<br/>

Extra info:

That EFF article only links the component part to floc, the rest is [here](https://source.chromium.org/chromium/chromium/src/+/refs/tags/89.0.4389.114:chrome/browser/federated_learning/)

There is a Google blog post [here](https://developer.chrome.com/blog/floc/) that goes into more detail about the trial.

**Comment by notDavid** [comment]
FYI: https://github.com/brave/brave-core/pull/8468 (https://news.ycombinator.com/item?id=26765084)

**Comment by dm17** [comment]
Has this been confirmed?
https://vivaldi.com/blog/no-google-vivaldi-users-will-not-get-floced/ Vivaldi doesn't btw.

**Comment by alexolog** [comment]
Just wanted to add my vote for either removing or disabling this "feature"

**Comment by Peacock365** [comment]
@Eloston 

Seems like Vanadium has patched FLoC, the fix seems applicable to Ungoogled Chromium:

https://github.com/GrapheneOS/Vanadium/blob/11/patches/0078-disable-unused-FLOC-feature.patch

Can we please have the same fix in Ungoogled Chromium?

**Comment by dm17** [comment]
> @Eloston
> 
> Seems like Vanadium has patched FLoC, the fix seems applicable to Ungoogled Chromium:
> 
> https://github.com/GrapheneOS/Vanadium/blob/11/patches/0078-disable-unused-FLOC-feature.patch
> 
> Can we please have the same fix in Ungoogled Chromium?

Are you tracking differences between UG & Vanadium? I'm curious about that too - and wonder if the projects can help deduplicate each others efforts.

**Comment by altwarg** [comment]
According to https://amifloced.org/ last ungoogled chromium does not have FLoC enabled:
![image](https://user-images.githubusercontent.com/34391398/118132089-f8fc7f00-b407-11eb-95ee-f748877210cf.png)

**Comment by Altonss** [comment]
That may be normal, because I think that all Chrome Users don't have Floc enabled either.

**Comment by mdedonno1337** [comment]
What is the current situtation and plan for the FLOC removal?
Should we simply "import" the migitation proposed by other projects?

**Comment by Ahrotahn** [comment]
I've had a patch ready for a while that disables the current implementation, but I've been waiting to see what changes get made before mid-July.  So far it hasn't had as much activity as I thought it would have.  I'll take some time this weekend to update the patch a bit and submit a PR afterwards.

**Comment by Peacock365** [comment]
@Ahrotahn 

Thank you again for the patch. It seems like the Bromite project has failed to implement your patch, they seem to rely entirely on Google's preset conditions for FLoC being enabled. They see no necessity to explicitly patch this, and when I hinted at your patch in frustration, my comment got marked as "disruptive content" (well yes, that is correct, it is meant to "disrupt" the developer's lazy development attitude). If you can, please comment on why a patch is necessary in my stead:

https://github.com/bromite/bromite/issues/1104

You don't have to, but seeing how you are the author of an applicable patch and since I would like to continue using Bromite on mobile, could you please help me out there in the interest of all Bromite users? Thank you.

**Comment by dm17** [comment]
@Peacock365 You might be interested in this effort: https://github.com/Eloston/ungoogled-chromium/discussions/1395
