### ISSUE TITLE
Bug that opens a new window.

### ISSUE THREAD

**Issue by jpuser-ungoogled-chromium** [Eloston/ungoogled-chromium#1477]
Hi!
I'm japanese.
My english is very little. sorry.
I am using translation software.

First, watch the following video.

<ungoogled-chromium 87.0.4280.67 (Windows)> (GOOD!!)
https://www.experimental-address.com/wp-content/uploads/2021/04/87-0-4280-67.mp4

<ungoogled-chromium 89.0.4389.114 (Windows)> (BAD!!)
https://www.experimental-address.com/wp-content/uploads/2021/04/89-0-4389-114.mp4

"89.0.4389.90" and "89.0.4389.114" automatically open a new window.
I am annoyed by this behavior.

For example, try clicking on "Download" at the following address.

https://www.catalog.update.microsoft.com/Search.aspx?q=KB4537491

A new window will open by itself.

This did not happen with "87.0.4280.67".
Is this behavior of "89.0.4389.114" a bug?

87.0.4280.67" will be displayed in a separate tab.
I'd like it to appear in a separate tab, like "87.0.4280.67".

---------------------------------------------------------------------------
 - OS/Platform and version: Windows
 - ungoogled-chromium version: 89.0.4389.90 / 89.0.4389.114

**Comment by Ahrotahn** [comment]
In previous versions the popups-to-tabs patch was enabled by default.  This has been changed to be opt-in, and you must now enable the option in order to restore its functionality.  

It can be enabled with the "Popups to tabs" entry in `chrome://flags`, or by launching with the `--popups-to-tabs` switch.  

---

私も翻訳者を使っています。 うまくいけば、これは理解できます！

以前のバージョンでは、popups-to-tabsパッチはデフォルトで有効にされていました。 これはオプトインに変更されており、機能を復元するにはオプションを有効にする必要があります。

これは、  `chrome://flags` の "Popups to tabs" を使用するか、 `--popups-to-tabs` スイッチを使用して起動することで有効にできます。

**Comment by jpuser-ungoogled-chromium** [comment]
Thank you for your reply.
I got the same behavior as "87.0.4280.67".
Thank you very much! ^^
