### ISSUE TITLE
Add automatic updates into ungoogled-chromium

### ISSUE THREAD

**Issue by ivan123-ru** [Eloston/ungoogled-chromium#1481]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Automatic ungoogled-chromium updates

**Describe alternatives you've considered**
installing new build manually

**Additional context**
idk what else i can say.

**Comment by braewoods** [comment]
This is mostly an OS specific issue. We kinda already have this for Linux so where is it missing for you?

**Comment by blackbeardth** [comment]
try using chocolatey on windows

**Comment by ivan123-ru** [comment]
> This is mostly an OS specific issue. We kinda already have this for Linux so where is it missing for you?

I use Windows version of ungoogled chromium.

**Comment by jonahlosh** [comment]
What are the options for Mac OS?

**Comment by vairag22** [comment]
@ivan123-ru ungoogled-chromium doesn't have automatic updates because that would require a background service to function. Many people including the core devs are against it. That being said there are work arounds. Using Chocolatey would be a crippled way to auto-update because that would require installing chocolatey first and then using PowerShell script and Task Scheduler to automate the process.

[chrlauncher](https://github.com/henrypp/chrlauncher) is the best way to do it. No installing required. After extacting edit _chrlauncher.ini_ and change `ChromiumType=dev-official` to `ChromiumType=ungoogled-chromium`. Then run _SetDefaultBrowser.bat_ as administrator and set **chrlauncher** as default browser (source:[ chrlauncher readme](https://github.com/henrypp/chrlauncher#readme)).

To open Chromium, run _chrlauncher.exe_ this will automatically check for updates and install them if available, otherwise launch the browser. Your extensions, bookmarks etc will remain as before. You can create a shortcut for _chrlauncher.exe_ on Desktop and rename it Chromium for convenience. To select a different version of Chromium, disable auto-update etc edit _chrlauncher.ini_

Linux users can use their package manager, and Mac users can use Homebrew etc @jl-strider 
More on updaters for all OS [here](https://chromium.woolyss.com/#updaters). (Linux users scroll upwards and check as per your distro).

**Comment by vairag22** [comment]
If you issue is solved then please consider closing it.

**Comment by ivan123-ru** [comment]
> @ivan123-ru ungoogled-chromium doesn't have automatic updates because that would require a background service to function. Many people including the core devs are against it. That being said there are work arounds. Using Chocolatey would be a crippled way to auto-update because that would require installing chocolatey first and then using PowerShell script and Task Scheduler to automate the process.
> 
> [chrlauncher](https://github.com/henrypp/chrlauncher) is the best way to do it. No installing required. After extacting edit _chrlauncher.ini_ and change `ChromiumType=dev-official` to `ChromiumType=ungoogled-chromium`. Then run _SetDefaultBrowser.bat_ as administrator and set **chrlauncher** as default browser (source:[ chrlauncher readme](https://github.com/henrypp/chrlauncher#readme)).
> 
> To open Chromium, run _chrlauncher.exe_ this will automatically check for updates and install them if available, otherwise launch the browser. Your extensions, bookmarks etc will remain as before. You can create a shortcut for _chrlauncher.exe_ on Desktop and rename it Chromium for convenience. To select a different version of Chromium, disable auto-update etc edit _chrlauncher.ini_
> 
> Linux users can use their package manager, and Mac users can use Homebrew etc @jl-strider 
> More on updaters for all OS [here](https://chromium.woolyss.com/#updaters). (Linux users scroll upwards and check as per your distro).

thanks!

**Comment by matteodev8** [comment]
It would be better if automatic updates are disabled by default and you can enable them only if you search for updates

**Comment by vairag22** [comment]
By default it checks for updates and only notifies the user that updates are available. To enable auto download and install the user has to edit the _chrlauncher.ini_ and change `ChromiumAutoDownload=false` to `ChromiumAutoDownload=true`.

**Comment by vairag22** [comment]
By default it checks for updates every 2 days and only notifies the user that updates are available. To enable auto download and install, user has to edit _chrlauncher.ini_  file and change `ChromiumAutoDownload=false` to `ChromiumAutoDownload=true`. Auto update check can also be disabled by changing `ChromiumCheckPeriod=2` to `ChromiumCheckPeriod=0`.

**Comment by JordanBoulan** [comment]
The problem I'm seeing with chrlauncher atm for Windows Installations is that it seems to still be using builds by macchrome which are two years outdated:

From the readme

```
# ungoogled-chromium
#	Unofficial builds without Google integration and enhanced privacy (based on Eloston project)
#	"github.com/macchrome/winchrome/releases/" (32/64 bit)
#	"github.com/Eloston/ungoogled-chromium"
#

```

**Comment by PF4Public** [comment]
>builds by macchrome

@JordanBoulan Unfortunately we cannot provide support for third-party binaries.

**Comment by Francewhoa** [comment]
## Flatpak

For those using Linux, the easiest option that I know of to get automated updates for Ungoogled-Chromium is to use Flatpak to install Ungoogle Chromium. I used this Flatpak for months now. It works really well. Very stable. And more importantly, more secure. Steps are in my comment at [ https://github.com/ungoogled-software/ungoogled-chromium/issues/1358#1358---steps](https://github.com/ungoogled-software/ungoogled-chromium/issues/1358#1358---steps) 

## Chromium Web Store

To get semi-automated updates for **extensions**, I suggest using this [Chromium Web Store](https://github.com/NeverDecaf/chromium-web-store#readme) extension. Yes, an extension which update other extensions. Chromium Web Store is available for Linux and Windows and other operating systems. Steps to install and use Chromium Web Store are in my same comment at [ https://github.com/ungoogled-software/ungoogled-chromium/issues/1358#1358---steps](https://github.com/ungoogled-software/ungoogled-chromium/issues/1358#1358---steps)

**Comment by claudiodekker** [comment]
Since this appears to be a common and recurring issue (arguably for good reason), I figured I'd try to partially address it by creating **a Chromium extension that automatically checks for new Chromium updates in-line with your preferences**.

Its functionality resembles that of NeverDecaf's "Chromium Web Store" extension: It displays a badge indicating available updates and, when interacted with, provides a concise overview of all available updates, allowing you to directly download newer build versions, jump to the release page, copy hashes and more. Essentially, it serves as the closest thing to an automated updater mechanism, without one being built-in.

You can find it here: https://github.com/claudiodekker/chromium-update-notifier
