### ISSUE TITLE
What is a C++ construction in ungoogled_flag_entries.h?

### ISSUE THREAD

**Issue by BrowserCoder** [Eloston/ungoogled-chromium#1486]
What a C++ construction is in "**ungoogled_flag_entries**.h"?:

 **{"pdf-plugin-name", "Set internal PDF plugin name",
   "Sets the internal PDF viewer plugin name. Useful for sites that probe JS API navigator.plugins.  ungoogled-chromium flag.",
   kOsDesktop, MULTI_VALUE_TYPE(kPDFPluginNameChoices)},**

Do I miss some code above it?

My VS2019 compiler is producing an error.
![flag_entries](https://user-images.githubusercontent.com/80814504/114744686-a0798980-9d56-11eb-93dc-652aa2ad2cbd.png)

**Comment by Ahrotahn** [comment]
That is part of the output from the [`add-ungoogled-flag-headers`](https://github.com/Eloston/ungoogled-chromium/blob/master/patches/extra/ungoogled-chromium/add-ungoogled-flag-headers.patch) patch.  That file in particular contains the flag entries that are added by ungoogled-chromium.  

If that file exists then you are trying to build over a directory that has already had the patches applied.  I'd reccommend starting with a fresh source directory since you'll probably encounter further errors if you attempt to apply the patches a second time.  

If you're certain you want to do a dirty build you can safely delete the file along with the files created by the other patches:
```
chrome/browser/bromite_flag_choices.h
chrome/browser/bromite_flag_entries.h
chrome/browser/ungoogled_flag_choices.h
chrome/browser/ungoogled_flag_entries.h
chrome/browser/ungoogled_platform_flag_choices.h
chrome/browser/ungoogled_platform_flag_entries.h
components/ungoogled/BUILD.gn
components/ungoogled/ungoogled_switches.cc
components/ungoogled/ungoogled_switches.h
net/url_request/trk_protocol_handler.cc
net/url_request/trk_protocol_handler.h
```
Those should be recreated when the patches are applied.

**Comment by Eloston** [comment]
Closing as resolved
