### ISSUE TITLE
Arch: Sandbox fail

### ISSUE THREAD

**Issue by triceratops1** [Eloston/ungoogled-chromium#149]
[15211:15211:1216/222531:FATAL:zygote_host_impl_linux.cc(107)] No usable sandbox! Update your kernel or see https://chromium.9oo91esource.qjz9zk/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
Abortado (`core' generado)

ungoogled-chromium_55.0.2883.75-1/

VERSION: semi-statical build

**Comment by triceratops1** [comment]
WORKAROUND  

add the chromium firejail profile
and a bashscript
firejail --profile=chromium.profile ./chrome --no-sandbox

**Comment by Eloston** [comment]
Does `--disable-setuid-sandbox` have any effect?

**Comment by triceratops1** [comment]
Linux ***** 4.4.38

**Comment by Eloston** [comment]
Wait you're running in a firejail? That'll break the sandbox, so yes you have to use --no-sandbox.

**Comment by triceratops1** [comment]
no :(

./chrome --disable-setuid-sandbox
[16137:16137:1216/223834:FATAL:zygote_host_impl_linux.cc(107)] No usable sandbox! Update your kernel or see https://chromium.9oo91esource.qjz9zk/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
Abortado (`core' generado)

**Comment by Eloston** [comment]
FYI it's slightly better to run with `chrome-wrapper` with statically-linked builds since they do some setup that's not done without.

And it's a bit redundant to run Chromium inside firejail since Chromium's sandbox uses the same technologies that firejail does.

**Comment by triceratops1** [comment]
./chrome 
[16242:16242:1216/224018:FATAL:zygote_host_impl_linux.cc(107)] No usable sandbox! Update your kernel or see https://chromium.9oo91esource.qjz9zk/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
Abortado (`core' generado)

./chrome --disable-setuid-sandbox[16230:16230:1216/224012:FATAL:zygote_host_impl_linux.cc(107)] No usable sandbox! Update your kernel or see https://chromium.9oo91esource.qjz9zk/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
Abortado (`core' generado)

**Comment by triceratops1** [comment]
sh chrome-wrapper
[16344:16344:1216/224232:FATAL:zygote_host_impl_linux.cc(107)] No usable sandbox! Update your kernel or see https://chromium.9oo91esource.qjz9zk/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
Abortado (`core' generado)

**Comment by Eloston** [comment]
Wait are you trying to run the static build outside firejail in the beginning? Or were you always using firejail?

**Comment by nopjmp** [comment]
I'm curious what `chrome://sandbox` says for you @triceratops1

**Comment by tonowoe** [comment]
Kind of offtopic from triceratops1's issue (I think), but do you all have all sandboxes enabled? `chrome://sandbox/` Gives me this:


```
Sandbox Status

SUID Sandbox	Yes
Namespace Sandbox	No
PID namespaces	Yes
Network namespaces	Yes
Seccomp-BPF sandbox	Yes
Seccomp-BPF sandbox supports TSYNC	Yes
Yama LSM enforcing	Yes
You are adequately sandboxed.
```

So it seems like I don't have the Namespace Sandbox. What should I do? Is it dangerous to have this in "No"?

**Comment by nopjmp** [comment]
@tonowoe that means you don't have user namespaces enabled I'm pretty sure. Arch doesn't have that enabled since they introduced a security hole and the other sandboxing techniques work well enough. https://bugs.archlinux.org/task/36969

**Comment by Eloston** [comment]
@tonowoe @nopjmp The namespace sandbox requires the user namespace, so that's most likely the cause.

@tonowoe Are you also running on Arch? I know Debian also disables this by default, but it's configurable at runtime.

@nopjmp Since the bug report you linked brought up the fact that the user namespace still has problems (and will for a while), do you think that Debian would be suffering from the same problem? It seems kind of strange when you consider that Ubuntu (which pretty much uses the same kernel as Debian I believe) has it enabled by default.

Technically this is kind-of off-topic, but it's fine as long as we don't have two major discussions in one thread (which neither aren't ATM).

**Comment by tonowoe** [comment]
> Are you also running on Arch? I know Debian also disables this by default, but it's configurable at runtime.

I'm running Debian. How can I configure it? Tried to Google but no luck.

**Comment by nopjmp** [comment]
@Eloston It may have problems. User namespaces allows allows users and not just root to make namespaces. This means a user could create a situation that they are "root" in the user namespace which may make it easier to exploit kernel bugs. Chromium says "You are adequately sandboxed." so you shouldn't have to worry about it. It's only needed if you are missing more recent features like seccomp-bpf.

**Comment by nopjmp** [comment]
@9Morello what system did you build the semi-static version on? It feels like an ABI compatibility problem.

**Comment by Eloston** [comment]
@tonowoe It's in the long list in the README near the bottom:
> Not necessary to install if the kernel option unprivileged_userns_clone is enabled

You can use sysctl to set the option during startup. Do `man sysctl.conf` to learn about `/etc/sysctl.conf` and `/etc/sysctl.d`.

@nopjmp Regarding user namespaces, I don't really know much about the implementation details, but I have used them for my linux containers (mainly for separation of software not security isolation). I always assumed they couldn't beat VMs, but I didn't know the extent of the problems until you brought it up.

Regarding the static build, @9Morello builds it on 14.04 LTS. But we're using `is_official_build=true` so we can stay as close to Google Chrome for Linux as possible. Does the sandbox work for Chrome for Linux on Arch? If it does, then we should investigate this issue further; otherwise it's an upstream problem.

Alternatively, there's also #44 that will add better support for Arch Linux.

**Comment by nopjmp** [comment]
@Eloston chrome's sandbox works I'm using it right now. It looks like the issue is something is blocking SBX_CHROME_API_RQ from getting set to 1 or parsing SBX_CHROME_API_RQ is not getting parsed to 1. I copied chrome's official sandbox binary to ungoogled and it's still broken.

**Comment by Eloston** [comment]
@nopjmp The `chrome-sandbox` binary only provides the SUID sandbox. It's not needed if enough of the other sandboxing features are available.

Unfortunately I don't know anything about Chromium's sandboxing implementation. Is `SBX_CHROME_API_RQ` only related to the SUID sandbox?

**Comment by nopjmp** [comment]
Our build system is naming the binary as chrome_sandbox instead of chrome-sandbox. That's why it's not finding the binary and throwing the more appropriate error of "please fix the permissions".

**Comment by nopjmp** [comment]
@tonowoe you can use the debian specific sysctl `kernel.unprivileged_userns_clone` flag to enable user namespaces as well to prevent having to use setuid binaries.

**Comment by Eloston** [comment]
@nopjmp I forgot that Debian renames `chrome_sandbox` to `chrome-sandbox` before packaging. Maybe we can create a script that can set the mode `4755` and the group to `root` like Debian does it?

But I'm wondering: is the SUID sandbox more or less secure than the user namespace sandbox? Which one does Google prefer?

> you can use the debian specific sysctl kernel.unprivileged_userns_clone flag to enable user namespaces as well to prevent having to use setuid binaries.

[Dunno if you saw this message or not](https://github.com/Eloston/ungoogled-chromium/issues/149#issuecomment-267789352). I guess yours is a little more clear than mine? *shrugs*

**Comment by nopjmp** [comment]
Oh I didn't see it. User namespaces is what Google prefers. They still use the setuid sandbox on ChromeOS, but we will probably never target that.

They both have trade offs, but it depends on what the distro maintainers want. If Google killed setuid, distros like Arch would have to enable user namespaces and/or patch it like Debian did.

I trust the Debian and Arch security team for the most part, but I can't remember a recent user namespace exploit since June 2015.

**Comment by Eloston** [comment]
> patch it like Debian did

I'm guessing it's to prevent the browser from failing due to a permission error and attempt to use the other sandboxing technologies. Not quite "patching", but I'm being pedantic.

Anyways, the way the static build is now is unfriendly to novice users. Maybe we can include a special README for static builds to inform them?

**Comment by nopjmp** [comment]
That's probably the best option until we have packages for their system.

**Comment by dm17** [comment]
Apparently firejail increases the attack surface of chromium... How about using unprivileged docker or lxc?
