### ISSUE TITLE
Pinned Tabs

### ISSUE THREAD

**Issue by DigitalNXZ** [Eloston/ungoogled-chromium#1497]
*IMPORTANT: Please ensure you have read SUPPORT.md before continuing*

Hi also I don't know if it's a Feature Request or something else..
I wondered why Pinned Tabs are closeable, I'll use shortcuts like strg + w so it could happen that I could close them very fast..

Is it somehow possible to set the tabs over flags or settings to non closeable and deactivating the webbrowsing in the pinned tab?

I'll think its more a problem of the original google chrome?
Vivaldi fixed that issue, they have non closeable pins but you can browse in those pinned tabs and after the resart its not the tab I pinned, its the last site I had opened :/?

Is the a Solution to it? or a extensions?

best regards~

**Comment by vairag22** [comment]
> Why are pinned tabs closeable?

Because otherwise you'll have to unpin them first and then close them. Most people will find one extra step pointless. Didn't found any flag to change this behaviour. Solution: Be careful or create a PR to add this 'safety' feature or convince the project maintainers to do it for you.
> Why can you browse web on pinned tabs?

Because browsers were made for browsing and browsing feature should be availbale at all times. For reading docs, playing videos there are specialized softwares.
> After it's not the same tab I pinned, it is the last site I opened...

You may have selected `Continue where I left` off in `Settings -> On Startup` that's why the last site you opened loads when you launch Chromium. But pinned tabs should be there, they do not close until the user closes them manually. If it does happen then first update to the latest version and report if issue persists.

**Comment by DigitalNXZ** [comment]
> Because otherwise you'll have to unpin them first and then close them.

Bulls* you have a right click function and you can make use of that.. like may adding a "close pinned tab" and removing the "close" on it.. you don't need to unpin it before you can close it.. there often solutions to it.

I don't know how much work it so ya..

> You may have selected Continue where I left off in Settings -> On Startup that's why the last site you opened loads when you launch Chromium. But pinned tabs should be there, they do not close until the user closes them manually. If it does happen then first update to the latest version and report if issue persists.

Wrong.. it's loading in the pinned tab as the last site I was on.. I need to be careful to not browse in the pinned tabs or it gets useless.. because it's just loads the last website I was on.. (Continue where I left is disabled) or it vanish because it was not the last window I closed..
I'll Browse with 2 Monitors. Left side playing videos and right side browsing trough the web, so if I close the Window with the pinned tab first and the without pinned tabs.. they gone.

If I pin something I want it to be as I pinned it.. like if I Pin GitHub and.. let's say odysee I want to land on github and odysee on the startup in the pinned tabs even if I changed the url before without realizing it.

> convince the project maintainers to do it for you.

Since Ungoogled Chromium is a better Chrome without Google Services (fork) I try my luck here, may it get added as a enhancement.

**Comment by PF4Public** [comment]
It is an old issue / feature request that didn't receive much attention. I dare to guess it must be the presentation of the issue affected it being even considered by anyone.

Please try phrasing your idea differently so that we can better understand your intentions.
