### ISSUE TITLE
Google translation service

### ISSUE THREAD

**Issue by reclaimer** [Eloston/ungoogled-chromium#154]
Ungoogled is blocking the "Translate to..." functionality of Chromium, since it redirects the request to one of those garbage domains. That's fair.

But could we make it optional? I don't mind relying on Google for that, but would have everything else turned off.

**Comment by Eloston** [comment]
This is not practical to implement due to how domain substitution works and several patches that disable translation-specific functionality. Not to mention other patches that disable code in other components, which are probably needed to make translation work. More than likely, you will have to give something else up to allow translation to work.

This may be feasible if this project grows and more people start contributing. But for now, closing as wontfix.
