### ISSUE TITLE
Please update windows binary ! !

### ISSUE THREAD

**Issue by ghost** [Eloston/ungoogled-chromium#1555]
**Please update windows binary because the current version 89.0.4389.114-1 is very old**

**Comment by vairag22** [comment]
This issue is same as #1519. I saw you commented there so why did you create a duplicate issue?
You can download the latest version from [here](chromium.woolyss.com), multiple variants are available. You can use [chrlauncher](https://github.com/henrypp/chrlauncher) to select variant, automate updates and configure other stuff.

One issue is enough to let devs know official binaries need to be updated. Tag eloston and tangalbert if want to, but do it there.

**Comment by alexolog** [comment]
Please update the Windows version

**Comment by jacob755** [comment]
v92 x86 thanks to @macchrome
https://github.com/macchrome/winchrome/releases

**Comment by tomasz1986** [comment]
> v92 x86 thanks to @macchrome
> [macchrome/winchrome/releases](https://github.com/macchrome/winchrome/releases)

Just to avoid confusion, the x86 link in the description is invalid, but the one under Assets leads to the correct file.

**Comment by PF4Public** [comment]
Note that macchrome releases are distributed separately from ungoogled-chromium.
