### ISSUE TITLE
connect(145, {sa_family=AF_UNIX, sun_path=@"/tmp/.X11-unix/X0"}

### ISSUE THREAD

**Issue by YaBoiMason** [Eloston/ungoogled-chromium#1572]
**Describe the bug**
Gets stuck trying to connect to an X.org socket on Wayland, strace shows getting stuck at ```connect(145, {sa_family=AF_UNIX, sun_path=@"/tmp/.X11-unix/X0"}```

**To Reproduce**
Install ungoogled-chromium on Fedora 34 with Wayland, and run it

**Expected behavior**
Program launches

**Screenshots**
![Screenshot from 2021-07-18 18-38-59](https://user-images.githubusercontent.com/25540164/126084222-7bf7ce9c-42a0-4163-b0e4-155b9beb0b67.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Fedora 34, Wayland, Gnome 40
 - ungoogled-chromium version: 91.0.4472.164

**Additional context**
Thinkpad T430

**Comment by wchen342** [comment]
Never seen this before..not an expert in Wayland. Does normal chromium launch? I suspect it is something specific to the particular combination of DE/graphics since it works fine for me on F34 with KDE Wayland.

I looked up a little around and it seems normally this kind of error only happens with X forwarding on headless servers or in containers. One reason I can think of is `selinux` is stopping uc from reading the socket. Maybe check your log with `ausearch`.

**Comment by PF4Public** [comment]
I hope your question has been answered, otherwise please let us know.
Closing this issue for now.
