### ISSUE TITLE
[help] Enable built-in translator?

### ISSUE THREAD

**Issue by TolyanDimov** [Eloston/ungoogled-chromium#1636]
Tell me how to enable the built-in page translator, like in chrome?
![](https://habrastorage.org/webt/e_/gp/gt/e_gpgtgdfan9a3sis3qr2jbmu00.png)

**Comment by qualityrice** [comment]
I don't want to sound rude, but you're asking for a Google service in a browser specifically made to remove Google services. If you want Google services like the translator, then it doesn't make sense to use a browser called Ungoogled Chromium.

**Comment by tomasz1986** [comment]
> I don't want to sound rude, but you're asking for a Google service in a browser specifically made to remove Google services. That is literally the only purpose of this project. If you want Google services like the translator, then it doesn't make sense to use a browser called Ungoogled Chromium.

The world is not black and white though. Some people want to stop using Google services and switch to alternative ones whenever possible. The translator is kind of a special case though, because there is literally no alternative to it. And, some people do need it, e.g. for their work. Using the website version is not the same, because it fails to translate some websites in comparison to the built-in one, and the website version is also blocked in some countries.

I personally wouldn't mind having a switch or something that would still allow using the translator.

**Comment by ianmatt** [comment]
you can install Google Translate extension (aapbdbdomjkkjkaonfhkkikfgjllcleb)
check ungoogled FAQ on how-to install extensions

**Comment by tomasz1986** [comment]
> you can install Google Translate extension (aapbdbdomjkkjkaonfhkkikfgjllcleb)

Tried it (now and also long ago already), but it's basically the same as using the Google Translate website. It can only translate highlighted text (by sending it to the site), but fails to translate full pages. This makes it kind of useless, unfortunately.

Let's not even mention the fact that the built-in translator can process even sites that you have logged in, which is impossible when using the website or the extension.

**Comment by evilenx** [comment]
I found an extension that translates very well as an alternative to Google Translate

https://chromewebstore.google.com/detail/lingvanex-online-text-and/kdamfjkjgaidaigdfelkpgdnbigclccc?hl=es_SV

**Comment by infinitephantasm** [comment]
for those looking for an extremely equivalent alternative, https://github.com/FilipePS/Traduzir-paginas-web is probably your best bet. has the same right click translate function (for the *entire* page, without reloading/opening a new site), selective text, and auto-translate settings, along with being able to change the translation service you use. the readme says it isn't 'officially' released, but you can just install the .crx in releases.

**Comment by oifj34f34f** [comment]
You can enable the built-in translator by following these steps:

**On Windows:**

1. Close ungoogled-chromium.
2. Open PowerShell (if ungoogled-chromium is installed in `Program Files` or another protected folder, run as administrator) and run the following script to restore invalid domains such as `translate.9oo91eapis.qjz9zk` in `chrome.dll` (only translation-related domains are patched):

```powershell
irm https://gist.githubusercontent.com/oifj34f34f/d186205dbe41522a2008945770407960/raw/90ab38df5d36b2c79e06ddc243db86b0f6a8addc/restore-google-translate.ps1 | iex
```

3. Acquire your own Google API key by following the instructions at https://www.chromium.org/developers/how-tos/api-keys/#getting-keys-for-your-chromium-derivative, or simply use one of the keys available online.
4. Press <kbd>Win</kbd>+<kbd>R</kbd>, enter:

```cmd
rundll32.exe sysdm.cpl,EditEnvironmentVariables
```

and create a `GOOGLE_API_KEY` environment variable with that key.

5. Run ungoogled-chromium with the following flags:

```
--translate-script-url=https://translate.googleapis.com/translate_a/element.js --test-type
```

To avoid typing this every time, right-click your ungoogled-chromium shortcut → Properties → append the flags to the end of the "Target" field, e.g.:

```cmd
C:\Users\Admin\AppData\Local\Chromium\Application\chrome.exe --translate-script-url=https://translate.googleapis.com/translate_a/element.js --test-type
```

**On Linux:**

TODO (should be easy to port the PowerShell script above with an AI)

---

**Disadvantages:**
- You'll need to re-run the patch script after every ungoogled-chromium update, since it overwrites `chrome.dll` with an unpatched version.
