### ISSUE TITLE
Chromium 56's issues  

### ISSUE THREAD

**Issue by triceratops1** [Eloston/ungoogled-chromium#165]
New year, new chromium, new issues.

i give you a full report about new warnings (chromium)

webcam full access (better than webrtc) https://developers.google.com/web/updates/2016/12/imagecapture
when was added: https://blog.chromium.org/2016/12/introducing-webvr-api-in-chrome-for.html

recomended: test if leaks ip, if leaks, disable it (just like webrtc), if dpesnt leak, put the warning at README (just like torify inox): put tape at webcam (laptop) or disconnect it (pc)

IOT control, [Direct access to IOT devices]
https://w3c.github.io/remote-playback/
recomended: disable it (just like webrtc)

WebVR (WebGL2)

    It also provides access to the user’s position and orientation, so that web apps can render a stereoscopic 3D scene to the headset's display

https://blog.chromium.org/2016/12/introducing-webvr-api-in-chrome-for.html

recomended way

easy way: disable webvr (forever/until the hard way is created), as US-CERT recomended qith webgl (lesser poweful)

www.us-cert.gov/current/index.html#web_users_warned_to_turn

hard way: use it via CTP (you MUST make click to enable), like Tor Browser

CTP = Click to play
thanks and best regards for this new year

**Comment by nopjmp** [comment]
WebVR is strictly a display platform. It's mainly for android and VR headsets (57 adds improvements) user's position is not based on geolocation and rather movement in a "VR" space (ex: HTC Vive). WebGL was recommended to be disabled since it leaks information through GPU "bugs" or "anomalies". This is well documented in research papers. The better approach for all of these things is to disable JavaScript since third party JavaScript cannot be trusted.

Remote Playback will most likely be disabled anyways since we don't support Chromecasts technically. For now it's a Android only feature since the Desktop backend hasn't been made yet.

Tor adds click to play through built in Firefox features since Mozilla has been helping the Tor Project with improving the security and privacy of Firefox.

**Comment by triceratops1** [comment]
@nopjmp  i use webgl at ungoogled

but with scriptsafe (deletes identifiable info)

**Comment by nopjmp** [comment]
@triceratops1 I suggest reading this paper (one of the many) https://cseweb.ucsd.edu/~hovav/dist/canvas.pdf

**Comment by Eloston** [comment]
I am closing this as wontfix. At the time of writing, Chromium 56 is not stable yet. Thus, there are no updates to Iridium, Inox, Debian, or other distributor patches yet. Once those have updated and have been included in ungoogled-chromium, then we can consider features that have not been patched appropriately.

**Comment by triceratops1** [comment]
@eloston ok


but i want alert about this issue

i've send alerts to inox and iridium too

**Comment by triceratops1** [comment]
@eloston  

scriptsafe has webvr protection

**Comment by triceratops1** [comment]
@andrandyou has it
https://github.com/andryou/scriptsafe/releases/download/v1.0.9.0_beta/ScriptSafe_v1.0.9.0_BETA.zip
