### ISSUE TITLE
Chrome.exe trying to connect to metriq.xyz

### ISSUE THREAD

**Issue by account123123123** [Eloston/ungoogled-chromium#1766]
My Malwarebytes is picking up chrome.exe (ungoogled chromium executable) trying to send outbound connects to metriq.xyz with the ip address 95.216.62.165. I have downloaded the latest version and this is a new event that seems to be correlated with the newest version. 

Version: 96.0.4664.45 
OS: Windows 10 64bit

**Comment by networkException** [comment]
Where did you get the binary from? Can you reproduce this without any extensions on a clean profile?

**Comment by account123123123** [comment]
> Where did you get the binary from? 

https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/96.0.4664.45-1 

I'll check without extensions and report back, but my suspicions are in the program since I have had the same extensions since the previous version.

**Comment by Nifury** [comment]
The binary is released via GitHub Actions, and its source code can be found here: https://github.com/Nifury/ungoogled-chromium-windows/tree/github_action

I don't think the root cause is in the program. chrome.exe connecting to metriq.xyz doesn't necessarily mean the executable is suspicious or compromised. The request may be initiated by an extension, a webpage, or even an external program.
