### ISSUE TITLE
Chromium 57: about:plugins page is being removed

### ISSUE THREAD

**Issue by triceratops1** [Eloston/ungoogled-chromium#181]
sorry if misfortune ts a bad word :D

but google removed chrome:plugins (now you CANT disable/enable your plugins)

http://www.ghacks.net/2017/01/29/google-removes-plugin-controls-from-chrome/

**Comment by Eloston** [comment]
In the future, please make your title as specific and as concise as possible.

**Comment by g4b1nagy** [comment]
Quoting Julian Pastarmov on this: "In a nutshell you can still control the state of the two plugins that are part of Chrome's bundle but do not represent essential Chrome components - PDF and Flash - both of those can be controlled through the content settings dialog that you can reach from the settings page."

See this page => https://groups.google.com/a/chromium.org/forum/#!topic/chromium-discuss/PmF9gGe9Auc for details.

**Comment by Eloston** [comment]
I skimmed through [the corresponding bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=615738) and it seems they have grouped plugin controls with the JavaScript settings and made custom plugins loadable via the command-line. They're discouraging the use of plugins now (which makes sense considering the rapid expansion of web standards in an effort to make web applications nearly as flexible as desktop ones).

Closing now, since all of the desired functionality is available in alternate forms.
