### ISSUE TITLE
AuthServerAllowlist policy is set and can not be removed

### ISSUE THREAD

**Issue by r3d00** [Eloston/ungoogled-chromium#1859]
**Issue:**

The chrome policy AuthServerAllowlist policy is set to "*", and while there might be a reason for it (allowing proxy-authentification without being on the intranet), it also sets ungoogled-chromium to "managed by your organisation", disabling settings (for example secure DNS configuration).

Deleting the policy json file in /etc/opt/chrome/policies/ does not disable the policy and reload policies in chrome://policy/ also does not reload the policies in /etc/opt/chrome/policies

**Expected behaviour:**

1.  Being able to remove this policy and get rid of "managed by your organisation" to allow setting secure DNS configuration.
2. Manually deleting the policy in /etc/opt/chrome/policies should remove the policy and the "Reload policies" button in chrome://policy should work.

**Reproduce:**

1. Install ungoogled-chromium in Fedora using [this package](https://github.com/ungoogled-software/ungoogled-chromium-fedora)
2. The policy is enabled by default (I did not find any reference that this was caused by packaging)

**Comment by PF4Public** [comment]
Could it be ungoogled-chromium-fedora issue?

**Comment by r3d00** [comment]
Found out that is a chromium issue as well. It happens upstream already. This can be closed.

**Comment by sgallagher** [comment]
FYI: https://src.fedoraproject.org/rpms/fedora-chromium-config/c/2a4303ccd7577c1878fa62b6e81019bf984734ae?branch=rawhide

The AuthServerAllowlist policy is no longer set for Fedora.

**Comment by revher** [comment]
It doesn't seem to be enough and at least on Fedora 41 you have to:
`dnf remove fedora-chromium-config-gssapi-3.0-5.fc41.noarch`
and restart chrome. Then you can verify that the AuthServerAllowlist line is suppressed in chrome://policy and that the ennoying mention "managed by your organisation" is suppressed too.

**Comment by sgallagher** [comment]
> It doesn't seem to be enough and at least on Fedora 41 you have to: `dnf remove fedora-chromium-config-gssapi-3.0-5.fc41.noarch` and restart chrome. Then you can verify that the AuthServerAllowlist line is suppressed in chrome://policy and that the ennoying mention "managed by your organisation" is suppressed too.

Yes, we don't automatically remove it from systems that already have it. But new installations don't ship with that package installed by default.

Ultimately, the bug here is that there's no mechanism for a packager to extend the behavior of AuthServerAllowlist without the browser *incorrectly* stating that the configuration is managed by an organization.

**Comment by revher** [comment]
Thanks for your reply, however I think that in future versions of Fedora this package should be proposed for removal  to the user as it was potentially not installed intentionally and there should be only one Fedora policy.

**Comment by sgallagher** [comment]
@revher Put simply: no.

The subpackage providing this is still useful, because it enables the use of Kerberos/GSSAPI support for authenticating to Fedora development services such as the Koji RPM build system. Having this package available simplifies setup for new contributors to the Fedora Project.

We moved away from shipping this package to end-users, but it's still included as part of the `fedora-packager` dependency tree. We don't want to remove it from anyone who has it installed, because they'd suddenly become unable to access development resources.
