### ISSUE TITLE
Ubuntu 16.04 .deb links for latest version are broken

### ISSUE THREAD

**Issue by pr0ggy** [Eloston/ungoogled-chromium#190]
The .deb links for Ubuntu 16.04 listed in [this comment](https://github.com/Eloston/ungoogled-chromium/issues/140#issuecomment-266326418) appear to be broken.

**Comment by Eloston** [comment]
@9Morello If you still have them, could you upload them to a fork of ungoogled-chromium-binaries and then update the site configuration files? I can regenerate the HTML pages if you aren't able to.

@pr0ggy If we aren't able to upload Ubuntu 16.04 binaries, hang tight since we're currently in the process of upgrading to version 56.

**Comment by 9Morello** [comment]
I should still have them, I'll reupload as soon as I find the correct VM I used to build it.

**Comment by pr0ggy** [comment]
No problem at all, appreciate the work you all are putting into this project!

**Comment by 9Morello** [comment]
@pr0ggy https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/ubuntu/xenial_amd64/55.0.2883.95-1

**Comment by pr0ggy** [comment]
Awesome, thanks again!
