### ISSUE TITLE
At least 51 security issues...

### ISSUE THREAD

**Issue by T-vK** [Eloston/ungoogled-chromium#192]
Are there any plans to update this project more regularely? Since the last commit, there have been at least 51 new security issues: https://chromereleases.googleblog.com/2017/01/stable-channel-update-for-desktop.html

I'd love to use this project, but it's just too dangerous if you only get security fixes every 3 months or so.

**Comment by Kendos-Kenlen** [comment]
Check the [develop branch](https://github.com/Eloston/ungoogled-chromium/tree/develop) which is updated more often. The master branch represent the last released version.

**Comment by Eloston** [comment]
> Are there any plans to update this project more regularely?

Of course I would like to update more regularly, but as @Kendos-Kenlen mentioned, there's a lot of work involved. Update the patches requires a lot of trial-and-error and reading the source code for changes.

Currently, this process is done one patch at a time, since the current update method is very simplistic (which is difficult to parallelize). However, this issue has caused me to create #193.

Closing now since the question seems to be answered.

**Comment by ffa** [comment]
there are other paths you can take until an update is available, particularly security tools. And, in general, using security tools goes a long way to preventing currently unknown exploits.
1. use firejail or a sandbox
2. use the umatrix extension
