### ISSUE TITLE
question: comparison to hexavalent

### ISSUE THREAD

**Issue by alexmo1997** [Eloston/ungoogled-chromium#1947]
I have difficulties choosing between https://github.com/Hexavalent-Browser/Hexavalent and this project, so I figured I'd ask if anyone would care to answer what the technical differences are and when you'd prefer which project?

**Comment by jstkdng** [comment]
So, graphene os' vanadium patches for desktop chromium? I guess the motivations are different. UC wants chromium without google services, vanadium wants a more secure chromium and web view but still work with google services (it seems).

Pick what you want.

**Comment by alexmo1997** [comment]
Well as I saw, hexavalent also removes some google privacy invasive stuff.
This is important to me, but I also want to have a secure browser, so I'm not sure, what to do...

**Comment by PF4Public** [comment]
> I'm not sure, what to do...

Are you asking advice from us on what to use? Do your own research and make informed decision — as easy as that :)

**Comment by alexmo1997** [comment]
> > I'm not sure, what to do...
> 
> Are you asking advice from us on what to use? Do your own research and make informed decision — as easy as that :)

I tried that, but I don't really know C++ or have insight into the chromium codebase, so I'm not sure if I can compare patches...

**Comment by PF4Public** [comment]
Consider trying both then :)

**Comment by qua3k** [comment]
Hexavalent aims to provide substantial privacy and security improvements to Chromium. We’ve invested in toolchain hardening as well as improvements to the browser sandbox to make the browser more resistant to exploitation.

There isn’t an attempt to remove Google services when various security-relevant component updates are downloaded from Google servers directly. We’re not going to compromise security for our users just so we can say our browser makes no connections to Google and you can’t really compare the two because they focus on separate problem domains.

**Comment by jstkdng** [comment]
Hey @qua3k

Whether using UC patches introduces security vulnerabilities is a whole different matter that should be addressed in another issue.

That being said, your point is correct, maybe adding what Hexavalent is not trying to do to your docs could avoid any other future misunderstandings.

But still, thanks for your input. With this answer I believe the issue should be closed now.
