### ISSUE TITLE
How "ungoogled" is "ungoogled-chromium"

### ISSUE THREAD

**Issue by esotericDisciple** [Eloston/ungoogled-chromium#205]
![chromium](https://cloud.githubusercontent.com/assets/577091/24324056/70b074fc-113c-11e7-91f0-0e36be3b9604.png)

I've been running MX-16's (Debian Jessie's) version of Chromium to install or update new extensions, but ever since it was updated to a version newer than the version shipped in the static build of ungoogled-chromium, I've been seeing this message. If "ungoogled-chromium" is truly "ungoogled," why is it attempting to send feedback about anything?

**Comment by leeoniya** [comment]
it may be the case that it "sends" it to 0.0.0.0.

it's much more work to tweak the UI than to just shunt all the google domains & comm internally.

**Comment by Eloston** [comment]
> If "ungoogled-chromium" is truly "ungoogled," why is it attempting to send feedback about anything?

Because this:

> it's much more work to tweak the UI than to just shunt all the google domains & comm internally.

With domain substitution and another patch to block the substituted domains from working, I am highly confident that even with the "Send feedback to help us fix the issue" checkbox enabled, it won't be able to send anything.

If you want to know exactly how this is done, you can read `DESIGN.md` to find out which files and scripts you need to look through, and also `developer_utilities/update_lists.py` for how some of the files are generated.

If you have further questions, you can continue asking them here. I will close the issue now.
