### ISSUE TITLE
Remove non-functioning Google Print UI

### ISSUE THREAD

**Issue by Woodzrul** [Eloston/ungoogled-chromium#224]
Came across this application today and decided to use going forward. Is there a reason as to why the Google Print menu under Settings still exists?

Settings -> Show advanced settings...

Personally I would like this to be removed.

Running on Windows 7 x64.

**Comment by Eloston** [comment]
It's still there because it takes extra patching to remove UI elements. The UI is generally decoupled from the feature implementations, and ungoogled-chromium focuses on disabling features, so some nonfunctioning UI is left in.

If you or anyone else really wants to submit a pull request to remove it, then that's fine by me.

**Comment by Woodzrul** [comment]
@Eloston Thank you so much for the detailed response. Unfortunately I do not know how to submit a pull request and then find the piece of code that needs removing. Oh well... Thought I would mention anyway. :-)

**Comment by Shalachaska** [comment]
It seems like Google Cloud Print functionality (including the settings UI related to it) can be disabled by setting the enable_service_discovery build flag to false, but I can't test it myself as I don't have the requirements to build Chromium.

**Comment by Eloston** [comment]
@Shalachaska I'm pretty sure I tried disabling this before, but it required lots of files to be patched (because it also includes local service discovery, which is heavily integrated for some reason). I think I would also need to disable Multicast DNS support too (`enable_mdns`) since that flag can enable `enable_service_discovery` when set to true.

I can try it on the next version and see what happens.

**Comment by Shalachaska** [comment]
Another way would be to just delete lines 782 to 810 in /src/chrome/browser/resources/options/browser_options.html

**Comment by Eloston** [comment]
@Shalachaska Adding patches that don't change any internal features is more of a burden than it's worth right now. Disabling `enable_service_discovery` would also disable other features that aren't very useful, which is why it might be worth the effort to disable it.

**Comment by Eloston** [comment]
Status update: `enable_service_discovery=false` has been around for a little while now.

I've also changed my mind about the patch. I will accept a PR for a patch to remove the UI, but I will not guarantee that the patch will stay across future versions if it becomes a pain to update.
