### ISSUE TITLE
Extension page blocked for being insecure?

### ISSUE THREAD

**Issue by StealthyXor** [Eloston/ungoogled-chromium#225]
Downloaded the Windows x64 binary release of 'Ungoogled' and found that there was a link to install extensions.

When I click this link, it blocks the site.

http://i.imgur.com/XCZYuuX.png

I was trying to figure out whether or not it's possible to install Adblock Plus or other extensions like that.
Is it?

**Comment by Eloston** [comment]
All links from the browser's interface to Google are broken [due to domain substitution](https://github.com/Eloston/ungoogled-chromium/blob/master/FAQ.md#why-are-there-urls-with-the-qjz9zk-domain-in-them-why-use-domain-substitution). Even if you go to the Chrome Web Store page manually, you won't be able to use the interface to install extensions.

If you want to install extensions from the Chrome Web Store, you may [follow the instructions documented in the FAQ](https://github.com/Eloston/ungoogled-chromium/blob/master/FAQ.md#can-i-install-extensions-from-the-chrome-webstore). Otherwise, you can drag-and-drop `crx` files on the extensions page or load unpacked extensions after enabling the Developer mode checkbox.

Let me know if something doesn't make sense. Closing for now.
