### ISSUE TITLE
Conan.io package / Build automation with conan

### ISSUE THREAD

**Issue by a-teammate** [Eloston/ungoogled-chromium#230]
I noticed you're section about provided binaries: https://ungoogled-software.github.io/ungoogled-chromium-binaries/

https://www.conan.io/ would work in your favor as prebuilding is hard and getting the build procedure up and running is hard as well.
In the [zlib package](https://www.conan.io/source/zlib/1.2.11/lasote/stable) you can see an example of a matrix of prebuilt packages with different settings - they also offer tools for that (which do the prebuilding in the CI).

-----

I heared from this project in https://github.com/inexor-game/code/issues/371.

However I dunno in how far we could use your project, as it seems that you are using the GPL.
Is our project which is using a BSD-Style license even allowed to use this package?
Im not sure.

But if no, would you mind answering:
why add a license restriction when you're trying to free another software project? I mean you're intention is pretty good and its useful, but a lot of users can't get rid of the chrome stuff because of your license.

**Comment by Eloston** [comment]
Conan is an interesting recommendation. But do they allow long-running and resource-intensive compile jobs? It doesn't make sense to me from a financial standpoint to do so. I've checked out popular CI options and they are too restrictive to compile Chromium.

> Is our project which is using a BSD-Style license even allowed to use this package?

Based on my understanding of GPLv3, you're allowed to use ungoogled-chromium as a separate module, but any changes you make must be obtainable. I'm not exactly sure how CEF works, so I can't say for sure if you're able to meet those conditions for your use case.

> why add a license restriction when you're trying to free another software project?

ungoogled-chromium was actually public domain until 27f62c91a1de555f51c0bc5e6afb9be9b4fb546c. That was the time when I included Inox patches, which are GPLv3 licensed. I wasn't sure what other less restrictive licenses were comptabile with GPLv3, so I chose it to play it safe. If it weren't for Inox, I would probably have used BSD since I believe Iridium and Debian both use Chromium's BSD license.

**Comment by a-teammate** [comment]
Conan for itself is not a CI, they just provide some add-on tools to directly upload packages built on various CIs to their packet store.
One would probably need to use a Jenkins or maybe one could ask Travis and Appveyor to allow us an exception to the build time restriction.
Or just anyone wanting to provide packages for different compilers/settings could build them locally on their machine and upload them to conan.io. 

The main work would actually be to transform all Chromium dependencies to be built from sources as well (and do so in a repeatable way, meaning creating a conan package for each)
-- 
License:
I see your point. So ungoogled-chromium got infected itself.. :/
Well thanks for the hint, I open an issue in Inox.

(The bad thing is that CEF is a library, so its not a separate module and hence we would be GPL infected as well. We wont do that, since we're trying to stay free.. :/)

**Comment by gcarq** [comment]
Hi, I've got your attention from https://github.com/gcarq/inox-patchset/issues/77. I'm answering here instead, to keep the conversation up. I honestly don't mind under which license the inox-patches are, I would be happy with either GPLv3, BSD or public domain.

**Comment by Eloston** [comment]
@gcarq Okay, that's good to hear.

@a-teammate Does the BSD license work for you? If it does, I can change to it for the version 58 release of ungoogled-chromium.

**Comment by a-teammate** [comment]
Hurray! Yeah the BSD license is fine :) anything without copyleft is okay :)
Thanks a ton!

Now we'll only have to solve the big build mess chromium and CEF are atm..

**Comment by Eloston** [comment]
@a-teammate Okay, I'll switch it in a new commit soon.

I'm not sure if Conan.io is appropriate for this project based on what I've heard so far. But if someone wants to investigate, that's fine by me.

**Comment by gcarq** [comment]
@a-teammate, @Eloston I will also change the license to BSD soon.

**Comment by gcarq** [comment]
Switched to BSD "Simplified", see https://github.com/gcarq/inox-patchset/commit/5a5543657e90df2af0f472643f8ef5f6feb4f229

**Comment by Atavic** [comment]
I'm no lawyer, but if I read [here](https://www.conan.io/terms_conditions):

> However, please notice that by uploading contents to Conan you expressly grant Conan the right of distribution, reproduction and public communication of the contents, as established in the Intellectual Property Act (Minimum Required License) as this license is needed by Conan's platform to render its services to other users.

I see that the users grant a license to this barbarian.

**Comment by Croydon** [comment]
> I see that the user grants a license to this barbarian.

If you want that a service is hosting and distributing your stuff you need to give the service the permission to do so. That's all.

**Comment by Atavic** [comment]
Sure, but does it mean that the user gives the intellectual property to Conan?

**Comment by Eloston** [comment]
> We claim no intellectual property rights over the content you upload to the Website. Your profile and content uploaded remain yours. 

Right under the section titled "Intelectual property"

**Comment by Eloston** [comment]
I don't believe conan.io is necessary since GitLab CI can be used (explored in #37)

**Comment by Croydon** [comment]
@Eloston Conan is a package manager, not a CI platform.

GitLab CI can't replace a package manager.

**Comment by a-teammate** [comment]
I will give some more detailed explanation:

## What is conan?
Conan is a tool comparable i.e. to CMake. (but on a different layer; you can use CMake with Conan, but you don't have to)
It gives you a way, to deterministically **define how to build a project.**

I.e. on windows? `cmake ..` afterwards `make` afterwards `make install`
           Linux? `./configure` afterwards `make` afterwards `make install`.
Seems simple so far, no tool needed isn't it?
probably wrong as soon as you are stepping away from the very basics.
Soon some people need `./configure shared-build=false` on some linux derivades just because something is missing.
Still. Devs using conan will just execute `conan build` and in the conan-recipe, everything is done.

*Sure, you could use another tool for that, i.e. a batch script on windows and a bash script on linux. but read on before: this is not even the interesting part*

### Problem:
Imagine you have a depdency which depends on zlib, i.e. libreSSL. And you also need zlib yourself in the project.
Now the problem is: if you build libreSSL with zlib 1.4 and you absolutely forced to use zlib 1.4 in your project as well. Otherwise it wont link.

### Other problem:
Remember the people on that unix derivade which needed to build everything with shared=false? Well, better make sure you add the right zlib-files for them in your build system!
This can become quite messy pretty quickly if you operate on more than just a single OS.

## How does conan help?
You can add as dependency the libreSSL and zlib. It will build them prior to building your project (and with the defined build procedure for each OS). You can also override the zlib version libreSSL depends on, if you want a newer one in your project. Afterwards you can add to your CMake-buildfiles to use "the conan libs". Or in your Makefiles? Easy!
The user on the unix derivade without shared libs? Hey you didn't even notice that the zlib package is building differently for those people, someone else made that package. And in your project? Everything just works.

### Another problem: Rebuilding everything sucks
Hey you do not want everyone to rebuild all dependencies everytime they want to build your shit do you?
So what to do?
Just one compiler in a specific version and always in debug? then you won't need conan. just upload the binaries somewhere in a big package.
Visual Studio 2015 Debug and Release? Already 2 prebuilts for each dependency.
Visual Studio 2017 as well? -> 4 prebuilts. And remember: when you update them: make sure to compile them with the very same settings. If something didn't work for building them: better remember that for the next time!!!!

#### Conan way
Before prebuilding the dependencies for the user, it checks, whether the package already has prebuilt packages uploaded for it, which are compatible. It downloads just them and does not try to build them on the devs pc.

Well, srsly. I didn't even get started yet, with this textwall.. There is a lot more you can do with it. It is helping a LOT. If you need to deal with dependencies on more than one system with more than one compiler? You actually better use conan (or a similar package manager, there just isn't any :P)

chrome has tons of dependencies and if you want it easy to build them on different OS, better use conan.
How to do that?
- [ ] Find out for which dependencies there is a conan package
- [ ] Use conan to get those dependencies into your project
- [ ] Make a conan package for each of those dependencies which are missing
- [ ] Profit. Srsly, I swear. Ive been through all of these problems I mentioned above and we had way less depencies than you have.

**Comment by Eloston** [comment]
@Croydon @a-teammate As I understand, the main problems that Conan solves are the large time and space requirements needed to build Chromium. These requirements become problematic when a contributor wants to build Chromium but lacks the physical resources to do so. GitLab CI solves this problem, because someone else's hardware takes care of that for us (see footnote).

Replacing bundled third-party libaries in Chromium with Conan packages is not practical, since there would be some work involved to join Chromium's build system (involving GN, Ninja, specific compilers and flags) with Conan's system. Google also makes its own changes to some of these libraries, which may not be available in Conan. This may mean that only a few third party libraries can by substituted by Conan packages. In addition, the impracticality is compounded by Chromium's rapid development.

Also, there are possible concerns of trust by involving another third party that provides binaries to build Chromium. This is quite similar to normal Chromium using binaries in the source tree.

Another problem that sounds related and solvable by Conan is the use of libraries provided by a Linux distribution. However, Conan is actually a competitor to all Linux distributions, since each provides their own ecosystem of libraries.

Footnote: One could argue there are ethical concerns for using a free service to do this, but that's up to the maintainer of GitLab CI support to decide.
