### ISSUE TITLE
ungoogled-chromium_58.0.3029.110-1_macos

### ISSUE THREAD

**Issue by nixballs** [Eloston/ungoogled-chromium#238]
Hi All,

Thanks for such a great project. I have been following it closely and finally found some time to complete macos build.

Eloston - I have forked the latest tag/branch here: [ungoogled-chromium_58.0.3029.110-1_macos](//github.com/nixballs/ungoogled-chromium/releases)

Feel free to add the build to the macos releases on the [downloads](//ungoogled-software.github.io/ungoogled-chromium-binaries/) page.

**Comment by Eloston** [comment]
Nice. Is there anything in the instructions or code that needs to be changed?

**Comment by nixballs** [comment]
I have updated the macos [build instructions](//github.com/nixballs/ungoogled-chromium/blob/master/BUILDING.md).

Re code, few warnings upon build, but it completes fine.

Maybe allow [Chrome plugins](//github.com/Eloston/ungoogled-chromium/blob/master/resources/configs/macos/gn_flags).

**Comment by Eloston** [comment]
That's good to hear, but I have a few questions:

1. Why do you need to check the build requirements in a separate directory? Why do you set the config type environment variable twice?
2. Why did you disable source cleaning?
3. Should I update the build dependencies to Xcode 8 and macOS 10.12 (as it says on the downloads page)? Your build instructions still say Xcode 7, and so do Google's build instructions for this version.
4. Why enable Chrome plugins for Clang?

**Comment by tectiv3** [comment]
Current instructions work just fine, no need to alter them.
there is a new warning though: 
```
warning: unknown warning option '-Wno-unused-lambda-capture'; did you mean '-Wno-unused-parameter'? [-Wunknown-warning-option]
```
On 10.11.6 and Xcode 8.2.1

**Comment by nixballs** [comment]
Eloston,

Originally, following tectiv3's build instructions resulted in some directories not found, however I just re-run the same commands and it worked OK - weird.

Re source cleaning, I believe it is not necessary if using `prepare_sources.py`
Dependencies, no, don't think so, it should work with Xcode 7 as well - I have 8.3.3 - simply added the info more as fyi.

Oh Chrome plugins 'for' Clang - I thought it is to enable installation of chrome extensions from the store. Currently I use [Chrome-Extension-Downloader](//chrome-extension-downloader.com/) and install via drag and drop. Being able to install extensions from the store would be beneficial.

tectiv3 is right, current instructions worked fine on the second run, so all good.

The warning is as per tectiv3's post above - however it does not seem to affect the build / unless I'm missing something.

**Comment by Eloston** [comment]
> there is a new warning though:

As long as it doesn't cause the build to fail, then it's fine. Google likes to use unstable LLVM versions to build Chromium since they include newer warning flags and other bleeding-edge features. The Debian build uses Clang 3.8, and there are quite a few warnings per target (so there's lots of console spam).

> Originally, following tectiv3's build instructions resulted in some directories not found, however I just re-run the same commands and it worked OK - weird.

I assume you mean the official build instructions?

> Re source cleaning, I believe it is not necessary if using prepare_sources.py

You had a flag earlier that effectively disabled source cleaning, but now it's gone. Nevermind.

> Oh Chrome plugins 'for' Clang - I thought it is to enable installation of chrome extensions from the store. 

No. That flag enables the use of Google's custom Clang plugins to run some additional checks during compilation ([see here for more details](https://chromium.googlesource.com/chromium/src/+/master/docs/clang.md#Using-plugins)). I don't believe the default plugins affect the build output in any significant way.

> Currently I use Chrome-Extension-Downloader and install via drag and drop. Being able to install extensions from the store would be beneficial.

Theoretically, if the extensions include an update check URL, manually checking updates via the Developer mode button should be able to download and install updates. I don't know if this works or not.

BTW, I've just updated the build instructions and extra_deps.ini.

**Comment by pjv** [comment]
Unfortunately, I have been unable to use versions past 55 on Macos due to "aw snap" page crashes on a lot of different sites. I have tried deleting my profile and even deleting the whole chromium config folder from `~Library/Application Support` and still get crashes.

I downloaded a vanilla chromium snapshot of version 58.0.3029.110 (same as latest mac ungoogled chromium build) and it does not crash on those pages.

My mac is a 2015 retina 5K iMac with 32 GB, running macOS 10.12.5.

Three random example pages that crash for me on v 58, but not on v 55: 

http://sass2stylus.com/
https://themeforest.net/item/savoy-minimalist-ajax-woocommerce-theme/12537825/comments
http://blog.janjonas.net/2011-04-22/configure-nullmailer-smtp-authentication

Anyone else on macOS have problems with those URLs?

@nixballs ?

**Comment by nixballs** [comment]
@pjv  - that's strange, all those websites work perfectly fine on my MBPr.
I would suggest downloading [EasyFind](http://www.devontechnologies.com/products/freeware.html), search for "Chromium" as per screenshot below (All Volumes), Delete everything, install the latest available version and try again.


![image](https://user-images.githubusercontent.com/7742499/27505981-afac5020-58f1-11e7-828c-ddb416957351.png)

![ungoogled](https://user-images.githubusercontent.com/7742499/27506009-8440512e-58f2-11e7-8a44-d24e15590788.gif)

**Comment by pjv** [comment]
Hey @nixballs, thanks for the suggestion and the confirmation that it must be something in my setup. Unfortunately, i can't nuke everything that has 'chromium' on my disk, as there are a lot of things with that string in it that are not relevant (e.g. something in my dev projects folder has a node module called `chromium-pickle.js` and other things like that). 

But i'll go through the list of stuff and get rid of whatever seems like it might potentially be contributing and then try again with a clean install and an empty config file and see what happens.

**Comment by pjv** [comment]
Alas - after cleaning everything possible. Fresh install of v. 58. Blank config.

![uc](https://user-images.githubusercontent.com/327716/27508161-1be4f398-58a5-11e7-9b1e-9f2e54e724cd.gif)

I tried upgrading my MBPr to v. 58 and it also crashes on the same URL as in the gif above. On a hunch I thought it might have to do with the resolution setting for the retina display, but I tried various resolutions on the MBP and it had no effect. Tried turning off hardware acceleration in chromium advanced settings. Also tried logging in as a different user on the MBP with the same result as well.

Downgrading to v. 55 on each machine "cures" the crashes.

I wish there was some way to debug this. It doesn't spit anything to the system log when it crashes and the stack trace is useless.

**Comment by Eloston** [comment]
ungoogled-chromium builds in release mode by default. One can get a debug build by modifying the GN flags as such:

* Remove `is_debug = false` (or set it to `true`)
* Set `symbol_level` to `-1`, `1`, or `2`. `2` forces the most symbols. See `build/config/compiler/compiler.gni` for an explanation of the settings.

Note that these options will cause the compilation to run longer and take more space.

**Comment by pjv** [comment]
I built ungoogled chromium from source hoping that maybe it would just magically fix itself if compiled in my env, but that didn't work either.

Then I stumbled onto #233, uninstalled PPAPI and viola! No more aw snap. Feel kind of dumb for not thinking of flash as a potential culprit.

**Comment by Eloston** [comment]
Huh, I had forgotten about that issue.

Anyways, glad to see a workaround was found.
