### ISSUE TITLE
new options for buildscript   

### ISSUE THREAD

**Issue by triceratops1** [Eloston/ungoogled-chromium#24]
-r  stores the terminal prints at a logfile, called log(n).txt, (n) is a number, example, log1.txt, log2.txt .....

a strategy would use the | tee option, that would be useful for debug purposes     

-n builds a simple source package instead of compile the sofwtare,  generating only the  .dsc, .orig.tar.xz and .debian.tar.xz

**Comment by Eloston** [comment]
The logging idea is not bad. I'll implement it in some form.

Your `-n` option is somewhat similar to what I was planning on doing. Instead of generating a `.dsc`, `.orig.tar.xz`, and `.debian.tar.xz`, it would output the source code to a directory and also generate a debian directory to put in there. I don't see the point of generating a `.dsc`, `.orig.tar.xz`, or .`.debian.tar.xz` if they're going to be unpacked on the same system for building. What do you need these files for?

**Comment by triceratops1** [comment]
yes,   the purpose  of -n is  

make very easy use online compiling services "instead of compile locally / vps"


and  make easy upload them to an apt repo

**Comment by Eloston** [comment]
Alright. Will do.

**Comment by Eloston** [comment]
Closing this as wontfix since `buildlib` will be deprecated, and this enhancement does not make sense in the new system (#125).
