### ISSUE TITLE
Push to Debian

### ISSUE THREAD

**Issue by micah** [Eloston/ungoogled-chromium#27]
Hi!

I'm happy I found your project! The only thing holding me back from using it myself is that there aren't packages available for other Debian releases.

Is there any chance you might be interested in getting your changes integrated into the debian chromium package? These sorts of privacy enhancements are things that I think would be very useful for the broader debian audience. If you don't think that will work, an alternative would be to get ungoogled-chromium into debian as its own package. You are already making packages, it seems like maybe just a little bit more effort to try and get them into debian itself.

I think that if this were made available to Debian, it would reach a lot more people!

**Comment by Eloston** [comment]
Thanks for your interest in my project!

Although I do build my own Debian packages, I actually don't know many details on what I would need to do as a maintainer, such as the proper procedures of submitting packages and source code, and providing support for the package. Plus, I'm pretty sure some of the things I do to the source code (namely the domain patcher and source cleaner, which are mostly automated and therefore somewhat unpredictable in what they can break) are things that would take more time to do if I were to follow Debian's rules.

Also, I'm currently in the process of creating a flexible and extensible cross-platform Python build system that will take care of downloading, patching, configuring, and building Chromium for a certain platform or distribution. The `debian` directory used for building will become pretty simple; it will just run the build command and bundle up the build artifacts into `.deb` packages. There are several reasons why I'm switching to this system, but one major reason is that it makes supporting other platforms such as Mac OSX and Windows easier. Perhaps Debian and other distributions would be fine with my unconventional method of building packages for their distributions, but I don't think I have the time right now to learn what I need to know to become a package maintainer.

I could just propose to include a subset of the patches that aren't too dependent on a specific build configuration, but I'm fairly certain that my patches don't meet the standards of "good" patches. Also, I haven't been able to consistently keep up-to-date with the latest stable of Chromium, so Debian may not be happy with that.

In essence, I don't have a lot of time, and I use ways of saving time that others may not like very much.

**Comment by macandchief** [comment]
Just a remark: For less experienced users it is a bit unclear how to install this browser. I was struggling with the process (even if I studied the github description). I found some install instructions in a forum of the debian based distro called bunsenlabs helpful.
For Stretch, amd64:
`mkdir ~/src && cd ~/src && wget https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/58.0.3029.110-1/chromium_58.0.3029.110-1_amd64.deb && wget https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/58.0.3029.110-1/chromium-widevine_58.0.3029.110-1_amd64.deb && wget https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/58.0.3029.110-1/chromium-shell_58.0.3029.110-1_amd64.deb && wget https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/58.0.3029.110-1/chromium-l10n_58.0.3029.110-1_all.deb && wget https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/58.0.3029.110-1/chromium-driver_58.0.3029.110-1_amd64.deb && sudo gdebi chromium_58.0.3029.110-1_amd64.deb && sudo gdebi chromium-driver_58.0.3029.110-1_amd64.deb && sudo gdebi chromium-widevine_58.0.3029.110-1_amd64.deb && sudo gdebi chromium-l10n_58.0.3029.110-1_all.deb && sudo gdebi chromium-shell_58.0.3029.110-1_amd64.deb`

This requires wget and gdebi and it downloads the packages in a folder called src and installs them. Those packages are older than the packages in the repos, so apt upgrade tries to replace them. To avoid upgrading the following command helps:
`sudo apt-mark hold chromium chromium-driver chromium-l10n chromium-shell`

As I mentioned this is for less experienced users but it might be helpful to point out such steps in the description. Great work btw, it's striking how less resources this browser uses when all the junk has been removed.

**Comment by Eloston** [comment]
@macandchief You make a point about package versions, but hopefully 62 comes out soon enough so that doesn't continue to be an issue. In `develop`, the packages have already been renamed with a `ungoogled-` suffix due to the inconvenience of package holding.

I don't think it is necessary to have instructions for installing Debian package files here because many other software do not post instructions either. So, methods to install should be easy to find.

**Comment by macandchief** [comment]
Ok, thank you for the details, that's great with ungoogled-. I'm looking forward to give version 62 a try.

**Comment by macandchief** [comment]
v62 got released, fantastic! If there is v58 already installed, is simply running the following a proper way to update?
`mkdir ~/src && cd ~/src && wget https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/62.0.3202.94-1/ungoogled-chromium_62.0.3202.94-1_amd64.deb && wget https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/62.0.3202.94-1/ungoogled-chromium-widevine_62.0.3202.94-1_amd64.deb && wget https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/62.0.3202.94-1/ungoogled-chromium-shell_62.0.3202.94-1_amd64.deb && wget https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/62.0.3202.94-1/ungoogled-chromium-l10n_62.0.3202.94-1_all.deb && wget https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/62.0.3202.94-1/ungoogled-chromium-driver_62.0.3202.94-1_amd64.deb && wget https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/62.0.3202.94-1/ungoogled-chromium-common_62.0.3202.94-1_amd64.deb && sudo gdebi ungoogled-chromium_62.0.3202.94-1_amd64.deb && sudo gdebi ungoogled-chromium-common_62.0.3202.94-1_amd64.deb && sudo gdebi ungoogled-chromium-driver_62.0.3202.94-1_amd64.deb && sudo gdebi ungoogled-chromium-widevine_62.0.3202.94-1_amd64.deb && sudo gdebi ungoogled-chromium-l10n_62.0.3202.94-1_all.deb && sudo gdebi ungoogled-chromium-shell_62.0.3202.94-1_amd64.deb`

**Comment by Eloston** [comment]
@macandchief I think that installation method is fine. We should move this discussion elsewhere if you still have questions.

**Comment by macandchief** [comment]
@Eloston Yes, indeed, the part from my post might be more useful elsewhere as the topic clearly changed and does not suit to Push to Debian.

So this is how the update v58 -> v62 went:
First I run (although it might not be necessary as I removed these packages later):
`apt-mark unhold chromium chromium-driver chromium-l10n chromium-shell`

After that I tried the one-liner I posted, but:
`This package is uninstallable
Dependency is not satisfiable: ungoogled-chromium-common (= 62.0.3202.94-1)`

I was thinking about installing ungoogled-chromium-common first and the package ungoogled-chromium after that, but: `dpkg: error processing archive ungoogled-chromium-common_62.0.3202.94-1_amd64.deb (--install): trying to overwrite '/usr/lib/chromium/natives_blob.bin', which is also in package chromium 58.0.3029.110-1`

At this point I simply removed the installed packages (first I used this command without the chromium-shell package, but it needs to be removed. otherwise it gives an error message while installing ungoogled-chromium-shell):
`apt remove chromium chromium-shell`

And after that:
`sudo gdebi ungoogled-chromium-common_62.0.3202.94-1_amd64.deb && sudo gdebi ungoogled-chromium_62.0.3202.94-1_amd64.deb && sudo gdebi ungoogled-chromium-driver_62.0.3202.94-1_amd64.deb && sudo gdebi ungoogled-chromium-widevine_62.0.3202.94-1_amd64.deb && sudo gdebi ungoogled-chromium-l10n_62.0.3202.94-1_all.deb && sudo gdebi ungoogled-chromium-shell_62.0.3202.94-1_amd64.deb`

There is an error message if chromium-shell wasn't removed, but I mentioned it already above:
`dpkg: dependency problems prevent configuration of chromium-shell:
 ungoogled-chromium-shell (62.0.3202.94-1) breaks chromium-shell and is installed.`

If I'm not mistaken `apt-mark hold` is not necessary anymore.

Update done. The browser is working fine! Some extensions needs to be updated (re-installed too). Fantastic work, well done.

According to these steps I guess this is how an update v58 -> v62 should work as a one liner:

`mkdir ~/src && cd ~/src && wget https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/62.0.3202.94-1/ungoogled-chromium_62.0.3202.94-1_amd64.deb && wget https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/62.0.3202.94-1/ungoogled-chromium-widevine_62.0.3202.94-1_amd64.deb && wget https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/62.0.3202.94-1/ungoogled-chromium-shell_62.0.3202.94-1_amd64.deb && wget https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/62.0.3202.94-1/ungoogled-chromium-l10n_62.0.3202.94-1_all.deb && wget https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/62.0.3202.94-1/ungoogled-chromium-driver_62.0.3202.94-1_amd64.deb && wget https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/62.0.3202.94-1/ungoogled-chromium-common_62.0.3202.94-1_amd64.deb && sudo apt-mark unhold chromium chromium-driver chromium-l10n chromium-shell && sudo apt remove chromium chromium-shell && sudo gdebi ungoogled-chromium-common_62.0.3202.94-1_amd64.deb && sudo gdebi ungoogled-chromium_62.0.3202.94-1_amd64.deb && sudo gdebi ungoogled-chromium-driver_62.0.3202.94-1_amd64.deb && sudo gdebi ungoogled-chromium-widevine_62.0.3202.94-1_amd64.deb && sudo gdebi ungoogled-chromium-l10n_62.0.3202.94-1_all.deb && sudo gdebi ungoogled-chromium-shell_62.0.3202.94-1_amd64.deb`

There will be the packages left in the (root) /src directory but after the update these can be also removed.

**Comment by Eloston** [comment]
Well it seems that [the disable signin patch was included in Debian's 63.0.3239.40-1](https://anonscm.debian.org/cgit/pkg-chromium/pkg-chromium.git/tree/debian/patches/disable/signin.patch?id=db1cfb715b0fb78514e75256d610893c3e3fc960). That's kinda neat.

**Comment by pannous** [comment]
Please add instructions of how to add ungoogled-chromium package to Debian on main Read.me

thx

**Comment by FelipeLema** [comment]
as an alternative to adding instructions, point to https://github.com/ungoogled-software/ungoogled-chromium-debian

**Comment by pannous** [comment]
Thanks.

Is there no server which can be added to sources.list for simple apt-get usage?

**Comment by Eloston** [comment]
@pannous Nope, see #37

**Comment by mckaygerhard** [comment]
seems all of you are waste effors.. eevent works in join with debian...

**Comment by mckaygerhard** [comment]
i filled a new bug on debian to suggest use ungoogled.chromiun event chromiun itselft at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939406 or https://bugs.debian.org/939406.. **so if both project work together can be a great benefit for both, so then winbuntu, mx-linux and mint the most popular distributions will use then thist browser as primary solution**

**Comment by trymeouteh** [comment]
I would like this also. It will allow me to get the latest version easier and quicker as long as it is updated as much as other browsers are in the repo.

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently — closing.
If you have any more information to add, let us know.
