### ISSUE TITLE
manpage needs clarification on the new --temp-profile option and bug tracker update

### ISSUE THREAD

**Issue by libBletchley** [Eloston/ungoogled-chromium#283]
The difference between --temp-profile and --incognito is unclear from the manpage and not even mentioned in the FaQ.  Since `--temp-profile` is apparently unique to ungoogled-chromium, it should probably be clarified.

The "bug tracker" part of the manpage mentions this: http://code.google.com/p/chromium/issues/list.  Perhaps it should also list the ungoogled-chromium bug tracker, and the kind of bugs that should go there.

I also think the Debian installation guide should warn users that the `apt` tools will confuse ungoogled-chromium with the official chromium, and attempt to "upgrade" to the official one.  It might be useful to document how to pin the version so users can avoid that.  I may submit a pull request for some of this.. just need to know first if folks are okay with it.

**Comment by Eloston** [comment]
Based on your content, I will assume the context here is the Debian packages.

> The difference between --temp-profile and --incognito is unclear from the manpage and not even mentioned in the FaQ. Since --temp-profile is apparently unique to ungoogled-chromium, it should probably be clarified.

This is partially correct. `--temp-profile` is unique to Debian's Chromium. ungoogled-chromium did not change the behavior. The implementation is in the script `/usr/bin/chromium`.

> I also think the Debian installation guide should warn users that the apt tools will confuse ungoogled-chromium with the official chromium, and attempt to "upgrade" to the official one.

The `develop` branch has all package names prefixed with `ungoogled-`. This change will be merged to `master` in the next release of ungoogled-chromium.

On a related note, I think that the `--temp-profile` and "bug tracker" documentation issues should be reported to Debian. Additionally, it might help to distinguish flags or environment variables introduced by Debian from existing ones.

However, I will change the "bug tracker" section for ungoogled-chromium's packages to link to GitHub Issues.

Closing since I don't believe there is anything else for ungoogled-chromium to do. I will make the bug tracker tweak right now (which will show up on `develop`)

**Comment by libBletchley** [comment]
I've submitted the bugtracker manpage bug here:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=880965

I'll also submit one to debian for the --temp-profile option as well.

> The develop branch has all package names prefixed with ungoogled-. This change will be merged to master in the next release of ungoogled-chromium.

When that happens, should users uninstall the ungoogled-chromium that's named as "chromium" and install package that uses the new name?

**Comment by Eloston** [comment]
No need to purge the package. The configuration files can be reused by ungoogled-chromium, so you only need to delete.

**Comment by libBletchley** [comment]
I was waiting for the next release, and ignoring the apt nags to "upgrade", then on Nov.14 Ungoogled-Chromium was silently replaced with the google version.  According to the logs, `unattended-upgrade` did that, which I think suggests the version of that day was security-critical.

Anyone following this thread will want to pin the version of their ungoogled-chromium.

**Comment by libBletchley** [comment]
Ungoogled-chromium now sends a nag upon every launch that the profile is for a more recent version.  It also lost access to the password store, so no passwords are prefilled, nor can it store new passwords.

Anyone know how to fix these issues, apart from obliterating the profile?

**Comment by Eloston** [comment]
> Anyone know how to fix these issues, apart from obliterating the profile?

I think the profile should be fine when ungoogled-chromium updates to 62.
