### ISSUE TITLE
OS detection via JavaScript

### ISSUE THREAD

**Issue by ghost** [Eloston/ungoogled-chromium#31]
May be outside issue...
Is it possible to change the "identifier" in source code for OS detecting (http://browserspy.dk/os.php), but not affecting JS functionality and building?
The meaning of the not to be the white crow and easy prey for tracking, if I use a rare OS/distro.

**Comment by Eloston** [comment]
Huh, I didn't realize there were other ways to detect the platform. But do we need to do this in the Chromium source code? If it can be done via an extension, it would benefit more than those who use ungoogled-chromium.

**Comment by Atavic** [comment]
[WebKit Trac](https://trac.webkit.org/wiki/Fingerprinting) has a good list about Fingerprinting.

Also see: https://github.com/Eloston/ungoogled-chromium/issues/13 https://github.com/Eloston/ungoogled-chromium/issues/55

**Comment by Eloston** [comment]
From what I understand, [ScriptSafe](https://github.com/andryou/scriptsafe) can deal with this. I don't see any need for ungoogled-chromium to do anything here.

**Comment by ciampolo** [comment]
I had to write this already for another repo but PLEASE DO NOT SPOOF YOUR OS, the only thing **it does is make you so easily identifable it is astonishing**. It is more than foolish to assume Github, Google etc. are not abusing this since at least a decade.

TCP/IP fingerprinting works without Javascript/HTML/CSS; just by pinging a server that server can tell your OS and even rough version like WinNT X, Linux Kernel xx etc. That's the reason mozilla decided to keep the original OS even if privacy.resistFingerprinting is enabled.

The only way to be "safe" (without external providers) is to setup a Windows VPN and pipe everything through it. Which (in my opinion) would defeat the purpose of "security" since your traffic passes through a propiertary code that, worse, isn't even remotely UNIX. 

Best bet is to use a VPN service with many users that is hosted in a trustworthy EU country (as in DACH or BENELUX). Everything else should be considered unsafe, while anything from the Five Eyes countries should be considered malicious. If you care any percent about privacy and then still pipe your traffic through any of UK/US/CA/AU/NZ you should really just stop using the internet and open your private home to the general public, including that Nigerian prince.
