### ISSUE TITLE
Mac OS: Fixup UI

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#35]
Reported by @9Morello:

> 1. On the OS X Chromium's top menu, there is still an "Sign in" option. Clicking it does nothing, so I supposed it could be harmlessly removed.
> 2. Remove the connection it tries to make when adding another profile to ungoogled-chromium. Not sure if this was present on Linux, but if I click on "Add person..." in the Settings page, then on "Sign in", there is a connection attempt to a changed domain (which is blocked by ungoogled-chromium).
> 3. On the OS X Chromium's top menu, If I click on "Help", and then on "Chromium Help", it attempts to connect to a remote support page (and then its blocked by ungoogled-chromium).

For the third problem, should the link be fixed or removed altogether?

**Comment by 9Morello** [comment]
For the third problem, I think its safe to remove it, along with the "Report an issue..." option (that one is grayed out and nothing happens when the user clicks on it).

For the second, maybe we should check first if Chromium somehow integrates with the OS X's users by any chance. But I suppose removing the "Sign in" link should be ok.

**Comment by Eloston** [comment]
I almost forgot about this issue.

I don't have a Mac to play around with, so it'll be hard for me to figure out how the UI corresponds with source code. If someone has some knowledge that can enlighten us, or wants to make a pull request, that will help a lot.

**Comment by PF4Public** [comment]
A lot has changed since the time of filling of this issue. Is it still of interest?

**Comment by kramred** [comment]
I'll look into it later today or over the weekend.

**Comment by kramred** [comment]
> 1. On the OS X Chromium's top menu, there is still an "Sign in" option. Clicking it does nothing, so I supposed it could be harmlessly removed.

Cannot reproduce. Might be gone by now.

> 2. Remove the connection it tries to make when adding another profile to ungoogled-chromium. Not sure if this was present on Linux, but if I click on "Add person..." in the Settings page, then on "Sign in", there is a connection attempt to a changed domain (which is blocked by ungoogled-chromium).

Cannot reproduce. Seems to be not longer in the Chromium code or is dealt with by the current patches.

> 3. On the OS X Chromium's top menu, If I click on "Help", and then on "Chromium Help", it attempts to connect to a remote support page (and then its blocked by ungoogled-chromium).

That menu item is still there and has the domain substitution applied so that the link points to: `https://support.9oo91e.qjz9zk/chrome/?p=help&ctx=menu` 

The origin of that menu item is probably here: [`chrome/common/url_constants.cc`](https://source.chromium.org/chromium/chromium/src/+/master:chrome/common/url_constants.cc;l=61)

I don't mind it like this but one could change it to point to the GitHub repo or something similar - opinions?
