### ISSUE TITLE
Large memory leak in main process over several days

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#362]
There seems to be a memory leak in the Debian 9 amd64 binaries I've built.

Current reports: On my machine, I have seen the memory footprint of the main process grow from about 170 MB to over 400 MB in the span of 3 days (with [my binaries here](https://github.com/Eloston/ungoogled-chromium-binaries/releases/tag/65.0.3325.162-1)). @ik9999 has reported growth of *over 2 GB* on the main process within 3-5 days for my 64.0.3282.186-1 Debian 9 amd64 binaries on Debian testing (buster).

Some potential avenues to investigate:
* Sift through the patches to see if anything there could be causing any problems.
* See if any of ungoogled-chromium's deriving projects, such as Inox or Debian's Chromium, have memory leaks. This can narrow down the potentially problematic patches.
* See if `linux_portable` (as of version 65) is affected by memory leaks to this degree.
* Use [LeakSanitizer](https://www.chromium.org/developers/testing/leaksanitizer) based on `linux_portable` (as of version 65).

**Comment by ik9999** [comment]
Are you sure that its not a [chromium](https://github.com/chromium/chromium) issue? I can't check it right now.

**Comment by Eloston** [comment]
@ik9999 It's hard to say. Given that this is a pretty large leak and that you've been affected by it in previous versions, I think it's more likely that it's due to some change in ungoogled-chromium.

**Comment by Eloston** [comment]
@ik9999 67 is out. Are you still experiencing major memory leaks?

**Comment by ik9999** [comment]
@Eloston I feel like memory usage grows slower now, it was 721mb yesterday, now its 889mb.

**Comment by tonowoe** [comment]
I'm using those pre-built binaries as well with Debian 9 amd64, and I've noticed the same. If I don't reboot my browser or computer for couple of days, I see that the browser is being heavy on RAM usage. It haven't bothered be that much because it's really fast to just restart the browser so the RAM usage will go back to normal again. I have had this problem for many versions now, and it's about the same in the latest 67 version. But it seems that RAM usage will not grow as fast as in earlier versions.

If I remember correct, this happened in the normal chromium too, not just in ungoogled, not sure though.

**Comment by csagan5** [comment]
I have had at least one [similar report](https://github.com/bromite/bromite/issues/111); my suggestion is to look upstream for possible Chromium issues. Difficult to say whether it's the same root cause or not, since Bromite builds for Android and there are a lot of differences also in the memory model.

**Comment by csagan5** [comment]
Another suggestion: what do you see in the task manager (Shift + Esc)? A leak would not associate memory to any specific tab.

**Comment by tonowoe** [comment]
This is not the issue anymore after upgrading to 71.x.

**Comment by Eloston** [comment]
Good to hear. @ik9999 Does your memory usage still grow?

**Comment by ik9999** [comment]
@Eloston Installed v71 using [your deb binaries[](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/debian/stretch_amd64/71.0.3578.98-1). Running it for like 24 hours. Memory grew from 300mb to 800mb. Maybe it happens because i have many extensions/long-running tabs. Will wait for few more days, maybe it will stop growing.

**Comment by intika** [comment]
Nice growth you should invest some finance in there hahahaha 
The line is days or hours ? 
was the browser just open or used ?

**Comment by ik9999** [comment]
@intika 
>The line is days or hours ?
Days.
>was the browser just open or used ?
Opened and used.

**Comment by intika** [comment]
hard to debug when the browser is used but i think this affect upstream as well

**Comment by ik9999** [comment]
I dont feel like usage makes it grow more. I've used it a lot in last 2 days, but memory almost stopped growing.

**Comment by Eloston** [comment]
If memory usage is not concerning so far, then I'll close this issue. Until (or unless) ungoogled-chromium formalizes development with better practices (i.e. running code testing and analysis tools that Google uses over the code), I don't see any point in digging deeper into memory usage; any attempt to do so could end up futile with updates and new features.

**Comment by donnaken15** [comment]
I got this issue when updating to the latest version just now on Windows. I downloaded a few different versions and for some reason between version >115 and 117, this actually starts to happen to me. Main process memory went from about a gigabyte to 9 gigabytes used, taking megabytes of memory constantly. On earlier versions, it stays around 600 MB on my session.
This is without extensions (and since the freaking thing deleted all of them).
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/20864393/cc7f3cc7-62f4-4763-a14e-91f896273cbc)

**Comment by PF4Public** [comment]
> On earlier versions, it stays around 600 MB on my session.

Have you tried empty profile?

**Comment by donnaken15** [comment]
> I got this issue when updating to the latest version just now on Windows. I downloaded a few different versions and for some reason between version >115 and 117, this actually starts to happen to me. Main process memory went from about a gigabyte to 9 gigabytes used, taking megabytes of memory constantly. On earlier versions, it stays around 600 MB on my session. This is without extensions (and since the freaking thing deleted all of them). ![image](https://user-images.githubusercontent.com/20864393/271170246-cc7f3cc7-62f4-4763-a14e-91f896273cbc.png)

usage over 10 minutes on my profile, while having just a video open (hundreds of unread windows/tabs though)
https://streamable.com/i3ahyy
