### ISSUE TITLE
Remove build dependency on quilt

### ISSUE THREAD

**Issue by squalus** [Eloston/ungoogled-chromium#366]
Quilt is useful for patch maintainers, but not necessary for normal users. It can be replaced by a Python3 script that 1) reads the lines in the series file and 2) applies the patches using either `git apply` or `patch`. The same script can be used for all platforms.

This will be one less dependency for users to install. For Windows this is particularly beneficial beause it removes the need to install MSYS2. If we decide to use `patch`, the gnuwin32 binary can be downloaded automatically.

**Comment by Eloston** [comment]
Alternatively, we could use [`python-quilt`](https://github.com/bjoernricks/python-quilt). But for non-developers, this adds a lot of complexity. It's simpler to just invoke `patch` directly.

> If we decide to use patch, the gnuwin32 binary can be downloaded automatically.

In the previous Windows instructions (before I attempted to update Windows support recently), I manually download MSYS2's `patch` binary from SourceForge (with the required DLL to make it run). I can't recall exactly why, but there may have been some issues with GNUWin32's old version of GNU `patch`. Since we can now automatically download and extract (almost) everything, we could just automate that procedure.

**Comment by Eloston** [comment]
For now, I think it's better to play it safe by invoking `patch` directly and using MSYS2's `patch`. I think it'll be fine to include the patching code this as a new module `patching.py` with CLI command `patsrc` (for "patch source", unless you can think of a better name).

**Comment by squalus** [comment]
What about using `git apply`? That works fine for me in testing on Windows. And we can download updated official binaries from https://git-scm.com in the extra deps.

Would the new buildkit command run between `subdom` and `genpkg`? And I guess we no longer need `genpkg` to copy patches or patching scripts to the tree.

**Comment by squalus** [comment]
Also it appears `python-quilt` just invokes `patch` :)

https://github.com/bjoernricks/python-quilt/blob/3dd50bc77/quilt/patch.py#L26

**Comment by squalus** [comment]
A few more things
- The Windows git binaries actually include patch.exe so it's possible we could use this
- If `patsrc` is run after `getsrc` it's no longer necessary to perform subdomain replacement on the patches, so that code could be deleted in the `subdom` step. Is this what you have in mind?

**Comment by Eloston** [comment]
`git apply` requires Git to be downloaded. If you're not a developer, this is a large and non-portable dependency (IIRC it's a subset of MSYS). On the other hand, my GNU `patch` approach only requires two small downloads; of which only a single `exe` and `dll` are required from it.

If one of your goals is to make building easier for non-developers, then I don't think it makes sense to download Git.

> Also it appears python-quilt just invokes patch :)

Yep, and it's stated in its README that `patch` and `diff` are required for applying and creating patches, respectively.

The only reason I considered including python-quilt is for its usefulness in development, while also being lightweight (compared to MSYS2). If we're certain that developers won't be using python-quilt over MSYS 2 or WSL, then python-quilt is just more bloat and complexity compared to invoking `patch` directly.

> Would the new buildkit command run between subdom and genpkg? And I guess we no longer need genpkg to copy patches or patching scripts to the tree.

Actually, thinking about the python-quilt problem made me realize that there's no good way to let `buildkit` know where `patch` is located, since it's being downloaded to a configuration-specific location. This *could* be solved by downloading it to a dedicated location like `buildspace/utilities` and adding a new config file `utiliites.ini` to specify shell commands to implement specific features, but I don't want to make `buildkit` configuration-specific or add complex logic to make it "smart"; I would rather choose simplicity and transparency over convenience when it's reasonable.

Instead, I think it's better to go with the alternative to `patsrc` I had in mind, which is to add a shared packaging Python script to apply a patch series using GNU patch or `git apply` (i.e. a script like `apply_patch_series.py` in `resources/packaging/shared/`). This is because the `windows` base bundle and packaging types are already semantically linked to one another, so it's valid for `build.bat` to use `apply_patch_series.py` and the predetermined location of GNU patch. `buildkit` and packaging types don't have this sort of relationship.

From a more abstract perspective, applying patches could arguably be classified as either source file processing, or as part of building in the packaging process. (Also, this ambiguity is what made it difficult for me to choose between `patsrc` or `apply_patch_series.py` in my previous comment.)

**Comment by Eloston** [comment]
Also, I forgot that applying patches was part of packaging, not buildkit as per my own design document...

> If patsrc is run after getsrc it's no longer necessary to perform subdomain replacement on the patches, so that code could be deleted in the subdom step. Is this what you have in mind?

If applying patches was part of buildkit, this couldn't work because Debian applies patches as part of its build process. Also, domain substitution over the source tree and user bundle allows users to build Chromium in an environment without Python 3 (but this isn't really a common use case, as I now realize).

**Comment by Eloston** [comment]
(I just added a new section to DESIGN.md about [buildkit's design philosophy](https://github.com/Eloston/ungoogled-chromium/blob/develop/DESIGN.md#buildkit-design-philosophy), which generalizes and distills the underlying thoughts of my earlier post.)

**Comment by squalus** [comment]
Yes, my goal here is to make the Windows build simpler for non-developers. The build will be more reliable and repeatable if there are fewer manual setup steps.

>On the other hand, my GNU patch approach only requires two small downloads; of which only a single exe and dll are required from it.

Using the Gnuwin32 binary is my first choice too since it's so small. Let's do this if the version isn't too old to work.

> git apply requires Git to be downloaded. If you're not a developer, this is a large and non-portable dependency

I was thinking about getting the `PortableGit-2.16.2-64-bit.7z.exe` binary from git-scm.org which doesn't require an install and can be extracted by 7z. So it can go through the automatic extra_deps.ini system. I haven't tested it yet though. The download is 35mb which doesn't bother me. We should do this if Gnuwin32 doesn't work.

> The only reason I considered including python-quilt is for its usefulness in development,

python-quilt would be fine because it can be bundled. I just want to get rid of the unnecessary dependencies in the non-developer build workflow. But like you mentioned, it's easier to just invoke `patch` directly

> Instead, I think it's better to go with the alternative to patsrc I had in mind, which is to add a shared packaging Python script to apply a patch series using GNU patch or git apply (i.e. a script like apply_patch_series.py in resources/packaging/shared/). This is because the windows base bundle and packaging types are already semantically linked to one another, so it's valid for build.bat to use apply_patch_series.py and the predetermined location of GNU patch. buildkit and packaging types don't have this sort of relationship.

To me it makes more sense as a buildkit source processing step, because it can be done before `subdom` and the patch substituion code can be eliminated. The patch substitution  just seems like unnecessary complexity. But of course it works fine either way, it's just a judgement call. I don't know enough about Debian packaging to speak about that issue.

> Also, domain substitution over the source tree and user bundle allows users to build Chromium in an environment without Python 3

`list_build_outputs.py` is a build-time dependency on Python3, and we'll be adding another one using the new `apply_patch_series.py` script. I have no problem with this.

Thanks for the thoughts, I will work on adding a patching script.

**Comment by Eloston** [comment]
> To me it makes more sense as a buildkit source processing step, because it can be done before subdom and the patch substituion code can be eliminated. The patch substitution just seems like unnecessary complexity.

You're right, it is very complicated. You're not the first to point out the issue. Separating buildkit with packaging scripts and avoiding Python 3 in the packaging scripts are objectives that don't make much sense, and they conflict with the design of Linux-based packaging systems (e.g. Arch Linux's PKGBUILD and Debian's dpkg system in #37 ) and the goal of keeping things simple and cross-platform.

I am brainstorming options here to amend these problems with minimal changes. I'm projecting that only the packaging scripts and build process will go through the largest changes, but the file structures and `buildkit` itself will stay mostly intact.

**Comment by Eloston** [comment]
These changes will take some time, so you may submit a PR whenever you're ready. It should be pretty straight-forward to merge your script into buildkit if we choose to do so then.

**Comment by Eloston** [comment]
83a6cbc80682a2dc1ec116c6db0d79e4df6c5bd5
