### ISSUE TITLE
"Blocked request to" infobar repeatedly shows if a tab's top-level domain ends in `qjz9zk` and internal pages are accessed via the menu

### ISSUE THREAD

**Issue by 9Morello** [Eloston/ungoogled-chromium#42]
I still don't know what triggers this, but after some action by the user, Chromium starts to try connecting to Google every time I visit the "Extensions" page.

**Platform:** OS X El Capitan
**Link that ungoogled-chromium attempts to connect to:** https://support.9oo91e.qjz9zk/chrome?p=help&ctx=settings
**What makes ungoogled-chromium start this:** I don't know. It stops by restarting it.

Not sure if this just affects the OS X version.

**Comment by 9Morello** [comment]
Discovered how to reproduce it:
1) Open ungoogled-chromium
2) Go to the "About Chromium" page
3) Click on "Get help with using Chromium". It should open a new tab ant attempt to connect to the link pointed in the first post. Close the warning.
4) From now on, as long as you don't close the tab opened before, it should attempt to connect to that link every time you visit the "Extensions" page, or any other page through the menu (Downloads, Settings, History, etc).
5) This doesn't happen if you directly type the URL (ie. `chrome://extensions`).

**Comment by Eloston** [comment]
Another restriction is that the tab has to stay on that URL. If you switch URLs, then the bug doesn't occur.

I've narrowed down the issue to tabs that have the `qjz9zk` top-level domain in the address bar. For example, going to any website then going to `qjz9zk`, and then opening Settings, Downloads, etc. will trigger the same bug.

This means that other buttons in Chromium that open pages like this will have the same problem. However, "Learn more" links don't have this issue because they immediately go to `about:blank`.

This is a very specific and narrow bug, because it only happens normally when then user clicks that help button on that page, and leaves the tab open on that URL. I guess I can workaround this by just removing the button.

**Comment by 9Morello** [comment]
Perhaps you could link the "Get help with Chromium" to this Github page?
Maybe change the text a bit to make it clear its about ungoogled-chromium.

**Comment by Eloston** [comment]
I don't want ungoogled-chromium to be branded like other Chromium forks, and I believe changing that button to point here would be considered part of a branding change.

Technically, the fact that this button and all the other "Learn more" links are broken is a bug caused by domain substitution. Those links don't connect to Google on its own or affect the user's privacy, security, transparency, or control.

**Comment by 9Morello** [comment]
I see. Makes sense. ungoogled-chromium feels just like regular Chromium, but without google integration - instead of a full blown fork. Good to read that this is intentional and you intend to keep it that way.
