### ISSUE TITLE
Update Windows support to version 67

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#428]
*Issue created for https://github.com/Eloston/ungoogled-chromium/issues/414#issuecomment-398911323. Comment content follows:*

> Building version 67.0.3396.87-1 on Windows seems to fail. Actually the build process doesn't even start.
> This is the output I get when running build.bat:
> https://paste.debian.net/plain/1030109
> 
> Also note that on same setup the build process starts normally for version 66.0.3359.181-1, so I'm guessing this is something inherent to the latest update.

**Comment by Wyse-** [comment]
The culprit seems to be line 22 of build.bat:
`call python tools\gn\bootstrap\bootstrap.py -o out\Default\gn.exe -s`

Here's the output (I redacted my full PATH, I don't think it's necessary):
https://paste.debian.net/plain/1030249

**Comment by Eloston** [comment]
What output do you get from running the command that failed with exit status 2? i.e. `'['C:\\Python27\\python.exe', 'C:\\ungoogled-chromium-master\\buildspace
\\tree\\build\\toolchain\\win\\setup_toolchain.py', 'C:\\Program Files (x86)/Mic
rosoft Visual Studio/2017/Community', 'C:\\Program Files (x86)\\Windows Kits\x08
', 'C:\\Windows\\Sysnative;C:\\Windows/SysWOW64', 'x64', 'true']'`

**Comment by Wyse-** [comment]
Okay, I believe I might've found out what is causing this. 
Here's the full content of the bootstrap.py and setup_toolchain.py files for reference:
[bootstrap.py](https://paste.debian.net/1030461/)
[setup_toolchain.py](https://paste.debian.net/1030462/)

First of all it doesn't seem like the above command is correct batch syntax. It's being built by bootstrap.py (lines 125-137) and probably executed some other way. 

From what I understand it executes setup_toolchain.py with python 2.7 and passes the rest of its contents as an array of arguments to the setup_toolchain.py script, which performs a check on its arguments (lines 185-190). In our case there's 6 (I'm guessing setup_toolchain.py itself is considered an argument) strings being passed as arguments and since they should be 8 the script returns exit code 2.

Also, the order in which the argument strings are being passed appears to be different from the one specified in lines 186-189 of setup_toolchain.py:
```
'Usage setup_toolchain.py '
          '<visual studio path> <win sdk path> '
          '<runtime dirs> <target_os> <target_cpu> '
          '<environment block name|none> <goma_disabled>'
```

It seems like setup_toolchain.py is being fed the following:

```
  win_sdk_path = sys.argv[2] (C:\\Program Files (x86)\\Windows Kits\x08)
  runtime_dirs = sys.argv[3] (C:\\Windows\\Sysnative;C:\\Windows/SysWOW64)
  target_os = sys.argv[4] (x64)
  target_cpu = sys.argv[5] (true)
  environment_block_name = sys.argv[6] (null)
  goma_disabled = sys.argv[7] (null)
```

I believe we're missing target_os and environment_block_name when calling setup_toolchain.py.
I tried modifying setup_toolchain.py with these values
```
  win_sdk_path = r'C:\Program Files (x86)\Windows Kits\10'
  runtime_dirs = r'C:\Windows\Sysnative;C:\Windows\SysWOW64'
  target_os = 'win32'
  target_cpu = 'x64'
  environment_block_name = 'none'
  goma_disabled = 'true'
```

And while this makes build.bat go further than before I get the following output:
https://paste.debian.net/plain/1030470

**Comment by Eloston** [comment]
Wow, this is pretty bad breakage. I guess they didn't update the GN bootstrap script for Windows in time (this isn't the first time this happened; it has happened with macOS before).

For future reference, I figured I'd document how I approached this problem:

Usually the next major version of Chromium has a newer snapshot of GN bootstrap.py, so I looked at the script for 68.0.3440.38.

I initially tried the online git-blame tool, but comparing dates and commit hashes was too tedious.

Then I compared the logs between the two versions ([67 here](https://chromium.googlesource.com/chromium/src/+log/67.0.3396.87/tools/gn/bootstrap/bootstrap.py) and [68 here](https://chromium.googlesource.com/chromium/src/+log/68.0.3440.38/tools/gn/bootstrap/bootstrap.py)) to and picked out the following commits to be included (based on changes that didn't add files not in 67):
```
95fe44b3c31cf5e1a668d9ef8853aaf2cf9523a5
0d3bbfb6b8ba05af199b49f5dd71d842f6acffda
```

and wrote them to a patch using the following shell command for each:
```sh
curl https://chromium.googlesource.com/chromium/src/+/COMMIT_HERE%5E%21?format=TEXT | base64 -d >> gn_fixes.patch.patch
printf '\n' >> gn_fixes.patch.patch
```
(replacing `COMMIT_HERE` with the full commit hash)

Then I added it to the proper patch order, refreshed it, and created the commit here: 3ea744b02afbb4b3dcac93d8d4fa9116d0d6183b

Let me know how that goes.

**Comment by Wyse-** [comment]
Awesome, 67.0.3396.87 Windows binaries built successfully on commit https://github.com/Eloston/ungoogled-chromium/commit/6453c2d13a03ee151211a82c06d281209876f688 of develop branch.
Here they are if anyone needs them:
https://github.com/Wyse-/ungoogled-chromium/releases/tag/67.0.3396.87-2

**Comment by Eloston** [comment]
Wow, we got lucky that nothing else needed changes. Neat.
