### ISSUE TITLE
[fr-Linux] Plz add the hardware video decoding patch. Yes its still busted.

### ISSUE THREAD

**Issue by forkoz** [Eloston/ungoogled-chromium#430]
In 2016 you said HW decoding would be added or was already fixed. Yet today I ran https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-dev vs ungoogled chromium and HW video decoding still doesn't work.

The option itself "Hardware-accelerated video" is unavailable. It says unsupported by your platform. Yes you can override the GPU list and it will say "enabled" but in chrome://gpu nothing is listed under video acceleration. In the other build several encodings and resolutions show.  

For the final test, I installed H264ify and watched the same 1080P youtube video in both browsers. Chromium-dev 8% cpu usage, ungoogled: 40%. 

Va-API support is not compiled in when building on linux. There are lots of discussions on this but still no resolution. Google supports it on ChromeOS so maybe that has something to do with the withholding of it from linux distros. Its even more comical that ungoogled-C will disable my hw decoding in chromium-dev since they somehow share a profile.

Anyways, the patches are here:

**Main patch**:
https://github.com/saiarcot895/chromium-ubuntu-build/blob/master/debian/patches/enable_vaapi_on_linux.diff
**I think for newer chromium (68, etc)**
https://github.com/saiarcot895/chromium-ubuntu-build/blob/master/debian/patches/enable_vaapi_on_linux_2.diff

Background info:

https://www.pcsuggest.com/chromium-hardware-accelerated-video-decoding-linux/
https://www.reddit.com/r/linux/comments/60o1l1/chrome_on_linux_needs_to_support_hw_video/
https://bugs.chromium.org/p/chromium/issues/detail?id=463440

they tried so hard and got so far....
https://chromium-review.googlesource.com/c/chromium/src/+/532294

**Comment by Eloston** [comment]
Are you using a build of ungoogled-chromium based on the Linux Rooted bundle? Since you mentioned that a `chrome://flag` is unavailable, it doesn't sound like it.

The Portable Linux build doesn't include [this VA-API patch](https://github.com/Eloston/ungoogled-chromium/blob/master/resources/patches/inox-patchset/chromium-vaapi-r18.patch). I don't see any reason why it can't be in Portable Linux, so it must've been a mistake I made. I'll move it so Linux Portable can have it too.

If the VA-API patch still doesn't work or you are already using a build with it applied, let me know.

**Comment by forkoz** [comment]
Thanks I grabbed portable because it was the newest build. I assumed they would all have the same feature set.
