### ISSUE TITLE
[Windows] 64-bit dependencies are used on 32-bit machines

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [Eloston/ungoogled-chromium#453]
like the title says will be good that document the steps of how to compile on x86 machine, because today the readme only says to change "x64" to "x86" but the problem is that the buildkit **still download x64 Dependencies**. in these cases will good that document how to compile ungoogled-chromium on a x86 machine

**Comment by Eloston** [comment]
Good catch. I believe you should be able to just change the dependency URLs to the correct 32-bit and update the hashes to have it work.

If this works, we can split up the Windows config bundle into three parts: `windows_common`, `windows_x64`, and `windows_x32`.

**Comment by Eloston** [comment]
Closing because we now offer 32-bit Windows binaries. Also, Chromium seems to [require a 64-bit machine regardless of the target architecture](https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md#system-requirements). If there is still interest in this, please open a new issue in ungoogled-software/ungoogled-chromium-windows.
