### ISSUE TITLE
No 4K video playback in YouTube on Debian Stretch

### ISSUE THREAD

**Issue by taahamahdi** [Eloston/ungoogled-chromium#463]
I'm not sure whether this is one of the limitations to preventing tracking from Google, but I am not able to stream video higher than 1080p@60fps from YouTube. I do not have any issues streaming 4K video from YouTube on other web browsers using the same machine.

**Comment by Eloston** [comment]
Actually, Debian's `chromium` on Stretch has the same issue. All Debian builds link against the system's `libvpx`, which provides VP8 and VP9 encoding. Debian Stretch has a really old libvpx version that doesn't support VP9 encoding, so it has been patched out in `patches/debian/system/vpx16.patch`. 4K YouTube videos are encoded only in VP9, but 1080p@60fps is also available in H.264 and/or VP8.

To fix this for Debian stretch, you can rebuild the browser with the bundled libvpx and remove `vpx16.patch`. Alternatively, you can upgrade to Debian buster or use Portable Linux.

I don't want to change the Debian stretch configuration because I want to stay as close to Debian's configuration as I can to ease upgrades.

**Comment by taahamahdi** [comment]
Thanks for the info!
