### ISSUE TITLE
Explain risks of disabling Safe Browsing

### ISSUE THREAD

**Issue by lorenzhs** [Eloston/ungoogled-chromium#50]
It seems that you disabled Google Safe Browsing, and I understand why people might want to do that. However, it's already designed with privacy protection in mind: it uses a local bloom filter to determine whether a URL might be dangerous, and only asks the servers if the bloom filter says "maybe". Even then, only hashes of the URL are transmitted whenever possible. This way, it leaks very little information, but provides good security benefits. Most users should probably have it enabled.

There's a good explanation at https://github.com/amq/firefox-debloat/issues/3

**Comment by 9Morello** [comment]
> only asks the servers
Considering the aim of this project, I can see why its disabled.
The main principle of this browser is that it will block any kind of connection to Google. As it is with other Google services, you'll lose a bit of convenience by not using them.

I think its likely that most users of ungoogled-chromium are also using add-ons like uBlock Origin, which already provides blocklists for malware domains.

**Comment by lorenzhs** [comment]
Well, who is the public of ungoogle-chromium? Phishing sites are designed to deceive, and they deceive power users, too. Safe Browsing also blocks sites serving malicious content (like exploit kits, where you don't even have to click anything to get infected). Isn't the privacy and information security impact of a malware infection worse than sending a few hashes of partial URLs to Google?



> 
The main principle of this project is that it will block any kind of connection to Google. As it is with other Google services, you'll lose a bit of convenience by not using them.

If it were only convenience you lost, then I wouldn't have filed this issue. This has a direct security impact on your users, and you're exposing them to risks without explaining what they are. I'm merely asking you to explain these risks, to make sure that users know what to expect.

Adblockers don't update often enough to provide the same level of protection, and if you're not preinstalling one, then you can't expect everyone to have one.

**Comment by 9Morello** [comment]
> Well, who is the public of ungoogle-chromium?

@Eloston should respond this one, but IMO the average user of ungoogled-chromium are power users who actively filter their browsing with extensions (such as uBlock Origin and uMatrix). They rather use a Chromium-based browser instead of Firefox or one of its forks because its way more responsive.

> Phishing sites are designed to deceive, and they deceive power users, too. Safe Browsing also blocks sites serving malicious content (like exploit kits, where you don't even have to click anything to get infected).

I've yet to see someone using uBlock Origin and/or uMatrix to get infected through phishing sites. Based on what you say "they deceive power users"? As anecdotal as it its, I've yet to see a normal, tech-illiterate user get infected with a proper adblock being installed.

>If it were only convenience you lost, then I wouldn't have filed this issue. This has a direct security impact on your users, and you're exposing them to risks without explaining what they are. I'm merely asking you to explain these risks, to make sure that users know what to expect.

I agree with you in this instance. Having a page explaining how safe browsing works would have no harm.

> Adblockers don't update often enough to provide the same level of protection, and if you're not preinstalling one, then you can't expect everyone to have one.
Source on this? What adblock are you using? uBlock Origin's default lists are updated almost every day.

Also, you're right in the sense that I cannot prove everyone using ungoogled-chromium is also using an Adblock. But I also highly doubt they aren't. If they are the kind of users to install this variant in the first place (maybe compiling it from source), I'm pretty damn sure they know what an adblock is.

**Comment by Eloston** [comment]
> Well, who is the public of ungoogle-chromium?

@9Morello pretty much got it. Users who understand the benefits of this project must already have a deeper understanding of the web and web browsers than an average internet surfer. These users are probably doing things to reduce their risk of being attacked, whether it be install extensions like uBlock Origin or disable plugins like Flash or Java. They could even run certain web applications within a VM when they need these features.

I'll add a section to the FAQ and README to inform users about the safe browsing situation.

**Comment by lorenzhs** [comment]
Thank you! I think this is helpful.
