### ISSUE TITLE
Building takes forever.

### ISSUE THREAD

**Issue by DrDonkey** [Eloston/ungoogled-chromium#500]
Tried building ungoogled on Manjaro xfce from aur, it already took 4 hours and still I am at file 5000/18k.
Is it supposed to take that much time or am I doing something wrong?
My processor is crap but still.

**Comment by Eloston** [comment]
Since the introduction of jumbo builds, single-threaded performance has become more relevant than in the past. If your processor's single-threaded performance is poor, that may be a factor. (There's documentation in the `docs/` folder *of the Chromium source tree* if you want to learn more.)

Also, IO performance is relatively important too (lots of intermediate files being generated), and having more RAM will help (so more data can be cached in RAM).

**Comment by DrDonkey** [comment]
Ok then. As I already said I got some old ass amd processor(dual core tho), and 2GB ram.
I guess I don't deserve ungoogled.

**Comment by Eloston** [comment]
That explain it.

> 2GB ram

I'm surprised building even works for you at all. The minimum required RAM is 8 GB according to Google's documentation, so if you end up using swap space...

**Comment by steven-omaha** [comment]
@DrDonkey There is also a precomoiled package available for Arch / Manjaro. It lacks behinds the git repository most of the time. Try `ungoogled-chromium-bin`.

**Comment by kovetskiy** [comment]
@steven-omaha oh, ok, I thought you are a maintainer.
