### ISSUE TITLE
error: unknown target CPU 'pentium-m'

### ISSUE THREAD

**Issue by ghost** [Eloston/ungoogled-chromium#530]
To build ungoogled-chromium I am using the script which I shared in [another issue](https://github.com/Eloston/ungoogled-chromium/issues/447#issuecomment-422958840). It works fine. Now as I am willing to cross-build UGC for another (older, 32-bit and much much slower) computer (see [cat /proc/cpuinfo](https://susepaste.org/bd4b76fd)) I tried to find which CPU name which `gcc` would detect and then use it in a `march` `CFLAG`. So on the target machine I ran:
```
gcc -march=native -Q --help=target | grep -- '-march=' | cut -f3
```
which gave me `pentium-m`. Then on the machine which runs the build script I exported `CFLAGS="-O3 -pipe -march=pentium-m -mtune=pentium-m"`. However this gives me a [series of errors](https://susepaste.org/7e63b193) which all show a similar message:
```
error: unknown target CPU 'pentium-m'
note: valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, iavx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cannonlake, iicelake-server, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, x8
```
I understant why `clang` complains - it obviously doesn't recognize all the architectures which `gcc` can use. However it doesn't give me a hint what architecture name I should actually use.

So what should I do?

**Comment by Eloston** [comment]
I don't think this is a problem with ungoogled-chromium; rather it is a problem with using the C/C++ compilers `clang` and `gcc`. Perhaps you should try asking the LLVM community for help first.

**Comment by anchev** [comment]
> Perhaps you should try asking the LLVM community for help first.

I have asked in clang's mailing list about 5 days ago but there is no reply whatsoever. So I hoped you might probably know as there is really no info about it.

**Comment by Eloston** [comment]
You could try StackOverflow and other compiling-related forums. I don't know much about compiler optimizations.

If you know the processor code name (e.g. haswell, broadwell, skylake, kabylake, etc.), then it seems `clang` should have one of them as an option.

**Comment by anchev** [comment]
> You could try StackOverflow

I have. Zero replies :(
FWIW: I have successfully cross-compiled for nocona and the binary works fine.

> If you know the processor code name (e.g. haswell, broadwell, skylake, kabylake, etc.), then it seems `clang` should have one of them as an option.

From what I see the error message of `clang` seems to list only 64-bit architecture names. This CPU is 32-bit though. Unfortunately even [this info](https://clang.llvm.org/docs/CrossCompilation.html#general-cross-compilation-options-in-clang) doesn't really answer in a clear way.

**Comment by anchev** [comment]
Finally I got some help on LLVM's lists. The key component is to add `-m32` to the command line in which case `CFLAGS=-O3 -pipe -m32 -march=pentium-m -mtune=pentium-m`. This works!

However I am getting some new errors (perhaps missing dependencies):

https://susepaste.org/a3d7b5bc

(On openSUSE Leap 15) I have installed all 32-bit versions of the prerequisite packages but for some of them `zypper` simply doesn't have a 32bit version. Even that didn't remove the errors though.

Can you help?

**Comment by Eloston** [comment]
It looks like the standard library headers aren't available for some reason. Based on the compiler command includes, it doesn't seem to be using Chromium's built-in libcxx library. So, you may need to have your system's standard library headers available so GN can be built. `linux_portable` should then use its own standard library to build Chromium itself.

**Comment by anchev** [comment]
I don't understand.

I am using the same `linux_portable` process as in #447 which has always worked so far for 64-bit architecures (including native and cross-compiling). The only difference as per the current issue is the target architecture/cpu (`pentium-m`). Re. libcxx, here is what `zypper` finds:
```
# zypper se libcxx
Loading repository data...
Reading installed packages...

S | Name                               | Summary                                                              | Type
--+------------------------------------+----------------------------------------------------------------------+--------
  | libcxx-gtk-utils-3-2_2-0           | Lightweight library for GTK+ programs using C++                      | package
  | libcxx-gtk-utils-3-2_2-0-debuginfo | Debug information for package libcxx-gtk-utils-3-2_2-0               | package
  | libcxx-gtk-utils-3-devel           | Lightweight library for GTK+ programs using C++ -- Development Files | package
  | libcxxtools-bin9                   | A C++ toolbox - binary RPC package                                   | package
  | libcxxtools-bin9-debuginfo         | Debug information for package libcxxtools-bin9                       | package
  | libcxxtools-http9                  | A C++ toolbox - HTTP protocol implementation                         | package
  | libcxxtools-http9-debuginfo        | Debug information for package libcxxtools-http9                      | package
  | libcxxtools-json9                  | A C++ toolbox - JSON package                                         | package
  | libcxxtools-json9-debuginfo        | Debug information for package libcxxtools-json9                      | package
  | libcxxtools-unit9                  | A C++ toolbox - testing library                                      | package
  | libcxxtools-unit9-debuginfo        | Debug information for package libcxxtools-unit9                      | package
  | libcxxtools-xmlrpc9                | A C++ toolbox - XMLRPC package                                       | package
  | libcxxtools-xmlrpc9-debuginfo      | Debug information for package libcxxtools-xmlrpc9                    | package
  | libcxxtools9                       | Collection of General-purpose C++ Classes                            | package
  | libcxxtools9-debuginfo             | Debug information for package libcxxtools9                           | package
```
What package(s) do I have to install?

**Comment by Eloston** [comment]
Perhaps the GN bootstrap script doesn't support cross-compiling. You can try setting native compilation flags for GN bootstrap, then change them to your desired `pentium-m` setting before you run `gn gen` and `ninja`.

**Comment by anchev** [comment]
> Perhaps the GN bootstrap script doesn't support cross-compiling.

How come? I cross-compile successfully for other 64-bit architecture as mentioned in an earlier comment.

Also the error is by `clang++` itself. Trying to run one of the problematic commands separately produces the same output. Adding a `-v` to it shows where it looks for includes:

https://susepaste.org/4830cd4f

Does that give a hint about anything?

> You can try setting native compilation flags for GN bootstrap, then change them to your desired pentium-m setting before you run gn gen and ninja.

Can you elaborate on this please?

FWIW: Currently [my build script](https://susepaste.org/01f12c78) inserts the `CFLAGS` before the line with the `ninja` command (just think that in the context of this discussion `architecture` and `cpu` are set to `penitum-m`).

**Comment by Eloston** [comment]
> How come? I cross-compile successfully for other 64-bit architecture as mentioned in an earlier comment.

As I understand it, you are compiling on a 64-bit host for a 32-bit target. Were you compiling on a 64-bit host for a 64-bit target before (existing 64-bit shared libraries can be used)? Were you compiling the same version of Chromium (GN bootstrap script has changed)?

> Can you elaborate on this please?

I am proposing that you modify `build.sh` so you have something like this:

1. Set flags to target native 64-bit architecture
2. Run GN bootstrap.py
3. Set flags to target your `pentium-m` machine
4. Run the rest of the build commands; i.e. `gn gen`, `ninja`

That way we avoid any issues with the target configuration requiring 32-bit headers that aren't configured correctly on your 64-bit host.

**Comment by anchev** [comment]
> As I understand it, you are now compiling on a 64-bit host for a 32-bit target.

Correct.

> Were you compiling on a 64-bit host for a 64-bit target before (because existing 64-bit shared libraries could be used)?

Yes.

> Were you compiling the same version of Chromium (because GN bootstrap script has changed)?

Yes.

> EDIT: I just re-read and you mentioned you could do both cross and native compilation (i.e. 64-bit host to 64-bit target, and 64-bit host to 32-bit target).

So far I have cross-compiled successfully only 64-bit host to 64-bit target. I am still struggling with 64 host to 32 target.

Re. the suggestion to reorder flags here is what I did:

First I moved the CFLAGS lines after the call of `bootstrap.py` and before the call of `ninja`. The resulting `build.sh`:

https://susepaste.org/80d52e41

The output shows some new error:

https://susepaste.org/7875fafd

Then I tried explicitly setting `native` flags before calling `bootsrap.py`:

https://susepaste.org/13c10e79

and that again gave the error:

https://susepaste.org/fd8c60a2

**Comment by Eloston** [comment]
> So far I have cross-compiled successfully only 64-bit host to 64-bit target. I am still struggling with 64 host to 32 target.

I see. Compiling for 32-bit targets from 64-bit hosts is another level of difficulty because of the number of differences between 32-bit and 64-bit architectures. You can't group cross-compilation of different CPU features (i.e. different supported assembly instructions) with the differences in the number of bits (i.e. 32-bit vs 64 bit); they are quite different.

> So far I have cross-compiled successfully only 64-bit host to 64-bit target. I am still struggling with 64 host to 32 target.

The fact that GN links now means that my assumption about the GN bootstrap script not supporting 64-bit to 32-bit cross compilation was correct.

> and that again gave the error:
> https://susepaste.org/fd8c60a2

From the paste:

```
/usr/include/glib-2.0/glib/gtypes.h:423:3: error: '_GStaticAssertCompileTimeAssertion_33' declared as an array with a negative size
  G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gmacros.h:232:103: note: expanded from macro 'G_STATIC_ASSERT'
#define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1] G_GNUC_UNUSED
                                                                                                      ^~~~~~~~~~~~~~~
```

It looks like you're trying to build against 64-bit system libraries, which obviously won't work because the address sizes are completely wrong (note `(sizeof (unsigned long long) == sizeof (guint64)` uses `guint64`, which I'm assuming is a 64-bit unsigned integer).

I belive you will need to set some GN flags in order to tell the build process to cross-compile a 32-bit binary. Unfortunately, I don't have any experience with this.

**Comment by anchev** [comment]
The doucmentation says that clang is a cross-compiler. From what you say it sounds to me that the program should be written in a way which supports cross compilation. I wonder what that means.

I suppose the discrepancy which you point out (`sizeof`) may be due to the assumption that the CFLAGS must be after the call of bootstrap.py because there are no such discrepancies if CFLAGS are set before bootstrap.py. IOW: isn't it more correct to look for a way to fix the failures with includes?

> I belive you will need to set some GN flags in order to tell the build process to cross-compile a 32-bit binary. Unfortunately, I don't have any experience with this.

How do you set thouse GN flags (in which file(s)?) and where can I read some documentation about what flags exists or may be needed?

**Comment by anchev** [comment]
So here is what I found:

[Discussion from 2015](https://groups.google.com/a/chromium.org/forum/?_escaped_fragment_=topic/chromium-dev/3d7-emSR0uI) suggesting some modifications for a 32-build. I don't know if those are applicable as of today of how to use them. In any all sources I found clearly say that it is impossible to build 32 bit chrome on 32 bit machine because the build process requires more memory than any 32 bit system can handle. So it must be done on a 64 bit machine.

A similar [discussion from 2016](https://groups.google.com/a/chromium.org/forum/?_escaped_fragment_=topic/chromium-dev/0gRhC35F5mM).

Official documentation about [Linux-specific build instructions](https://chromium.googlesource.com/experimental/chromium/src/+/refs/wip/bajones/webvr/docs/linux_build_instructions.md) where in system requirements it is written:

> x86 builds are not supported on Linux

Still in the Mandriva section it says:

> These packages are for 64 bit, to download the 32 bit packages, substitute lib64 with lib

which seems to contradict the above statement. I don't know if that implies that with certain modifications a 32-bit build would be possible (as per older discussions).

[GN build configuration documentation](https://www.chromium.org/developers/gn-build-configuration) which says:

> Chrome OS supports "x86" and "x64", but to build a 32-bit binary you will need to use a sysroot on a 64-bit machine.

I have no idea if that applies to chromium browser as well. It also suggests:

> For 32-bit official builds, append this arg to the above set: `target_cpu = "x86"`

Considering all that: can you recommend any particular steps to try (as I am honestly lost in what is discussed on Google groups) or is it a mission impossible (considering the info in system requirements).

**Comment by Eloston** [comment]
> The doucmentation says that clang is a cross-compiler. From what you say it sounds to me that the program should be written in a way which supports cross compilation. I wonder what that means.

Like I said before, cross-compilation is a broad term. Architecture is just one parameter that defines a target configuration, see the [Target Triple](https://clang.llvm.org/docs/CrossCompilation.html#target-triple) for other parameters. Compiling for different architectures (e.g. 64-bit to 32-bit) is much more challenging than compiling for the same architecture (e.g. 64-bit to 64-bit).

I believe Debian manages to build i386 packages on i386 systems. You can have a look at the `chromium-browser` source package to see how they did it. Otherwise if you must cross-compile, I'm not sure what all the flags (i.e. GN, CXX, LD, etc.) you will need. `target_cpu = "x86"` sounds like a good first step.

**Comment by anchev** [comment]
> Architecture is just one parameter that defines a target configuration, see the Target Triple for other parameters.

I have linked to the same reading earlier. The big question which still remains is: how does one specify the target tripple when building UC? Currently I do it by exporting CFLAGS inside `build.sh`. Are you suggesting any other approach?

> I believe Debian manages to build i386 packages on i386 systems. You can have a look at the chromium-browser source package to see how they did it.

I don't know how this can be possible, considering that chromim developers explain that linking needs more than 4GB of memory. Anyway re. Debian I searched and found [this](https://packages.debian.org/search?arch=i386&searchon=sourcenames&keywords=chromium-browser) but I have no idea where to look further (as it doesn't actually show how it was built).

Can you please "decypher" for me what [this](https://groups.google.com/a/chromium.org/forum/?_escaped_fragment_=msg/chromium-dev/3d7-emSR0uI/fz1Jm2bXDwAJ) means and how to use it in the context of UC? (considering that I am building `linux_portable` and not debian-specific)

**Comment by Eloston** [comment]
> I have linked to the same reading earlier. The big question which still remains is: how does one specify the target tripple when building UC? Currently I do it by exporting CFLAGS inside build.sh. Are you suggesting any other approach?

I see, I don't know much about the Target Triple beyond it being a compiler flag that affects how it should build the binary.

> I don't know how this can be possible, considering that chromim developers explain that linking needs more than 4GB of memory.

I'm not entirely sure if Debian builds its Chromium packages with cross-compilation or native compilation. [There are cross-compilation instructions here](https://wiki.debian.org/CrossCompiling#Building_with_dpkg-buildpackage). Debian's Chromium package has builds for the architectures `amd64`, `i386`, `arm64`, and `armhf`. There is some logic to set GN flags depending on the CPU architecture [inside the `debian/rules` file](https://salsa.debian.org/chromium-team/chromium/blob/master/debian/rules#L53), but I'm not entirely sure how or why the flags they configured work. If Debian does native compilation, maybe they use the settings `jumbo_file_merge_limit=12` and `concurrent_links=1` (inside that `debian/rules` file) to reduce enough RAM usage?

> Can you please "decypher" for me what this means and how to use it in the context of UC? (considering that I am building linux_portable and not debian-specific)

They are basically setting `target_cpu` to x86 and using a "sysroot". A sysroot is basically a pre-made chroot environment of an old Debian (in your link's case, wheezy) that Chromium links against for standard system libraries. A few notable details:

* Using a sysroot maximizes Chromium's shared library backwards-compatibility because the sysroot is generally made of an older Linux distro. It also increases consistency across builds by using the same shared libraries.
* Google normally uses sysroots in Linux builds, but ungoogled-chromium and all other Linux distros that package Chromium don't use them.
* Sysroots are normally downloaded as archives containing a pre-made environment from Google in normal Chromium builds.
* IIRC, there are scripts in the Chromium repository to create a sysroot archive.

**Comment by anchev** [comment]
Thanks for the info. I will have to look into all that more carefully.

> Google normally uses sysroots in Linux builds, but ungoogled-chromium and all other Linux distros that package Chromium don't use them.

Does that mean there is a risk of ending up with a binary which is not ungoogled?

**Comment by Eloston** [comment]
> Does that mean there is a risk of ending up with a binary which is not ungoogled?

Potentially yes, only if you use Google's pre-built sysroot while building.

**Comment by Eloston** [comment]
Sorry, I didn't make it very clear in my previous comment. There are scripts in the Chromium source code to create a sysroot environment of Debian using Debian's repositories. You would need to use these scripts to create an i386 sysroot environment, and configure the Chromium build to use it. In addition, you'll also need to set `target_cpu` to x86 as well.

I don't know how the sysroot creation scripts work, so I cannot provide instructions. However, I will be learning more when ungoogled-chromium starts to integrate sysroots for `linux_portable` builds.

**Comment by anchev** [comment]
Thanks for clarifying.

Are [these](https://chromium.googlesource.com/chromium/src/+/lkgr/build/linux/sysroot_scripts) the scripts you are you are talking about?

**Comment by Eloston** [comment]
> Are these the scripts you are you are talking about?

Yes, specifically the `sysroot-creator*` scripts. [There is a little bit of documentation in Chromium's docs/linux_sysroot.md](https://chromium.googlesource.com/chromium/src/+/lkgr/docs/linux_sysroot.md)

**Comment by Eloston** [comment]
So Debian still supports compiling 32-bit (`i386`) binaries on 32-bit machines. I believe other distros support this as well, but I haven't confirmed. If you are still having troubles with this, let us know.
