### ISSUE TITLE
Brave patches

### ISSUE THREAD

**Issue by dimqua** [Eloston/ungoogled-chromium#543]
Developers of the Brave desktop browser are maintaining a set of patches which may interested you:
https://github.com/brave/brave-core/tree/master/patches
Probably, you cherry-pick those related to privacy and security, and add them to the project.

**Comment by intika** [comment]
i checked a little bit the list of patches from brave and i have 2 issues about it 

1. The names of the patches are not very clear sometime 
2. I did not really find patches about privacy on the list you linked (i only came around translation patch components-translate-core-browser-language_state.h.patch and components-translate-core-browser-translate_url_fetcher.cc.patch) but i think core translation servers are already disabled on UC 

So i don't really see a patch that can help this project, but i may missed something can you please point out a patch if you find one useful for this project ?

**Comment by pjv** [comment]
See also: https://github.com/brave/brave-browser/issues/1431

**Comment by Eloston** [comment]
@pjv Huh. It's always surprising for me to see the impact of this project, considering my scope is pretty limited to GitHub.

@intika Thanks for investigating. For the issues list you found, we could pick applicable ideas to implement. (Please open seperate issues for them.)

**Comment by Eloston** [comment]
@dimqua If you find any Brave patches that are applicable to this project, please let us know.

**Comment by pjv** [comment]
from an AMA with Brave's CISO

<img width="958" alt="2018-10-19 at 12 07 pm" src="https://user-images.githubusercontent.com/327716/47233308-e0cf3b00-d397-11e8-98c4-da898d2c6149.png">

**Comment by lluke777** [comment]
What are the advantages in privacy of `ungoogled-chromium project` over `Brave browser`?

**Comment by remus-selea** [comment]
How about the tests written by a Brave employee (https://github.com/privacytests/privacytests.org and results https://privacytests.org/, haven't actually run them myself) which seem to show that Brave offers more in terms of privacy over ungoogled chromium? Is there something from Brave that could be added to ungoogled-chromium to improve the privacy? I'm curious because at this time I'm just [disabling stuff from Brave](https://github.com/brave/brave-browser/issues/31651) to benefit from this presumably "better privacy" that it has over ungoogled-chromium.

**Comment by PF4Public** [comment]
> tests written by a Brave employee
> haven't actually run them myself
> which seem to show that Brave offers more  in terms of privacy

You should be more careful about such statements. One should also interpret test results very carefully.

**Comment by rany2** [comment]
Also, these tests only considers the DEFAULT browser settings; UGC requires you to enable many of the privacy features via chrome://flags. It also depends on your definition of privacy; for example, Brave regularly phones home for Widevine, dictionary, crypto integration, etc but UGC doesn't connect to any servers other the sites you explicitly want to browse :)

**Comment by eliandoran** [comment]
@rany2 , I would say that it's more relevant to compare what Brave brings to the table in terms of privacy, rather than what it does worse (like phoning home) and see how those can be integrated in Ungoogled Chromium.

Are there any `chrome://flags` that can be activated to tick more boxes in privacytests.org for Ungoogle Chromium? I think extensions might be able to cover some of them as well, but it would be nice to have a reference for them.

**Comment by PF4Public** [comment]
> Are there any `chrome://flags` that can be activated to tick more boxes

You can search `ungoogled` in `chrome://flags` if you're already using ungoogled-chromium. And if you're not, here are some of them: https://github.com/ungoogled-software/ungoogled-chromium/blob/master/docs/flags.md
