### ISSUE TITLE
Statically linked binary for Linux x64

### ISSUE THREAD

**Issue by tavlima** [Eloston/ungoogled-chromium#554]
Would someone in the community willing to publish such artifact? I'm having a really hard time trying to built it myself...

**Comment by intika** [comment]
What's the exact issue ? 
If you need help building give more details about the system you are using and the steps you are doing

Building help page and other closed issue should help you to get the project building on your system

**Comment by Eloston** [comment]
If you're referring to Portable Linux, then builds are already available on the Contributor Binaries website. Otherwise, let us know what specific difficulties you are encountering.

**Comment by tavlima** [comment]
@Eloston, I tried to follow the build instructions in master, but they seem to be outdated. Tried the instructions in the specific tag used by the latest (stable) Linux Portable binary artifact, but also to no avail.

And I really mean statically linked binaries, which is not the case of the Portable Linux published in the Contributor Binaries:

```
# Looking into ungoogled-chromium_67.0.3396.87-1_linux.tar.gz ...
$ ldd chrome | grep "not found"
libatk-bridge-2.0.so.0 => not found
libgtk-3.so.0 => not found
libgdk-3.so.0 => not found
```

**Comment by Eloston** [comment]
@tavlima I've reported the statically-linked issue in #556.

Regarding the build instructions, please use the instructions in the tag you've downloaded instead of referencing `master`. I have added a notice about this.

In addition, Chromium 67 is not the latest stable. Please refer to the latest tags instead of GitHub Releaes. I've added a notice to the latest GitHub Releases with this info.
