### ISSUE TITLE
few questions on improvements for macOS build..

### ISSUE THREAD

**Issue by pastmaster007** [Eloston/ungoogled-chromium#558]
hi @Eloston, i have few questions..

Are we using domainsubcache.tar.gz file anywhere after zipping?
Can we create this zip file inside "build/src/out" folder?

Currently, dmg file creates in "build/src/ungoogled_packaging" folder, can we move it to "build/src/out" folder?
we may need to update build readme file, which says dmg file will create in build folder..

Can we comment "-Wno-ignored-pragma-optimize" flag in "build/config/compiler/BUILD.gn:1519" for macOS?
looks like this flag mainly for Microsoft optimzation which means for WindowsOS..

**Comment by Eloston** [comment]
> Are we using domainsubcache.tar.gz file anywhere after zipping?

If by "zipping", you mean the production of an archive of the build outputs, then no. `domainsubcache.tar.gz` exists to allow people to revert domain substitution. The main use case is to allow developers to update patches and resume building, since patches can include code with Google domains in them.

> Can we create this zip file inside "build/src/out" folder?
> Currently, dmg file creates in "build/src/ungoogled_packaging" folder, can we move it to "build/src/out" folder?

Could you explain why?

> Can we comment "-Wno-ignored-pragma-optimize" flag in "build/config/compiler/BUILD.gn:1519" for macOS?
> looks like this flag mainly for Microsoft optimzation which means for WindowsOS..

Here's the relevant comment for the associated bug report (in the GN file you linked): https://bugs.chromium.org/p/chromium/issues/detail?id=505314#c7

The report says that `pragma optimize` breaks Windows compilation. So, they ignore it by default and add exceptions for configurations like macOS so that the warning doesn't appear.

I don't see any benefit of removing the flag.

**Comment by pastmaster007** [comment]
> > Are we using domainsubcache.tar.gz file anywhere after zipping?
> 
> If by "zipping", you mean the production of an archive of the build outputs, then no. `domainsubcache.tar.gz` exists to allow people to revert domain substitution. The main use case is to allow developers to update patches and resume building, since patches can include code with Google domains in them.
> 
I mean archive file for "zipping"..
> > Can we create this zip file inside "build/src/out" folder?
> > Currently, dmg file creates in "build/src/ungoogled_packaging" folder, can we move it to "build/src/out" folder?
> 
> Could you explain why?
> 
Just checking as this is an output file, so can we keep in out folder or is it okay to keep in ungoogled_packaging folder?
> > Can we comment "-Wno-ignored-pragma-optimize" flag in "build/config/compiler/BUILD.gn:1519" for macOS?
> > looks like this flag mainly for Microsoft optimzation which means for WindowsOS..
> 
> Here's the relevant comment for the associated bug report (in the GN file you linked): https://bugs.chromium.org/p/chromium/issues/detail?id=505314#c7
> 
> The report says that `pragma optimize` breaks Windows compilation. So, they ignore it by default and add exceptions for configurations like macOS so that the warning doesn't appear.
> 
> I don't see any benefit of removing the flag.

I see below warning 11462 times..
> warning: unknown warning option '-Wno-ignored-pragma-optimize'; did you mean '-Wno-ignored-pragma-intrinsic'? [-Wunknown-warning-option]
> 1 warning generated.

**Comment by Eloston** [comment]
> I mean archive file for "zipping"..

I don't understand what you are referring to. Do you mean the creation of `domainsubcache.tar.gz`, or the `.dmg` (which can be understood as an archive)?

> Just checking as this is an output file, so can we keep in out folder or is it okay to keep in ungoogled_packaging folder?

It doesn't matter too much for this specific file, but I'd rather keep files introduced by ungoogled-chromium in one place. The compressed archive isn't part of the normal Chromium build process, but something generated by ungoogled-chromium tools.

> I see below warning 11462 times..

This might be because we're using the old LLVM 6.0.0 on macOS. What happens if LLVM 7.0.0 is used? FYI, LLVM is normally downloaded via `downloads.ini` in the `macos` config bundle.

**Comment by pastmaster007** [comment]
> I don't understand what you are referring to. Do you mean the creation of `domainsubcache.tar.gz`, or the `.dmg` (which can be understood as an archive)?
> 
I was asking about "domainsubcache.tar.gz" file, i got answer in your previous comment.. 
the reason for asking, when i recompile with 70 chrome, previous build's (chrome 69) "domainsubcache.tar.gz" files exists and new build exited with error. I deleted "domainsubcache.tar.gz" file from "ungoogled_packaging" folder and tried, then build works fine. 
In general, how do you start rebuild? by deleting entire "ungoogled_packaging" folder and run python script?

> It doesn't matter too much for this specific file, but I'd rather keep files introduced by ungoogled-chromium in one place. The compressed archive isn't part of the normal Chromium build process, but something generated by ungoogled-chromium tools.
> 
We may need to update build readme file for macOS, it says DMG file might generate in build folder.. So, i was thinking DMG file should be in "out" folder instead of build folder, that's why i asked question :)

> This might be because we're using the old LLVM 6.0.0 on macOS. What happens if LLVM 7.0.0 is used? FYI, LLVM is normally downloaded via `downloads.ini` in the `macos` config bundle.
>
Currently, i am using 6.0.0, i will try update to latest and verify..
Do i need to update google toolbox version too? we are using from jul 24th 2017 version..

**Comment by Eloston** [comment]
> In general, how do you start rebuild? by deleting entire "ungoogled_packaging" folder and run python script?

There's no rebuild support, because the logic to do so robustly is sophisticated. It is up to the user to determine how to restart the build. However, if you halted your build during `ninja` and you need to restart it, you can generally re-run just the `ninja` command as shown in the build script. Then, the packaging script can be run normally.

> We may need to update build readme file for macOS, it says DMG file might generate in build folder.. So, i was thinking DMG file should be in "out" folder instead of build folder, that's why i asked question :)

Ah, I didn't realize the instructions were out-of-date. I'll update it.

> Do i need to update google toolbox version too? we are using from jul 24th 2017 version..

It depends if `DEPS` at the root of the source tree is using a newer version or not.

**Comment by Eloston** [comment]
Closing since questions seem to be answered and inactivity.
