### ISSUE TITLE
Sanitize the web through bundled plugins

### ISSUE THREAD

**Issue by probonopd** [Eloston/ungoogled-chromium#574]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when each website nags me with questions about cookies, and displays lots of ads.

Especially when you delete cookies after each session anyway, this becomes **really** annoying.

![nag](https://user-images.githubusercontent.com/2480569/47613331-756b2480-da8d-11e8-825b-f2f750dae8ef.png)

**Describe the solution you'd like**

Have a "No Nonsense Edition" of this browser that comes with
* [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm)
* [I don't care about cookies](https://chrome.google.com/webstore/detail/i-dont-care-about-cookies/fihnjjcciajhdojfnbdddfaoknhalnja)

preinstalled and preconfigured.

**Describe alternatives you've considered**

Manually install those plugins. But it'd be a huge plus if there was a modern browser with those pre-integrated.

**Comment by intika** [comment]
@probonopd i personally use the same solution as you and probably as many users... but integrating the extension in uc is just out of the scope of the project i don't really see the benefit of bundling the whole thing... 
now browser are integrating ab blocking in their main code... we will may be see this feature coming around... 
Now you have to be careful for legal reasons because the cookie notification thing is there for a legal reason and disabling it with integrated component without letting the user choose it himself may put you in an illegal situation (... just to say)

**Comment by probonopd** [comment]
About the cookie thing, the sane thing would have been to have a setting in the browser, that in turn would communicate the user's consent (or lack thereof) to cookies as part of the request header.

Plus, as long as i don't click "accpet", do websites still use cookies? Because I never click these buttons...

**Comment by Eddi2015** [comment]
I also like this ideas @probonopd . As already said by others there might be some issues. ~99.5 % of the websites work with uBlock Origin, but none technical users might wonder at the 0.5 % of the sites why it doesn't work. So I still would leave it up to the user to install the extension. Maybe we can add some sort of startpage on the first launch that prposes to install those extensions and is able to insatll (and update) with one click. Maybe a related project: [](https://github.com/UnnoTed/Ungoogled-Chromium-Extension-Installer)

**Comment by hasufell** [comment]
If you want preinstalled protection and whatnot, you are better off using brave browser, because that's exactly what they do. This is just a patched chromium. I think it's good to keep the scope small.

**Comment by dimqua** [comment]
Is there any way to update extensions automaticly?

**Comment by intika** [comment]
> Is there any way to update extensions automaticly?

may be opening classic chromium and let it updates the extensions... but it will not work in future version if @Eloston decide to change the profile location... also do a backup of your profile before proceeding... there is may be an other solution that i am not aware of.

**Comment by anchev** [comment]
> Have a "No Nonsense Edition" of this browser that comes with
> ...
> preinstalled and preconfigured.

The nonsense come from the web sites, not from ungoogled-chromium. 'preinstalled' implies someone choosing software and version for another and everyone conforming to that choice. (this is what Google does in Googled Chrome). Similarly 'preconfigured' implies that someone else knows what I want which is nonsense itself.

> About the cookie thing, the sane thing would have been to have a setting in the browser, that in turn would communicate the user's consent (or lack thereof) to cookies as part of the request header.

As @intika explained: cookie consent has legal implications and exactly because of them you see all those annoying notifications on various sites. Site owners are required by the law to display them (GDPR etc.) So it is not sane thing to use a catch-all consent. I may trust my bank but I don't trust Zuckerberg (just an random example).

> Plus, as long as i don't click "accpet", do websites still use cookies? Because I never click these buttons...

Legally the cookie consent is required only for cookies related to your 'personal data' (as defined in GDPR), e.g. tracking cookies. No consent is required for "regular" (e.g. login) cookies. That said: don't rely on sites following strictly the law or being bug free.

If you want to sanitize your web experience:

0. Use Internet as little as possible
1. Don't trust anything on the web (me included)
2. Use a clean browser, not something with pre-installed choices
3. Configure everything the way you want it to work
4. Be wise. Don't rely on anyone respecting your (non-)consent.

Personally I use uBO, uMatrix and HTTPS everywhere, I have all cookies disabled and enable them only on sites on which I need to login. I also have JS disabled and enable it only temporarily for a specific site, with all other tabs and apps closed as I am paranoid about the CPU vulnerabilities which will stay with us for quite a long time as it seems.

**Comment by Eloston** [comment]
@probonopd Recall that ungoogled-chromium is Google Chromium, sans integration with Google. Thus, preloading extensions that changes the browsing experience significantly would violate this objective.

If you want integrated adblocking/privacy features by default, you may be more interested in projects like Brave Browser (as mentioned earlier). ungoogled-chromium will not take a stance on these kinds of issues for its users (except Google integration). At most, this project enables users to go beyond the vanilla Chromium experience via the addition of disabled-by-default feature flags.
