### ISSUE TITLE
gen.py: error: no such option: --no-sysroot

### ISSUE THREAD

**Issue by anchev** [Eloston/ungoogled-chromium#590]
### Description

`build.sh` exits with the specified error and the build process terminates.

### Console output and logs

```
...
+ ./tools/gn/bootstrap/bootstrap.py -o out/Default/gn
Usage: gen.py [options]

gen.py: error: no such option: --no-sysroot
Traceback (most recent call last):
  File "./tools/gn/bootstrap/bootstrap.py", line 92, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./tools/gn/bootstrap/bootstrap.py", line 78, in main
    subprocess.check_call(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '/tmp/download/ungoogled-chromium/build/src/tools/gn/build/gen.py', '--no-last-commit-position', '--out-path=/tmp/download/ungoogled-chromium/build/src/out/Release/gn_build', '--no-sysroot']' returned non-zero exit status 2
```

### Environment details

* ungoogled-chromium version: 70.0.3538.102
* Configuration bundle: `linux_portable`
* OS and version for building: openSUSE Leap 15.0
* Compiler toolchain:
```
clang -v
clang version 8.0.0 (trunk 346299)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /<***>/llvm-build/bin
Found candidate GCC installation: /usr/lib64/gcc/x86_64-suse-linux/7
Selected GCC installation: /usr/lib64/gcc/x86_64-suse-linux/7
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

### Building and packaging steps

The same described in #447.

**Comment by intika** [comment]
loooool

**Comment by intika** [comment]
Try removing `use_sysroot=false` from 'config_bundles/common/gn_flags.map' (just after git clone)

**Comment by anchev** [comment]
Tried. The issue remains.

**Comment by Eloston** [comment]
Might be because bootstrap.py wasn't updated after the snapshot of the GN repo was updated. I'll look into it.

**Comment by saltama** [comment]
I've added a patch for this [in this branch](https://github.com/saltama/ungoogled-chromium/tree/sysroot-patch), but I'm not opening a PR since this should be fixed once we have a new source tarball from chromium (the most recent I can download is 70.0.3538.102, newer ones are not available yet it seems).

**Comment by Eloston** [comment]
@saltama I think tarballs are usually built whenever a new stable version is released. Are there cases where they manually trigger builds of non-stable versions? If manual build triggering does not happen and and the next stable is not due for a little wihle, then it may be a better idea to include the patch so we can stay with the latest stable version.

**Comment by saltama** [comment]
I've noticed that they store those files in a S3v1 API-compatible server, and a [query shows](https://commondatastorage.googleapis.com/chromium-browser-official/?prefix=chromium-70.0.3538.1) they've just generated `chromium-70.0.3538.110`.
Those builds look like the result of manual triggering since I can't see any clear pattern.

71.x should become the new stable [in 3 weeks or so](https://chromiumdash.appspot.com/schedule), so I suppose there will not be many additional 70.x releases.

I'm building 110 now to verify if the patch is still needed and if the other patches still apply correctly.

**Comment by saltama** [comment]
Ok, the no-sysroot patch is still needed in 110, opening a PR.
By the way, as expected a few patches will need to be updated for 110.
