### ISSUE TITLE
[User discussion] ungoogled-firefox (Librefox)

### ISSUE THREAD

**Issue by intika** [Eloston/ungoogled-chromium#594]
**Just published an equivalent work for firefox**
https://github.com/intika/privafox-firefox

**Privafox-Firefox** : Tuning firefox settings (about:config) for a better security, privacy and performances. Firefox does not need to be rebuilt to be cleaned from privacy/security issues; as all settings can be changed in the about:config This project aim to fix all security/privacy issues related to firefox and also tune it to gain some speed performances.

**Comment by anchev** [comment]
> Firefox does not need to be rebuilt to be cleaned from privacy/security issues; as all settings can be changed in the about:config

I question that and you should question it too (unless you have inspected personally all the millions of lines of code).

> This project aim to fix all security/privacy issues related to firefox and also tune it to gain some speed performances.

This is an impossible task, so no serious project should ever claim even an attempt for full security and privacy, especially in conjunction with speed performance. Not only because security and speed are contradictory (in today's computer world) but also because of all the issues in the hardware itself which cannot be fixed - neither at kernel level, even less at browser settings level.

**Comment by anchev** [comment]
> i don't have the time to maintain a more elaborated version

This is quite different from the claim about aiming to fix all security/privacy. Also please bear in mind:

I am not alone != everyone who is with me is right
Aiming to secure != secure
Mitigation != fix
Not in my vocabulary != not a fact (and vice versa)
Usability <-> security (in today's computers)

In any case this is much more off-topic than the issue about implementing Tor functionality in UC, so we should probably stop here :)

**Comment by intika** [comment]
> In any case this is much more off-topic than the issue about implementing Tor functionality in UC, so we should probably stop here :)

Indeed
