### ISSUE TITLE
Windows Safe Browsing patches are out-of-date

### ISSUE THREAD

**Issue by ribatamu** [Eloston/ungoogled-chromium#619]
Please, if anybody had updated Windows build to shared.

**Comment by azdps** [comment]
With some changes that have recently been fixed with the Windows build I have been able to get almost all the way through the build process. Unfortunately, the build process fails when building the safebrowsing portion of ungoogled-chromium. Looking through some of the patches and the files that are being patched it looks like the Windows safebrowsing patches need to be updated. Not only are there specific patches for Windows there's also other safebrowsing patches as well that are applied in a certain sequence during the patch process. Not sure if those patches are having a negative impact as well.

**Comment by waqas** [comment]
Yes, related to Safebrowsing. Minus those patches and someone has released the build...
https://chromium.woolyss.com/#comment-4085

**Comment by intika** [comment]
Safe-browsing patches needs to be updated windows builds are failing because of it (re enabling safe-browsing https://github.com/Eloston/ungoogled-chromium/issues/639#issuecomment-466478108 to be able to build)

**Comment by Eloston** [comment]
Closing. Please continue discussin in the referenced issue.
