### ISSUE TITLE
64 bit build for Windows

### ISSUE THREAD

**Issue by xianwenchen** [Eloston/ungoogled-chromium#62]
I'm curious if it's possible to produce a 64 bit build for Windows. I'm actually interested in producing it myself, if you wouldn't mind helping me get started. :-)

**Comment by Eloston** [comment]
I haven't tested it, but the code should be there to build it. Do you have some understanding of Python? You'll need to add two lines to `build.py`:
* Import `CPUArch` from `buildlib.common`
* Set the `target_arch` attribute of `builder` to be `CPUArch.x64`

Then run `build.py` normally and hope for the best.

**Comment by xianwenchen** [comment]
Thank you!

**Comment by woolyss** [comment]
Hello everybody,

Please, can you test new releases of chromium 64-bit **with ungoogled-chromium** patches?
https://chromium.woolyss.com/#windows-64-bit-test-nik

For info, nik is the main developer of stable Chromium 64-bit versions, available over the Internet.

**Comment by Eloston** [comment]
Hi @woolyss, I really like your website. It has great info and binaries that I've used from time-to-time. Thanks :)

A few questions: Does nik's build use domain substitution or source cleaning? Did nik use buildlib, or include the patches in his own build process?

**Comment by woolyss** [comment]
Hello @Eloston, thank you very much. I made a simple resource.

 I am no nik but I can try to answer you. He probably will come here! ;)
1) He uses source cleaning.
2) I do not know if he uses buildlib but he includes [the patches](https://github.com/Eloston/ungoogled-chromium/blob/master/resources/common/patches/patch_order) in his own build process.

Nik does not use all patches because there are few limitations. Some of patches are not working because they are for GYP build system (fix-building-without-one-click-signin.patch and others). Nik compile Chromium with GN build system.

**Comment by chrme** [comment]
Hi @Eloston, i've used **some** of your patches from "patch_order" file only (some was failed and some i've disabled because of "trk" part and domain substitution).

**Comment by Eloston** [comment]
@chrme @woolyss 

I see. Well that's a bit unfortunate. Would you mind adding a disclaimer on the site saying that several patches and domain substitution are not used? Also, since you're using GN, I'm guessing you're using binaries provided by Google? If so, I would also like that to be mentioned in the disclaimer.

I may sound pedantic, but I think these differences are among the major features that ungoogled-chromium has to offer. The patches that depend on GYP are those that disable the more integrated features, and building without Google binaries gives users more certainty that Google isn't doing something behind our backs.

**Comment by woolyss** [comment]
@Eloston: Ok, I understand. I am writing a disclamer on the site.

**Comment by Eloston** [comment]
@woolyss Thanks

> Finally, can you compile a 64-bit version of ungoogled-chromium for Windows?
> I think it could be better than our merged builds! ;)

Yeah I'm planning to do that as soon as I can.

**Comment by woolyss** [comment]
> Yeah I'm planning to do that as soon as I can.
Nice! Thank you for your work and support.

**Comment by chrcoluk** [comment]
woolyss so what happened to your builds? I see no mention of it on your site.

**Comment by woolyss** [comment]
@chrcoluk, I have nothing against Eloston and its project but see my review at:
https://chromium.woolyss.com/?all=1#comment-1566
(note this link will display all comments, so the content can be slow to display)

Anyway, you can download a 64-bit version (chromium-ungoogled.zip) at:
https://github.com/henrypp/chromium/releases/tag/v53.0.2785.143-r403382-win64

For info, you will find a site archive at:
https://web.archive.org/web/20161115065312/http://chromium.woolyss.com/#windows-64-bit-chocolatey

**Comment by Eloston** [comment]
#147 implements this. Going to make x86 and x64 builds and upload them to the next tag.
