### ISSUE TITLE
src build: clang-7 hard coded requirement not needed when clang 8 installed

### ISSUE THREAD

**Issue by marksolaris** [Eloston/ungoogled-chromium#633]
### Description

I've manually compiled and installed the version 8 clang suite (clang++, lld, llvm etc) from the llvm.org source code. It's installed as a clang-8 binary, but not as an apt package. I don't have a clang-7 apt installed.

It'd be useful to have the linux builds detect for clang-7 or better, thus finding clang-8 etc and continuing without substitutions in the build files.

### Environment details

* ungoogled-chromium version: 71.0.3578.98-2 (actually git master 2018-12-17 zip)
* Configuration bundle: debian_bionic for ubuntu 18.04
* Packaging type (if applicable): ?
* OS and version for building: Ubuntu 18.04
* Compiler toolchain: clang 8 etc trees from llvm.org

### Building and packaging steps

cd /local/ungoogle-chrome
rm -rf ungoogled-chromium-master
unzip /var/tmp/ungoogled-chromium-master_2018_12_17.zip
cd ungoogled-chromium-master/
mkdir -p build/src
./get_package.py ubuntu_bionic build/src/debian
cd build/src/
perl -pe 's/clang-7/clang/g' -i debian/rules
perl -pe 's/clang\+\+-7/clang++/g' -i debian/rules
perl -pe 's/llvm-nm-7/llvm-nm/g' -i debian/rules
perl -pe 's/llvm-ar-7/llvm-ar/g' -i debian/rules
./debian/rules setup-local-src
perl -pe 's/clang-7\,/wdiff,/' -i debian/control
perl -pe 's/lld-7\,/wdiff,/' -i debian/control
perl -pe 's/llvm-7-dev\,/wdiff,/' -i debian/control
setenv PATH "/root/bin:/usr/local/bin:/bin:/etc:/usr/etc:/usr/bin:/usr/bin/X11:/usr/local/sbin:/sbin:/usr/local/go/bin:/root/go/bin:/usr/local/etc:/usr/sbin"
dpkg-buildpackage -b -uc

**Comment by Eloston** [comment]
At the time of writing, this isn't a huge issue because only LLVM 8 can build Chromium 74 with the build flags we have set.

Also, I'm hesitant to support multiple versions of LLVM at a time (even if they're newer) because I cannot guarentee that they will build correctly. I had at least one case where some bug in an unstable LLVM build broke Chromium builds (albeit clang failed noisily, but I don't know if or what silent errors could occur).

If you really want this feature, please make a PR to ungoogled-chromium-debian (and any other platform repo you want). I'm not really interested in implementing this feature for the above reasons.
