### ISSUE TITLE
[User discussion] Interviewing a success project owner (Eloston/ungoogled-chromium)

### ISSUE THREAD

**Issue by intika** [Eloston/ungoogled-chromium#648]
@Eloston 

As always thank you for your amazing hard work in this project it one of a kind :) I would like to ask you some advice for my little young project [Librefox](https://github.com/intika/Librefox) 

1. What do you think made ungoogled-chromium successful ? 
2. Regarding the stargazers and [star-track](https://seladb.github.io/StarTrack-js/) (see capture bellow) i see that you gained over 2000 :star:  in just few days and twice on 09/25/2016 and 09/22/2018 it's amazing ! what's the secret ? :smiley: 
3. Do you have any advice/comments regarding the [direction of my project](https://github.com/intika/Librefox/issues) ?

Thank you very much :) 

![screenshot_2018-12-29 github star history and stats](https://user-images.githubusercontent.com/6892180/50534231-a7ead980-0b31-11e9-82ac-08765bc85a2f.png)

**Comment by intika** [comment]
For the stars thins i guess i have the answer the first boom is from a [reddit](https://www.reddit.com/r/linux/comments/54fbpo/ungoogledchromium_a_chromium_variant_for_removing/) post and [lifehacker](https://lifehacker.com/ungoogled-chromium-strips-away-the-privacy-invading-fea-1787139870) article, the second one i think its me joining the team hahhaha just kidding i have no clue for the second one

**Comment by intika** [comment]
Also one thing, a lot of people asked me about mozilla trademark (Firefox) while i was disturbing a patched version it's curious that uc did not face this problem, i guess google folks are more permissive.

**Comment by Eloston** [comment]
> What do you think made ungoogled-chromium successful ?

"Success" is a pretty broad term. I will assume you define "success" based on the number of users, what users say about the project, and the kinds of bug reports this project receives. In that case, there are several points I can note (in no particular order of importance):

* **Continual desire to improve the project and oneself. I think this is the most important point.** I mainly gather ideas based on feedback, experiences from this and past software projects, and experimenting with software in general. I also gather ideas by reading code and docs from Google, reading technical blog posts about software, and reading about new developments in software engineering.
* Dedicating a lot of time to the project. Especially in the following areas:
    * Consistent attention to overall quality of documentation, code, and user experience (building the browser, using the browser, downloading pre-built binaries, reading documentation, etc.)
    * Responding to feedback on GitHub.
    * Considering all aspects of a bug, enhancement, request, question, etc. 
* Leaving a good impression on anyone who comes by. This happens in a number of ways, but a lot of this happened via the points I made above.
* Contributors keep the momentum going. Particularly in updating Chromium versions.
* The Chrome/Chromium userbase is large. The number of people concerned about privacy/security and Google's role in privacy is also decently large. Having a number of people interested in a project like this helps a lot.
* In the beginning (some time before the first spike of users), I went to a few different places to advertise this project. Then, I let other people spread the word. This works because of the number of interested users.

> Regarding the stargazers and star-track (see capture bellow) i see that you gained over 2000 star in just few days and twice on 09/25/2016 and 09/22/2018 it's amazing ! what's the secret ? smiley
> For the stars thins i guess i have the answer the first boom it is from a reddit post and lifehacker article, the second one i think its me joining the team hahhaha just kidding i have no clue for the second one

There was quite a bit of activity from [Hacker News](https://news.ycombinator.com) as well. Especially during the spike in 2018. I believe you can this from GitHub Insights.

> Also one thing, a lot of people asked me about mozilla trademark (Firefox) while i was disturbing a patched version it's curious that uc did not face this problem, i guess google folks are more permissive.

This project is not widely known, and people aren't confusing it with the trademarked Chrome and Chromium. If it becomes an issue, then I'll be fine with changing it.

> Do you have any advice/comments regarding the direction of my project ?

I don't know much about Firefox, so I can't give you any specific advice. Hopefully my comments on what made this project successful will help you too.

Regardless, I am glad that my project has inspired you to create Librefox. I wish you luck with it!

**Comment by intika** [comment]
@Eloston Thank you very much for taking the time to give me your feedback, it's really appreciated :+1:
