### ISSUE TITLE
Update Latest Release version number

### ISSUE THREAD

**Issue by Sk1pp3r** [Eloston/ungoogled-chromium#656]
It seems that chocolatey library https://chocolatey.org/packages/ungoogled-chromium remained at version 67.0.3396.87003, which is marked as latest release now.

https://github.com/Eloston/ungoogled-chromium/releases?after=69.0.3497.92-2

Could you update the Latest Release version number? Thanks.

**Comment by Eloston** [comment]
I don't use GitHub Releases anymore because it's extra manual work with little to no gain. In addition, the refactor (#651) will cease the use of tags on this repository; all tags will be made on the repositories for the individual platforms.

**Comment by lipici** [comment]
sorry to ask in here this but there is a place where i can see the evolution of ungoogled windows version?
i know a while ago was a thread where eloston updated the progress with V and X for version 69 but cant find it .

And second question because i dont understand:
Latest version is 67.0.3396.87-2 ?

**Comment by Eloston** [comment]
@lipici Right now, I don't think there's is anyone working on Windows support., so no issue has been created for it.

**Comment by lipici** [comment]
Thanks for the answer bro. Good luck with your project. I see and feel your passion that you put in because i know how it is to hate /dont like something that invade your privacy. I use windows 8.1 and removed everything from it with  nlite and i downloaded whatsapp from site and didnt logged in google play store.I mean they can have every site that i log into it and every app that i use but to pay me for that. I think is fair. 

    On Thursday, February 21, 2019, 9:25:54 AM GMT+2, Eloston <notifications@github.com> wrote:  
 
 
@lipici Right now, I don't think there's is anyone working on Windows support., so no issue has been created for it.
