### ISSUE TITLE
Why ungoogled-chromium isn't regularly updated?

### ISSUE THREAD

**Issue by LucasAnter** [Eloston/ungoogled-chromium#669]
Latest ungoogled-chromium release is [`71.0.3578.98-2`](https://github.com/Eloston/ungoogled-chromium/releases) while Chromium's latest release is `74.0.3701.0`. Isn ungoogled-chromium already insecure when there isn't latest security patches?

**Comment by Tank-Missile** [comment]
The problem is this is a "hobbyist" project according to @Eloston, and people who do these types of projects tend to have other things going on in their lives. It all comes down to reporting issues, and awaiting responses. If it takes a month, so be it. If I had more knowledge on chromium's source code I would deffiently pitch in, but the most I can do right now is just report issues and wait. If you ask me, the browser is more safe outdated with google integration removed than updated with it.

**Comment by arutr** [comment]
If you look at browser version statistics, Chrome is currently at version 71, so UGC is up-to-date with the mainstream version.

**Comment by Eloston** [comment]
ungoogled-chromium stays with the latest stable version of Chromium. At the time of writing, 72.0.3626.96 is the latest stable version, not 74.

If we had more manpower, then perhaps we could consider keeping up with more unstable versions of Chromium.
