### ISSUE TITLE
Is ungoogled-chromium-bin safe at the AUR?

### ISSUE THREAD

**Issue by LucasAnter** [Eloston/ungoogled-chromium#670]
[ungoogled-chromium-bin](https://aur.archlinux.org/packages/ungoogled-chromium-bin/)

**Comment by Tank-Missile** [comment]
I've been using it for the last several months with no issues. It seems there is an official build for Arch Linux, but the the AUR package doesn't appear to be using it yet. Right now it's downloading the binary from https://cloud.woelkli.com/. According to the user hosting it there, he says you just have to trust him. The best move at this point would be for the packager to change the source URL, since fishy looking links like that may deter people from using it. It's up to you if you want to use it.

**Comment by Eloston** [comment]
If the Arch Linux build is [reproducible](https://reproducible-builds.org/), then we could see if others can build and verify. Otherwise, there's no good way to determine safety.
