### ISSUE TITLE
Not only UnGoogled, but UnCompiled too.

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [Eloston/ungoogled-chromium#686]
Myself and others may be interested in trying this IF there was an installer or compiled version.

I don't use HomeBrew, Python etc. If an app's not ready to use, I don't use it.

I was intrigued when I ran across this Chrome replacement yesterday, but it's evidently for developers and/or power-users only, not the general public. Not even advanced users.

I consider myself more advanced than the average home user, but I don't code, compile or have any desire to use HomeBrew (tried it once).

So for now I'll stick to Chromium as my occasional Safari substitute, and may go ahead and remove Chrome altogether since I don't use it anymore.

**Comment by Eloston** [comment]
> Not only UnGoogled, but **UnCompiled too**
> Myself and others may be interested in trying this IF there was an installer **or compiled version**.

You're sending me mixed messages here...

In all seriousness, links to binaries are available via the README... I suppose the README's still too convoluted for people to see it. I will consider revising again at some point.

> but it's evidently for developers and/or power-users only, not the general public. Not even advanced users.

I'm curious to know what gave you that impression. As I mentioned, downloads are available, so it's not hard to get a build of ungoogled-chromium running. Also, the browser experience is pretty much regular Chromium, so there aren't any difficulties I can see ther either.

**Comment by GitTheHellOutaHere** [comment]
As I recall, I clicked the [Releases](https://github.com/Eloston/ungoogled-chromium/releases) link above and only found source code.

In my experience I've always found the downloads on the **releases** page on GitHub.
Finding no ready-to-run downloads there I didn't look for a second downloads page.

I've no idea what README you're referring to, but 'm guessing the amount of people who actually READTHEM is only marginally higher than those who read EULA's. ;-)

Go ahead and delete this thread.

**Comment by Innomen** [comment]
So where is that readme? Where are the "binaries?" Why aren't they in the releases tab?

**Comment by jstkdng** [comment]
Just go to https://chromium.woolyss.com/ and download, there are zips of ungoogled chromium for windows and mac.

**Comment by Innomen** [comment]
> Just go to https://chromium.woolyss.com/ and download, there are zips of ungoogled chromium for windows and mac.

That's how I got here, looking for the installer for. I don't know what "archive" means in that context and I don't want a portable install and all the hassle that comes with getting the rest of the OS to use the portable version.

**Comment by jstkdng** [comment]
The "archive" is literally just a zip file, download it and extract it, after you open it for a second time chromium will ask you to make it the default browser. It works on mac and linux afaik, in windows you have to edit the registry in order to make it the default (a problem every portable application has).

**Comment by Innomen** [comment]
> The "archive" is literally just a zip file, download it and extract it, after you open it for a second time chromium will ask you to make it the default browser. It works on mac and linux afaik, in windows you have to edit the registry in order to make it the default (a problem every portable application has).

That's why I don't want a portable one man like I said. I want to update my current chrome to this one. Why is there no installer to accomplish this? Oh right because like OP said: "Not only UnGoogled, but UnCompiled too."

**Comment by jstkdng** [comment]
Yes, an installer would be awesome, why don't you try to make one?
oss devs aren't getting paid, including Eloston afaik, you are not entitled to commodity in these types of projects. Try to contribute to the community instead of expecting everything to be spoon fed to you. I'm sure a lot of people will thank you if you create an installer.
Also, don't trust that page for you chromium version, use the about chromium button in the settings.

**Comment by Innomen** [comment]
> Yes, an installer would be awesome, why don't you try to make one?
> oss devs aren't getting paid, including Eloston afaik, you are not entitled to commodity in these types of projects. Try to contribute to the community instead of expecting everything to be spoon fed to you. I'm sure a lot of people will thank you if you create an installer.
> Also, don't trust that page for you chromium version, use the about chromium button in the settings.

Dude you aren't clever. Everyone already knows what and has heard that argument a thousand times.

The problem is threads like this get closed and deleted. That's not just "I don't have time" that's "everything is perfect now go away."

Also yeah I did that too. Contrary to your self serving beliefs, not everyone who scolds you is a fool.

Why don't you stop white knighting and admit the OP was right, this project isn't for people, it's for hobbyist pro techs that like to compile their own everything and scold everyone who wasn't born with a masters in comp sci.

![Screenshot 2019-07-10 13_58_33-Settings - About Chromium - Chromium](https://user-images.githubusercontent.com/134324/60992685-01229980-a31b-11e9-9dbd-ee49c37ab01f.jpg)

Sidenote: I love how you completely ignored the point about why bother with "Googled" chromium.

Work for Google maybe? Wish you did?

**Comment by jstkdng** [comment]
\*sigh\*
Where to begin...
- Why bother with googled chromium?
googled chromium is open source, chrome isn't, some people prefer oss, some people don't. That's it.

- Why is making this easy to adopt so low priority?
Well, why should Eloston care about other platforms? (I'm going to guess stuff rn, might be false) Simply Eloston wanted an ungoogled version of chromium, he did, and because he uses debian, he made binaries for debian and he just left it there. Other people wanted the project on their platforms so they started porting them. It is easy to update ungoogled chromium on other platforms, its only windows, mac, and the bsds where the problem is because simply people haven't cared to port it (and because of the nature of the operating systems). See pic related.
![2019-07-10_13-18](https://user-images.githubusercontent.com/52050345/60994046-4c39ae00-a315-11e9-96db-38a7d431fb1d.png)
It is really easy to update ungoogled chromium in arch linux in this case.
Maybe someone will make an installer for ungoogled chromium for windows, even I've been thinking about doing it since it is hard to make portable programs default, but I just haven't found the time for doing it (yet).
So... in the end, just wait until someone does it or do it yourself. That is how oss works most of the time.

**Comment by Innomen** [comment]
> some people prefer oss, some people don't. That's it.

So it's a fashion thing in your opinion. Actual improved function isn't a consideration? No one has like practical reasons for wanting to avoid closed source? Come on man. You're trying to trivialize the choice to imply no one has any responsibility. You don't even need to do that. Responsibility itself is a choice. 

> Eloston wanted an ungoogled version of chromium

What's the difference between "Googled" chromium and chrome? Why is this guy the only guy that wanted that? Why do all the other projects exist if they are still Googled? What is the point of any "Googled" chromium?

**Comment by jstkdng** [comment]
>You're trying to trivialize the choice to imply no one has any responsibility.

The issue of choice is so complex it is much better to keep it simple stupid. Some people have their reasons to choose oss to propietary, maybe functionality, or philosophy, or just because they have to due to professional reasons. Of course, everyone is responsible for their choices.

Regarding the last part. Eloston wasn't the only one, there are other projects like iridium (which has a nice little installer for windows, though, a bit dated. https://iridiumbrowser.de/downloads/windows) and other ones which I can't remember.

Finally the differences between normal chromium and chrome is that chrome has more integration to the google services than chromium I think. Then why does chromium exist? well, it takes resources to maintain an internet browser with all the features people expect it to have, I think google created chromium to take the load of their hands and let the open source community help maintain it without google having to pay them (lol). You can see that in the case of the edge browser, microsoft couldn't handle maintaning a browser by themselves so now they will use chromium as a base for their next browser.

**Comment by Innomen** [comment]
> I think google created chromium to take the load of their hands and let the open source community help maintain it without google having to pay them (lol).

So this OSS project literally does exist to serve closed source profits. Completely amazing. /smh

Well since the thing doesn't have an installer or updater I just completely nuked everything and started from scratch since I have no other choice.

Whenever I run into situations like this where there are seemingly no ethical tech players with a strong position anywhere in the game I am reminded of the unabomber. Brilliant if crazy guy runs off into the woods because tech dystopian fear, leading to scary thought, which if he had some shred of a point? 

Seems like so few with the ability in the tech space feels any responsibility to anything except themselves. It's like finding out every carpenter happens to also be a libertarian. Seems like a sociology PHD thesis waiting to happen.

**Comment by ThinkChaos** [comment]
> think google created chromium to take the load of their hands and let the open source community help maintain it without google having to pay them (lol)

You need to inform yourself on the history of browsers. Blink, the engine used in Chromium is a fork of Webkit. From the start it has been open source because WebCore the actual rendering part of WebKit is GPL because it is itself a fork of a KDE project.

**Comment by jstkdng** [comment]
>I'm going to guess stuff rn, might be false
oh well, called it, my bad then
