### ISSUE TITLE
It would be nice if the default behaviour for missing URI scheme could be set by a flag

### ISSUE THREAD

**Issue by congma** [Eloston/ungoogled-chromium#694]
**Is your feature request related to a problem? Please describe.**
Currently, when typing an URL in the address bar without an explicit scheme (e.g. `http://`), the default scheme `https://` is prefixed. This is also documented in the README file:

> _These are the non-essential features introduced by ungoogled-chromium._
>
> - Use HTTPS by default when a URL scheme is not provided (e.g. Omnibox, bookmarks, command-line)

I can see the appeal, but also the limitation. Some sites, unfortunately, may fail silently (until timeout) or refuse connection when HTTPS is not available.

**Describe the solution you'd like**
A new setting, for example a flag in `chrome://flags/`, that toggles between HTTP/HTTPS for the missing scheme.

**Describe alternatives you've considered**
- A new command-line option: perhaps not as accessible or explicit as a flag in `chrome://flags/`.
- Leaving the default scheme `http://`: this will unbreak most broken sites but may reduce security.

**Additional context**
[HTTPS Everywhere](https://www.eff.org/https-everywhere), a browser extension curated by the EFF, rewrites HTTP requests to HTTPS if the site matches a ruleset in its database. This extension is useful when the URL defaults to HTTP. Because the rules are curated, this is less likely to trigger broken sites.

**Comment by Eloston** [comment]
This sounds like #688. What version are you running?

**Comment by congma** [comment]
The version is `71.0.3578.98`.

I don't think this is the same as #688 though. This request is about the behaviour triggered when typing an URL by hand without the scheme part.

**Comment by Eloston** [comment]
Ah, I misread your issue. Thanks for clarifying.

Since this is only affecting URLs typed in the Omnibox, I think this is purely a user experience design decision. As @tie argues in #628, having https in the URL bar addresses potential privacy/security issues.

Approximately what proportion of websites do you visit that are affected by this issue? How often do you encounter them?

**Comment by tie** [comment]
Well, it *might be* a limitation if you enter (unvisited) URL and don't know in advance that the content is not served over HTTPS.  Though the same issue persists for HTTPS-only websites when `http://` is default.
And both cases are pretty rare these days:
- [Let's Encrypt Stats](https://letsencrypt.org/stats)
- [Firefox Telemetry for `HTTP_PAGELOAD_IS_SSL`](https://telemetry.mozilla.org/new-pipeline/dist.html#!measure=HTTP_PAGELOAD_IS_SSL)
- [HTTPS encryption on the web — Google Transparency Report](https://transparencyreport.google.com/https/overview)

If you have to type URL more than once regularly (e.g. visiting the website of some local shop or whatever still does not serve HTTPS) then I'd recommend adding `http://` URL to the bookmarks.  Even if you don't want to clutter bookmarks list, as long as the browsing history contains HTTP URL, autocompletion does the trick.

As for [Captive Portals](https://en.wikipedia.org/wiki/Captive_portal) (which are MiTM attack by design, so connection must fail), visiting something like [`http://neverssl.com`](http://neverssl.com) from the bookmarks for initial identification on the network solves the issue.

Let me know your use case if I am missing something, but I don't think that opt-out flag is worth the effort.

>[…]
>If your program is overall very easy to use but security adds complexity, people will work to defeat the security even if it's still reasonably easy to use with the security in place.
>[…]
>The ideal approach is to make security have a negative cost: make it harder to do things the insecure way than the secure one (which would include making insecure impossible).
— [Design for security](https://lwn.net/Articles/777828), comment by [rgmoore](https://lwn.net/Articles/778159)

---

I'd also like to note that there are mechanisms such as [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) that enforce similar policy, but they rely on preloaded lists, require user action or server-side setup and assume that the initial request is made over secure protocol (see [Limitations](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security#Limitations)).  That said, HSTS only benefits from default HTTPS scheme in [ungoogled-chromium](https://github.com/Eloston/ungoogled-chromium).

**Comment by congma** [comment]
Admittedly, my usage pattern isn't very typical. For daily browsing I use Firefox. I use the ungoogled-chromium only temporarily when accessing the sites that I have to use (insurance, some airline companies, for example) but somehow break under Firefox. Those sites are mostly _not_ very well tested in the first place (as you might infer from their non-compatibility with more than one browser), and they don't usually fail or fall back gracefully.

I agree with @tie that for the daily usage cases the default to `https://` schema is more beneficial than inconvenient or problematic. What I was requesting wouldn't change this for the default usage, as `https://` would still be the default of the default scheme ;) The difference is whether this can be modified or not. Does this fit into the goal of ungoogled-chromium? Will this take too much effort if it's to be implemented?

**Comment by Eloston** [comment]
I don't believe this is worth the effort, because flag checking code would need to be added to a number of places; mostly in C++ code, but also a JavaScript file. I'd rather not maintain that much extra complexity for a less common use-case, especially since this doesn't significantly deviate from regular Chromium's behavior.

If this is troublesome enough for you, and you have the resources to do so, you could consider rebuilding the browser without that patch. The browser should work just fine without it.
