### ISSUE TITLE
What are the advantages in privacy of ungoogled-chromium project over Brave browser?

### ISSUE THREAD

**Issue by lluke777** [Eloston/ungoogled-chromium#716]
What are the advantages in privacy of ungoogled-chromium project over Brave browser?

**Comment by Eloston** [comment]
Related: #543

I'm not sure what Brave has done since then, but I can explain what ungoogled-chromium has in terms of privacy.

Because this project is mainly for disabling any sort of web service dependecy, even the most simple requests the browser can make have been disabled. Not only that, but I've found domain substitution to be an effective tool for blocking out any other data leaks that we miss as we upgrade through the Chromium versions (even if they end up being small requests with no private information in the payload). If you are sensitive to all request that comes out, then this is a helpful feature.

However, there are some flags specifically for hindering JavaScript-based fingerprinting. They are listed in [docs/flags.md](https://github.com/Eloston/ungoogled-chromium/blob/master/docs/flags.md) with the prefix `--fingerprinting`.

There may be other small changes in the patches that help as well, but I don't remember them off the top of my head.

Let me know if you have more questions.

**Comment by lluke777** [comment]
OK. Thank you for clarifying.
