### ISSUE TITLE
It says "Update is available"

### ISSUE THREAD

**Issue by furkanmustafa** [Eloston/ungoogled-chromium#721]
**Describe the bug**
My **ungoogled**-chromium (72.0.3626.122-2) has just started to show that an "update is available".

It looks like it even downloaded something, and it's saying "Nearly up to date! Relaunch Chromium to finish updating."

How would that be possible?

**Expected behavior**
My ungoogled-chromium has no way and no place to check for updates.

**Screenshots**
![2019-03-28-161147_42x35_scrot](https://user-images.githubusercontent.com/596741/55137385-2b898600-5174-11e9-86fe-1bfa09bb0c48.png)
![2019-03-28-161157_732x399_scrot](https://user-images.githubusercontent.com/596741/55137391-2d534980-5174-11e9-8ac8-20a2746c2fa8.png)

**Environment (please complete the following information):**
 - OS/Platform and version: Artix Linux (Archlinux based)
 - ungoogled-chromium version: 72.0.3626.122-2

**Additional context**
I'm using portable build, built it myself.

**Comment by Eloston** [comment]
I'm not sure why your browser is doing this. Are you able to run Wireshark to see what traffic is going through?

**Comment by tonowoe** [comment]
Do you have a normal chromium installed also? Or Google Chrome?

**Comment by furkanmustafa** [comment]
Sorry I didn't have time yet to check. Will do.

> Do you have a normal chromium installed also? Or Google Chrome?

Actually yes, I have it. I will check again after removing chromium from system.

**Comment by atelosotaar** [comment]
At the very least I caught it trying to do ipv6 outgoing, but due to this being disabled in my kernel, it would just err on console (I don't have the actual error on hand, will edit when I do).

I've prepared (and applied for me) this patch which should disallow all ipv6 (still waiting for it to trigger, currently):
```diff
--- a/net/socket/socket_posix.cc	2019-08-24 01:52:35.404551016 +0200
+++ b/net/socket/socket_posix.cc	2019-08-24 01:53:27.596545271 +0200
@@ -86,10 +86,14 @@ int SocketPosix::Open(int address_family
          address_family == AF_INET6 ||
          address_family == AF_UNIX);
 
+  if ( AF_INET6 == address_family) {
+    socket_fd_ = -1; errno = EACCES;
+  } else {
   socket_fd_ = CreatePlatformSocket(
       address_family,
       SOCK_STREAM,
       address_family == AF_UNIX ? 0 : IPPROTO_TCP);
+  }
   if (socket_fd_ < 0) {
     PLOG(ERROR) << "CreatePlatformSocket() failed";
     return MapSystemError(errno);
```

No idea what it was trying to do via ipv6 though, sorry.

**Comment by atelosotar** [comment]
disregard [that ^ ](https://github.com/Eloston/ungoogled-chromium/issues/721#issuecomment-524742010) it's not related to the issue as I initially thought. It's in fact [this other issue](https://bugs.chromium.org/p/chromium/issues/detail?id=700347) happens when opening devtools and it's about port 9229. Also happens when fiddling through chrome://inspect/  (mainly `Discover network targets` but not just that)

**Comment by Eloston** [comment]
I actually saw this happen on an installation recently in verison 76. This is likely some behavior we are not catching in our patches.

**Comment by furkanmustafa** [comment]
> I actually saw this happen on an installation recently in verison 76. This is likely some behavior we are not catching in our patches.

Hmm.. I have removed the distro managed chromium package, (and kept my ungoogled-chromium up to date) and it stopped for a while now. But maybe because I am using a recent version (77).

I'm still watching the issue..

**Comment by jlj2** [comment]
The latest supplied Ungoogled-Chromium (UC) Linux Portable binary version, which is three versions ahead of v72 ([75.0.3770.100-1.2](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/linux_portable/64bit/75.0.3770.100-1.2)), also gives similar popups sometimes.

Lately, this occurred with UC in incognito mode and while reading text on a Youtube page and the video playing in either Theater Mode or perhaps Default View (NB:  Are Youtube and Chromium owned by Alphabet/Google?).  All tabs have been closed since then, but here is a screenshot taken during that session showing the tooltip that appeared over the notification icon:
![Screenshot_2019-10-22_01-09-08](https://user-images.githubusercontent.com/17560937/67419544-e3600400-f59a-11e9-89b6-2031868e90b6.png)

When clicking on the icon:

![Screenshot_2019-10-22_01-07-40](https://user-images.githubusercontent.com/17560937/67419702-2fab4400-f59b-11e9-9b42-d42016ef9ff5.png)

When clicking on the 'out of date' message, a popup appears that may look the same as the original notice:

![Screenshot_2019-10-22_01-10-54](https://user-images.githubusercontent.com/17560937/67419745-45b90480-f59b-11e9-8b15-d954cda29d22.png)

NB:  Another issue that should not be resolved here but perhaps may give insight into this one:  lately, this same HP notepad locks up sometimes and the CapsLock key flashes on and off (a kernel panic?) so that I need to reboot, and it has recently happened with UC in incognito mode being the 'only'/'major' app running on my desktop, also on a Youtube page, but I am not sure whether it happened when clicking either on 'Hide chat' or 'Show chat'.

**Comment by ik9999** [comment]
I have the same issue with 76.
![Screenshot from 2019-10-27 19-21-10](https://user-images.githubusercontent.com/6804575/67637779-09650b80-f8ef-11e9-8e88-d07b3565ace6.png)

**Comment by Eloston** [comment]
This issue happened to me yesterday on the latest Debian buster build, `76.0.3809.132-1.buster1`. But as @furkanmustafa mentioned, we should see if this still occurs in 77 or 78.

**Comment by jstkdng** [comment]
I'm on 77 and no message has appeared so far.

**Comment by Eloston** [comment]
If this is still an issue, please let us know.

**Comment by furkanmustafa** [comment]
This just happened again, in a different way this time.

![image](https://user-images.githubusercontent.com/596741/72966069-4878ff00-3e01-11ea-8f61-a69c2943307f.png)

And about page is showing this =>

![image](https://user-images.githubusercontent.com/596741/72966110-67779100-3e01-11ea-8e3e-0a60f111993a.png)

Nearly very scary (and very sneaky).

This time I have verified that I don't have Chrome or Chromium installed.

**Comment by furkanmustafa** [comment]
None of the files in my ungoogled-chromium folder has been changed recently;

```
furkan:~/apps/ungoogled-chromium$ ls -l -ta
total 278068
drwxr-xr-x  5 furkan furkan      4096 Dec 15 01:03 .
drwxr-xr-x 29 furkan furkan      4096 Dec  2 13:30 ..
drwx------  2 furkan furkan      4096 Dec  2 13:27 extensions
-rwxr-xr-x  1 furkan furkan 227728384 Nov  3 17:49 chrome
-rw-r--r--  1 furkan furkan    701056 Nov  3 17:43 v8_context_snapshot.bin
-rwxr-xr-x  1 furkan furkan  15463088 Nov  3 17:22 chromedriver
-rw-r--r--  1 furkan furkan  16344138 Nov  3 16:48 resources.pak
-rw-r--r--  1 furkan furkan   1063740 Nov  3 16:48 chrome_100_percent.pak
-rw-r--r--  1 furkan furkan   1376378 Nov  3 16:48 chrome_200_percent.pak
-rw-r--r--  1 furkan furkan     82118 Nov  3 16:45 natives_blob.bin
drwxr-xr-x  2 furkan furkan      4096 Nov  3 16:40 locales
-rwxr-xr-x  1 furkan furkan    316944 Nov  3 16:17 libEGL.so
-rwxr-xr-x  1 furkan furkan  10789400 Nov  3 16:17 libGLESv2.so
-rwxr-xr-x  1 furkan furkan    301600 Nov  3 16:02 chrome_sandbox
drwxr-xr-x  3 furkan furkan      4096 Nov  3 15:59 resources
-rwxr-xr-x  1 furkan furkan     37394 Nov  1 15:06 xdg-mime
-rwxr-xr-x  1 furkan furkan     33273 Nov  1 15:06 xdg-settings
-rw-r--r--  1 furkan furkan  10426784 Nov  1 15:06 icudtl.dat
-rwxr-xr-x  1 furkan furkan      5087 Nov  1 15:03 chrome-wrapper
-rw-r--r--  1 furkan furkan      2540 Nov  1 15:03 product_logo_48.png
-rw-r--r--  1 furkan furkan      1356 Sep 21 02:48 README
```

If it is saying "the update is ready just restart", where did it download the binary to? (and where from?)
