### ISSUE TITLE
Cannot use with 1Password 7

### ISSUE THREAD

**Issue by alecrobertson13** [Eloston/ungoogled-chromium#731]
**Describe the bug**

1Password7 does not work with ungoogled-chromium. The extension for the browser is installed but the desktop application does not open and so passwords cannot be filled as expected.

**To Reproduce**

Ensure 1Password extension [https://chrome.google.com/webstore/detail/1password-extension-deskt/aomjjhallfgjeglblehebfpbcfeobpgk?hl=en] is installed.

Go to any webpage with a login to fill.

Click the 1Password icon to fill the password.

Observe that the 1Password interface to fill the password, is not working. Although the window is shown, there is no ability to fill the password into the browser, as expected.

**Expected behavior**

1Password 7 [desktop application] opens when called from ungoogled-chromium and passwords can be filled.

**Screenshots**

**Environment (please complete the following information):**
 - OS/Platform and version: macOS 10.14.4
 - ungoogled-chromium version: 72.0.3626.122

**Additional context**

**Comment by hellotanuky** [comment]
https://discussions.agilebits.com/discussion/63557/1password-with-chromium
This is the 1Password's restriction since it cannot be used in any chromium-based browsers except Google Chrome and Opera. Instead, you can
1. use 1Password X with a valid 1Password subscription
2. use old versions of 1Password for Mac since it provides an option to disable code signature check

**Comment by Eloston** [comment]
Thanks @hellotanuky for the info. Closing this as invalid, unless someone has a solution we can implement.
