### ISSUE TITLE
Linux ppc64le port

### ISSUE THREAD

**Issue by leo-lb** [Eloston/ungoogled-chromium#747]
Just FYI;

I'm running a Linux ppc64le port at https://github.com/leo-lb/ungoogled-chromium with the help of patches from https://github.com/leo-lb/chromium_power (which is essentially a fork of https://github.com/shawnanastasio/chromium_power)

Anyone that might need ppc64le support can just use the fork.

Built releases available here: https://github.com/leo-lb/ungoogled-chromium/releases
If you don't trust the builds or they don't work on your platform for some reason, there's a script to build it all in one command. Check the README.md for more information.

I am assuming this project wont integrate changes that are not upstream already, upstreaming ppc64le support is pending but Google is not making this a priority at all so we're waiting.

**Comment by Eloston** [comment]
> I am assuming this project wont integrate changes that are not upstream already, upstreaming ppc64le support is pending but Google is not making this a priority at all so we're waiting.

My main concern with merging these patches into ungoogled-chromium is the compatibility with other CPU architectures. Secondly, I'm reluctant to include massive changes that don't really support the main goals of this project, mainly because of the maintenance required. Additionally, I am reluctant to add the patches as a separate branch, because I don't know how we would deal with the branch. Here are my questions:

* Should we be improving the patches so that compatibility is maintained? If so, how much maintenance effort would this cost?
* Should we leave it as a long-term parallel branch? If so, what happens if other large features start doing this? Would this impact the complexity developers would have to deal with? I have a feeling that the workflow we have with git and GitHub would break down if such branches accumulated over time. So, I think it would be better to have a separate repo altogether.

On that last thought, we could consider forking ungoogled-chromium-portablelinux as a new variant of Portable Linux for ppc64le, and add all the necessary patches there. However, this wouldn't work well if the Portable Linux packaging format is insufficient for all users; e.g. if they want distro-specific packages.

Finally, the simplest solution would be to note the existence of your fork in the README.

What are your thoughts?

**Comment by leo-lb** [comment]
I think that indeed, it would be a good amount of effort for someone to maintain this. @shawnanastasio (primarily) and myself have some familiarity with the port but not many other people do. I'm not asking you to merge this, if you wanted to do it you could, but I think it's a better idea maintenance wise for you to keep it in a fork, and indeed I would very much appreciate if you did mention the fork in your README!

The patches don't modify anything else than things really architecture specific, so compatibility with other architectures would not be broken. It is planned that I work on making RPM and DEB packages for the fork so that will come, when I get more time!

**Comment by leo-lb** [comment]
To clarify, the ppc64le patches are made against chromium git HEAD to ease merging with the main chromium source tree, then I patch ungoogled-chromium (which takes stable releases) with some older patches that were made against HEAD some time in the past (or not, some times patches both work on git HEAD and stable releases, it depends how often chromium does random refactoring of code, adding and remove new lines everywhere not really changing functionality but certainly breaking patches.. ahh.. the joy of patching chromium downstream).

**Comment by madscientist159** [comment]
I'd like to reopen discussion on this, especially in light of the fact that upstream Chromium (by Google design) only supports architectures where there is support for deep low-level DRM / device tracking functionality, and Google has been refusing to accept patches that would enable architectures (such as ppc64el) where this level of control and tracking is absent.

Raptor has been maintaining the ppc64el patchset for a while now, and overall I think the ungoogled chromium and ppc64el port are philosophically well aligned.  We can provide both developer support and hardware in support of a truly tracking-free, modern browser if the project is willing to accept our help?
