### ISSUE TITLE
MacOS binaries - retain compatibility with MacOS 10.9

### ISSUE THREAD

**Issue by cbertelli** [Eloston/ungoogled-chromium#749]
Until some versions ago, installing with macbrew run without problems. Latest versions were not anymore compatible with Mavericks.
Would it be possible to retain compatibility with this old version of MacOS?

**Comment by Eloston** [comment]
I generally don't like to support older platforms that Chromium no longer supports because that increases our maintenance burden (which slows down releases). However, if you manage to create or find some patches that allow us to maintain compatibility, let us know over at ungoogled-software/ungoogled-chromium-macos. Thanks.
