### ISSUE TITLE
Return Windows XP support

### ISSUE THREAD

**Issue by c-sanchez** [Eloston/ungoogled-chromium#75]
Is possible give back the Windows XP support which was stopped by Google from Chrome 50?
It was really unfortunate for many who still use Windows XP (including me)

**Comment by Eloston** [comment]
This will not be a trivial change. The Chrome developers are using Windows API features and libraries that don't work on XP, so all of those will have to change. Also, some technologies used for sandboxing aren't available on XP. You may even need to tweak some compiler settings to make this work too.

If someone wants to do this, go ahead. I don't have to knowledge to do it even if I wanted to.

I'm closing this for now since I don't consider this a feature that many users here will use, much less want to implement. If someone has the knowledge and is willing to take this up, please respond.

**Comment by c-sanchez** [comment]
I understand, really thank you very much for your reply.
