### ISSUE TITLE
FSDG-compatibility

### ISSUE THREAD

**Issue by chaosmonk1** [Eloston/ungoogled-chromium#756]
Hi. As your README notes, ungoogled-chromium is packaged by Guix. However, Guix does more than run the ungoogled Chromium script. From[1]:

> ;; This is a "computed" origin that does the following:
> ;; *) Runs the Ungoogled scripts on a pristine Chromium tarball.
> ;; *) Applies Debians Chromium patches, for their unbundling and GCC work.
> ;; *) Prunes all third_party directories that are not explicitly preserved.
> ;; *) Adjusts "GN" build files such that system libraries are preferred.

"all third_party directories that are not explicitly preserved" refers to a whitelist[2] of third-party files. As I understand it, the reason for removing unnecessary third-party files is to address licensing issues that otherwise make Chromium-derivatives incompatible with the Free System Distribution Guidelines.[3] See also here.[4]

Would you consider using Guix's whitelist (potentially adding other third-party files deemed important as long as they are clearly under a free license) and either
(a) removing all non-whitelisted third-party files so that ungoogled-chromium is FSDG-compatible (preferable) or
(b) creating another ungoogled-chromium-* distribution called something like "ungoogled-chromium-fsdg" or "freed-chromium" which removes all non-whitelisted third-part files?

Either solution would it easier for FSDG distros to package ungoogled-chromium without having to redo Guix's work and make ungoogled-chromium more appealing to users with concerns about freedom issues.

Thanks.

[1] https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/chromium.scm
[2] https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/chromium.scm#n72
[3] https://www.gnu.org/distros/free-system-distribution-guidelines.html
[4] https://bugs.chromium.org/p/chromium/issues/detail_ezt?id=28291

**Comment by qvint** [comment]
> As I understand it, the reason for removing unnecessary third-party files is to address licensing issues 

Distribution maintainers do that in order to use as much system libraries as possible.[1] If a `*/third_party/*` directory cannot be unbundled for some reasons, it is white-listed. I know that `third_party/unrar` includes non-free code,[2] but I don't think there are any licensing issues with the other third_party dirs...

> Would you consider using Guix's whitelist

I believe this work should be done in the existing ungoogled-chromium-* repos because it's a distro-specific thing. An example from the Fedora world: it is impossible to prune `third_party/harfbuzz-ng` in Fedora 29, because Chromium requires harfbuzz >= 2 while Fedora 29 repos provide only harfbuzz = 1.[3]

[1] https://chromium.googlesource.com/chromium/src/+/refs/heads/master/build/linux/unbundle/README
[2] http://bugs.debian.org/914487
[3] https://pkgs.rpmfusion.org/cgit/free/chromium-vaapi.git/tree/chromium-vaapi.spec?id=4bbccf833de3c6afd7cd057a168294f792d5f12e#n20

**Comment by Eloston** [comment]
@chaosmonk1 I agree with @qvint. It's hard to make a repo that would be generically applicable to all distributions due to a number of issues (versions, availability, perhaps even certain build configurations). The best we could do is add some resources people could use to the Wiki. In addition, this issue of non-free libraries is more of an issue with Linux or BSD distros. For these kinds of platforms, it is more likely that they have already solved this issue if they package Chromium or some variant thereof.

**Comment by emanruse** [comment]
AFAICS @chaosmonk1 is raising an issue with "freedom" in the sense that the software should be not only open source but also properly licensed, so that it complies with the FOSS ideology (the 4 freedoms). 

Many (perhaps most) distros also pack binary blobs for kernel stuff as well as other non-free software. So it is not likely at all that they have solved all the freedom issues with the software they pack. On the contrary.

The few "libre" distros which are supposedly 100% free software and endorsed by FSF seem to avoid packing Chromium at all - exactly because of its (as it seems) not so clear licensing. So if I understand correctly this is a call for fixing this so that ungoogled-chromium (uncloudium) would fit any distro ("libre" or not) with no potential licensing issues whatsoever. It is very unlikely that Google will work on this (upstream), so perhaps this fork of Chromium may become the first 100% "free software" (as per FSF's definitions).

I don't know if this is a freetardism[1] but it may be worth to consider it, even for (yet another) legal protection of the software.

[1] https://digdeeper.neocities.org/ghost/freetardism.html

**Comment by Eloston** [comment]
@emanruse It is enticing to strive for 100% free software, but I don't think it's realistic for uncloudium as a whole. However, I see no reason why this can't be implemented on a per-distro basis.

**Comment by emanruse** [comment]
@Eloston

A per-distro basis doesn't protect you or the project legally.

AFAIK anything without explicit free license is considered copyrighted by default and hence an "intellectual property" of the owner. In other words only the owner (Google) has the right to distribute/change the files which (although open source) don't have a license that explicitly permits anything else. So if at some point in time Google decides to sue you (and any other developer) for using/modifying/distributing their code without explicit permission you will be in trouble.

So even for your own personal protection I would recommend you pay serious attention to the the legal side of things, even if that requires consulting a lawyer.

**Comment by chaosmonk1** [comment]
@emanruse
> AFAICS @chaosmonk1 is raising an issue with "freedom" in the sense that the software should be not only open source but also properly licensed, so that it complies with the FOSS ideology (the 4 freedoms).

> So if I understand correctly this is a call for fixing this so that ungoogled-chromium (uncloudium) would fit any distro ("libre" or not) with no potential licensing issues whatsoever. It is very unlikely that Google will work on this (upstream), so perhaps this fork of Chromium may become the first 100% "free software" (as per FSF's definitions).

Yes, it is the licensing, not packaging, of Chromium derivatives that I'm concerned with. See[1][2][3] for examples of potential licensing issues.

Out of the Chromium derivatives I'm aware of, ungoogled-chromium seems to have gone the furthest in terms of user privacy, which is why I thought I'd see if there's interest in going a step further and becoming 100% free software as well.

@emanruse
> AFAIK anything without explicit free license is considered copyrighted by default and hence an "intellectual property" of the owner.

Yes, IIUC anything without an explicit free license is not legal to redistribute. It seems that this has not been enforced so far. I'm not sure whether or not it will in the future, but it's something to consider.

@Eloston
> However, I see no reason why this can't be implemented on a per-distro basis.

That's true. It would result in some redundant labor that would not benefit upstream users, but a fully free and privacy-respecting browser can be made available downstream by building on the excellent and valuable work you're already doing.

I thought I'd bring these potential issues to your attention in case you'd like to consider them. Either way, thank you for and keep up the great work!

[1] https://bugs.chromium.org/p/chromium/issues/detail_ezt?id=28291
[2] https://directory.fsf.org/wiki/Talk:Iridium_Browser
[3] https://github.com/iridium-browser/tracker/issues/93

**Comment by chaosmonk1** [comment]
Btw, I see this project referred to as "uncloudium" in this thread. Is that going to become the official name of this project? If so, I think it's a fine name and a good measure to avoid potential trademark issues down the road.

**Comment by Eloston** [comment]
@emanruse @chaosmonk1 

> AFAIK anything without explicit free license is considered copyrighted by default and hence an "intellectual property" of the owner.
> 
> Yes, IIUC anything without an explicit free license is not legal to redistribute. It seems that this has not been enforced so far. I'm not sure whether or not it will in the future, but it's something to consider.

Debian and Ubuntu seem to have worked out licensing pretty well. I don't think there are any patches that touch any code that is in a legal grey area (i.e. all code falls under what Debian and Ubuntu consider to be under the BSD license). Or, do you guys think that Debian and Ubuntu also have licensing issues with their Chromium packages?

> Btw, I see this project referred to as "uncloudium" in this thread. Is that going to become the official name of this project? If so, I think it's a fine name and a good measure to avoid potential trademark issues down the road.

This was going to become the name at one point, until #759.

**Comment by chaosmonk1** [comment]
@eloston
> do you guys think that Debian and Ubuntu also have licensing issues
> with their Chromium packages?

I'm not sure. It depends on whether or not any of the information
here[1][2][3] is accurate. If the information turns out to be wrong or
out-of-date, then everything's fine. Otherwise, if Debian does not
address these issues directly or indirectly, then yes, it seems that
Debian and Ubuntu would be affected as well.

[1] https://bugs.chromium.org/p/chromium/issues/detail_ezt?id=28291
[2] https://directory.fsf.org/wiki/Talk:Iridium_Browser
[3] https://github.com/iridium-browser/tracker/issues/93
