### ISSUE TITLE
Is there a way to update the browser?

### ISSUE THREAD

**Issue by lirmwing** [Eloston/ungoogled-chromium#777]
I'm not sure if it's listed anywhere, but is there a way to update ungoogled-chromium to a latest version for the sake of security updates, prevention of backdoors, or updates against security flaws? I should also ask: how often is the code updated for this stuff? 
Please take your time w/ responding.

**Comment by Eloston** [comment]
The main code (i.e. this repo) is updated relatively quickly now to the latest stable Chromium thanks to the work of generous contributors. However, the rate that the platform repos are updated varies; some platforms like Arch are updated very quickly, whereas platforms like Debian and Portable Linux are slower. You should follow the commit history and tags to get a sense of what that's like.

Let me know if you have more questions.

**Comment by Eloston** [comment]
There's no official updater for ungoogled-chromium, however. There are some third-party updaters that can do it (like chrlauncher I believe?).

**Comment by lirmwing** [comment]
I tried to install chrlauncher, and my antivirus picked it up as a trojan. What other updaters are out there that I could use?

**Comment by lirmwing** [comment]
How do I configure `chrlauncher.ini` then to update ungoogled-chr?

**Comment by Eloston** [comment]
I don't know, I've never used it. You should ask the developers of chrlauncher

**Comment by claudiodekker** [comment]
Since this appears to be a common and recurring issue (arguably for good reason), I figured I'd try to partially address it by creating **a Chromium extension that automatically checks for new Chromium updates in-line with your preferences**.

Its functionality resembles that of NeverDecaf's "Chromium Web Store" extension: It displays a badge indicating available updates and, when interacted with, provides a concise overview of all available updates, allowing you to directly download newer build versions, jump to the release page, copy hashes and more. Essentially, it serves as the closest thing to an automated updater mechanism, without one being built-in.

You can find it here: https://github.com/claudiodekker/chromium-update-notifier

**Comment by PF4Public** [comment]
@claudiodekker Are you also checking whether updates for a browser available? (which is what requested here, not extensions!)

**Comment by claudiodekker** [comment]
@PF4Public Yes, that's exactly what it's doing. It only checks for browser updates.
