### ISSUE TITLE
Add Qwant to default search engines

### ISSUE THREAD

**Issue by theel0ja** [Eloston/ungoogled-chromium#790]
I think Qwant search engine should be added

https://help.qwant.com/help/qwant-search/add-qwant-on-desktop/on-chrome/#default_search_engine

**Comment by csagan5** [comment]
For reference: https://github.com/bromite/bromite/blob/78.0.3904.72/build/patches/Add-Qwant-search-engine.patch

**Comment by lipici** [comment]
i dont understand how qwant isnt there by default instead of searcx

i tried searcx and its like you're using  no search , its enought to missspel a letter and you wont get any results or if you search something not popular you get the same, no result.
i respect the work of searcx and initiative, but its the reason people go to google search engine, not having a good and working product even if privacy is at stake.

**Comment by PF4Public** [comment]
Considering that to date even bromite had removed qwant search engine, closing this issue.
