### ISSUE TITLE
No video playback. At all.

### ISSUE THREAD

**Issue by quantizzed** [Eloston/ungoogled-chromium#796]
Hi!

I've just successfully built and installed the latest version (75.0.3770.100) on Manjaro Linux. Browsing works, extensions, too... but no video playback, at all, on any website. I just get a black box in place of a video with an infinite loader animation.

Firefox on the same system works well, so it's probably not codecs or hardware issue.

Where should I start unfolding and debugging this, to locate the cause, at least?

**Comment by jstkdng** [comment]
I also have this problem in my laptop with intel graphics, no video playback, just an infinite loading screen, but I recognized that it would work only on certain codecs, vp9 would not work whilst vc1 did, so I just disabled hardware video acceleration on chrome://flags and video playback just started working again.
Just go to chrome://flags/#disable-accelerated-video-decode and change it to enabled and restart the browser, it should be working now.
If you ask why this doesn't happen on firefox its because firefox has no hardware video acceleration at all.
Another interesting thing is that mpv DOES work with the vp9 codec, so maybe mesa was updated and some api was change and chromium hasn't updated yet.

**Comment by Eloston** [comment]
Which binary are you using? Portable Linux doesn't use VA-API, so you could use that for now.

**Comment by quantizzed** [comment]
> Which binary are you using? Portable Linux doesn't use VA-API, so you could use that for now.

I'm using the binary that I've compiled myself on my machine.

**Comment by quantizzed** [comment]
> I also have this problem in my laptop with intel graphics, no video playback, just an infinite loading screen, but I recognized that it would work only on certain codecs, vp9 would not work whilst vc1 did, so I just disabled hardware video acceleration on chrome://flags and video playback just started working again.
> Just go to chrome://flags/#disable-accelerated-video-decode, switch it to enabled and restart the browser, that should fix it.

Thank you very much, your solution worked like a charm. Mine is also a laptop with Intel graphics... 

> If you ask why this doesn't happen on firefox its because firefox has no hardware video acceleration at all. Another interesting thing is that mpv DOES work with the vp9 codec, so maybe mesa was updated and some api was changed and chromium hasn't updated yet.

It's a pity, because Chromium's video playback performance was like an order of magnitude better than Firefox's...

**Comment by jstkdng** [comment]
@quantizzed 
hello, managed to combine the vaapi patches from chromium-vaapi which fixes hardware acceleration, you can get the pkgbuild from my repo: 
https://git.vin.ovh/jk/ungoogled-chromium-archlinux
Just finished compiling and it works like a charm on both my kabylake laptop and on my nvidia desktop

**Comment by quantizzed** [comment]
@jstkdng 
Great, thanks!
Are you planning to merge these patches with the upstream code in this repository?

**Comment by jstkdng** [comment]
@quantizzed 
I would, but I don't like github.
