### ISSUE TITLE
Ungoogled-Electron?

### ISSUE THREAD

**Issue by esotericDisciple** [Eloston/ungoogled-chromium#797]
**Is your feature request related to a problem? Please describe.**
wonderunit/storyboarder is using Electron for their app, as do tons of other AppImage-binaries, I didn't realize how chromium-dependent Electron is until the latest version of storyboarder refused to run unless --no-sandbox was supplied. Now I'm suspicious of how privacy-unsafe Election might actually be under the hood...
**Describe the solution you'd like**
...However, if you released your own version of Election based off of your ungoogled-chromium, I'd trust any app that was built based off of it... 
**Describe alternatives you've considered**
...I could always use TV Paint, but I only have a student license for it. And Blender locked it's 2.8 API before thumbnail preview/seek support could be added to the NLA for greasepencil themes...
**Additional context**
...Thanks in advance?

**Comment by jstkdng** [comment]
Have you tested if electron phones home? AFAIK, electron is just a stripped down version of chromium and it shouldn't have any google integration.
Same with qutebrowser, it uses something like electron(qt webengine) but for C++ and it doesn't phone home.

**Comment by jstkdng** [comment]
Another thing is that electron has its own patched chromium source tree, and just porting all the ug patches to the electron source tree would be a pain in the ass not a lot of people would be willing to do.
Also, even if ungoogled electron existed, many applications would just not use it, especially if it is closed source, like discord, any just trying to replace the binaries would be a impossible since electron just combines chromium and all the sources, then creates one binary.
And even if the app is open source, you would have to ask the original developer to start using ungoogled electron in their builds, but I'm pretty sure they wouldn't, and, well, you'll have to build your ungoogled versions yourself.

**Comment by esotericDisciple** [comment]
Ah...How do I do a "phone home" test?

**Comment by mbakke** [comment]
1. Close all programs on your computer that have network connections.
2. Start Wireshark or tcpdump on your network interface (you'll find good guides on the interwebs).
3. Wait for all your previous connections to time out.
4. After a while, all you should see is "chatter" from the local network at a predictable rate.
5. Start the application. Does it cause a spike in network packets? What are the destination addresses?

**Comment by esotericDisciple** [comment]
Okay I just followed your tutorial, and, using wireshark, found that upon running Storyboarder both google-analytics and doubleclick turned up. github and amazonaws were also showing, as well as wonderunit.com (the app maker's website). Though this may be because of Storyboarder being like an app that could be run in a browser (ie, a website like any other), and as such is causing these phone home signals, not Electron itself. I don't know how to test Electron directly because I don't know if running Electron is the same as running an app built with Electron...

**Comment by Eloston** [comment]
Closing since this doesn't seem to be necessary.

**Comment by Flashwalker** [comment]
> Ah...How do I do a "phone home" test?

Just use something like Portmaster firewall.  
It will prompt then app want to go outside.

**Comment by Flashwalker** [comment]
> ...Also, even if ungoogled electron existed, many applications would just not use it, especially if it is closed source, like discord, any just trying to replace the binaries would be a impossible since electron just combines chromium and all the sources, then creates one binary. And even if the app is open source, you would have to ask the original developer to start using ungoogled electron in their builds, but I'm pretty sure they wouldn't, and, well, you'll have to build your ungoogled versions yourself.

But we can use it with Nativefier to run webapps

**Comment by Flashwalker** [comment]
Here is an alternative https://github.com/castlabs/electron-releases

**Comment by PF4Public** [comment]
In case anyone interested, like I've mentioned in https://github.com/ungoogled-software/ungoogled-chromium-wiki/issues/19#issuecomment-1143784496, ungoogled electron (well, sort of) is available in my overlay for Gentoo since Nov 26, 2021 and I'm using it ever since. Though, I didn't test whether electron is phoning home or not.
