### ISSUE TITLE
What do you expect?

### ISSUE THREAD

**Issue by yasindce786** [Eloston/ungoogled-chromium#80]
In googled......\\\\^^^

**Comment by Eloston** [comment]
?

**Comment by mimf** [comment]
I think he means the current name of this project is a bit dangerous. Google can shut it down easily I suppose?

Since this has been getting so much attention now, I suggest a name change.

**Comment by Eloston** [comment]
> I think he means the current name of this project is a bit dangerous. Google can shut it down easily I suppose?

No, they can't. I'm not violating any software licenses as far as I can tell.

> Since this has been getting so much attention now, I suggest a name change.

What do you suggest?

**Comment by reclaimer** [comment]
Any other metals, perhaps? Would be nice to say this is browser `X`, so it doesn't confuse anyone (Chromium makes you think of Google Chrome).

**Comment by ajkblue** [comment]
I would say keep the name just as it is now, "ungoogled-chromium" tells me everything I need to know about the browser, basically "Chromium without Google", and that's exactly what I want. I also believe it's the simplest to understand and comes across more trustworthy than a name like "Iron" or "Epic Privacy Browser". Names like those make me think of the other chromium-based browsers that have pretty bad security reputations (see the [Web Browsing section from the OS X Security and Privacy Guide] ( https://github.com/drduh/OS-X-Security-and-Privacy-Guide/blob/master/README.md#web-browsing) which states "Many Chromium-derived browsers are not recommended. They are usually closed source, poorly maintained, have bugs, and make dubious claims to protect privacy.") The majority of people that would even use this understand the difference between Chrome and Chromium, the latter being the open source version and therefore the more trusted of the two.

**Comment by Eloston** [comment]
@ajkblue You have solid reasoning. I also like the fact that the name tells users what to expect from the project, but I didn't have any good reasons to keep it until now. Thanks.

I'm closing this for now since @yasindce786 isn't clarifying the original question, and all of the questions in here are answered.

**Comment by sahal2080** [comment]
@Eloston I know you closed this but I think there's merit to a name change
- *Ungoogled* is very antagonistic. Though it might draw the privacy oriented person, it might drive away many non-techie people who would see this as "hackers crazy stuff"
- Current name might draw the attention of Goliath and unnecessary troubles that would just make life harder for a resource-limited project

Imho, since your point was made already with the name as is, renaming into a distinct brand sometime soon wouldn't hurt (I believe it'll help!). This is especially if you involve the community in name/logo design and selection and the like. The message as @ajkblue wouldn't be lost if it was renamed to something like _Pure Chromium_, _Clean Chromium_, _Chromium Liberated_, etc. You can just look at [thesaurus](http://www.thesaurus.com/browse/clean) for more inspiration.

**Comment by Eloston** [comment]
@sahal2080 

> Ungoogled is very antagonistic.

I can't see what you mean here. I see it as a neutral term. Let me make an analogy: Are you saying that undoing something or unearthing something from the ground is antagonistic?

> it might drive away many non-techie people who would see this as "hackers crazy stuff"

Really? I'm sure everyone recognizes "google", and when you *un-* something, it usually means to remove that thing. Sure the non-technically inclined users won't understand how or why, but the correct idea is conveyed.

> Current name might draw the attention of Goliath and unnecessary troubles that would just make life harder for a resource-limited project

Well I tried looking up Goliath, and I still can't figure out what you mean. Could you re-explain with different kinds of words?

> if you involve the community in name/logo design and selection and the like

Do you mean tell people to create a name/logo? I already let people contribute whatever ideas through issues.

> The message as @ajkblue wouldn't be lost if it was renamed to something like Pure Chromium, Clean Chromium, Chromium Liberated,

I think some of it will be lost. Consider this quote from @ajkblue:

> "ungoogled-chromium" tells me everything I need to know about the browser, basically "Chromium without Google"

The names you proposed are pretty generic; they can mean a lot of different things to different people. ungoogled-chromium is relatively specific.
