### ISSUE TITLE
[RFC] Third-party cookies situation

### ISSUE THREAD

**Issue by PF4Public** [Eloston/ungoogled-chromium#804]
Presently it is not an issue or a bug per se, but a request for a comment.

Imagine a very popular and very intrusive website. Let's call it `9oo91e.c0m`. Next imagine a second not so popular website, let's call it `example.com`.

Now imagine that all cookies are blocked. Both websites work fine, but lacking some functionality. For example `9oo91e.c0m/m4p5` is unable to calculate a route or something. 

Let's enable all cookies (overall or only for a session — doesn't matter), but block third-party ones. Both websites are happy with cookies and `9oo91e.c0m` cannot creep its own cookies through `example.com` because third party cookies are blocked.

Now let's try to disable cookies and selectively allow `example.com` to set cookies. `9oo91e.c0m` cookies are not creeping through `example.com`, but `9oo91e.c0m/m4p5` is still broken. Should we now allow `9oo91e.c0m` to set cookies and all hell broke loose. Not only `9oo91e.c0m/m4p5` is setting cookies, but also `example.com` is happily setting `9oo91e.c0m` cookies!

My questions here are: 

Is this by design?

Is it the way it is handled by chromium itself?

Is it possible to block all cookies, selectively unblock specific cookies, but keep blocking third-party ones no matter what?

**Comment by jstkdng** [comment]
That is how all browsers handle cookies afaik.
You could allow all cookies but delete them after you close the tab.
![image](https://user-images.githubusercontent.com/52050345/61919246-5913ef80-af1a-11e9-9e24-f8135aa8d660.png)
Install Cookie AutoDelete from the store and you will be able to just keep the cookies you want. Pic related, I have CookieAutoDelete configured so that I only have the facebook cookies that let me have an active session, the other ones are deleted after I close all facebook tabs.

**Comment by PF4Public** [comment]
@jstkdng Thanks for pointing this extension out! I'll give it a try.

By the look of cookies configuration settings page I was under the impression, that third-party cookies settings work independently from other settings. See the screenshot:
![image](https://user-images.githubusercontent.com/10319700/61970894-6a2a3280-afe6-11e9-9d5a-6ae4114d2309.png)
Am I wrong?

**Comment by jstkdng** [comment]
Your settings page is different from mine lol
![image](https://user-images.githubusercontent.com/52050345/61974948-65955800-afad-11e9-932e-aaec5ced2b33.png)
What is your platform and version of chromium?
And afaik third party cookies are still cookies. So, if you block all cookies, that includes third party cookies.
They have an option to just block them since if you block them they tend not to break some pages, some do break of course, like amazon aws.

**Comment by PF4Public** [comment]
>What is your platform and version of chromium?

It's Gentoo and Chromium: Version 72.0.3626.122 (Official Build) (64-bit)
You might be having a more recent version, right?

>And afaik third party cookies are still cookies. So, if you block all cookies, that includes third party cookies.

Sure, but this third-party toggle isn't disabled when all cookies are disabled, which makes an impression of a separate and independent setting!

**Comment by jstkdng** [comment]
>Sure, but this third-party toggle isn't disabled when all cookies are disabled, which makes an impression of a separate and independent setting!

well, that just seems like laziness to me from the chromium developers. You could try to open an issue in their issue tracker.

**Comment by Eloston** [comment]
The extension Cookie AutoDelete seems to be sufficient. Closing.
