### ISSUE TITLE
Differences to KDE's Falkon

### ISSUE THREAD

**Issue by maverick74** [Eloston/ungoogled-chromium#829]
Beside being based on qtwebEngine and not supporting webextensions, isn't Falkon sort of an ungoogled Chromium as well?

What differentiates ungoogled-chromium from Falkon in terms of privacy and features?

**Comment by Eloston** [comment]
I haven't heard about KDE's Falkon, and my knowledge of Qt's WebEngine is superficial. All I know is that Qt WebEngine just wraps around Blink and maybe V8, but that's about it.

In terms of privacy, ungoogled-chromium has some "extra" features like toggleable fingerprinting deception, among a lot of smaller changes to prevent the Chromium's browser chrome (i.e. all user-facing features) from communicating with Google.

In terms of features, ungoogled-chromium doesn't really add anything major. There are a number of tweaks here and there, for which you should see the README for more details. Otherwise, the remaining features are really the differences between Chrome/Chromium vs Falkon in the browser chrome. For example, does Falkon support the following?:

* A lot of GPU acceleration (see `chrome://gpu`. There's definitely more than what's listed, and I don't know hwo much is included in Qt WebEngine)
* Extensions, which give access to powerful third-party tools in Chromium and Firefox
* Fast upgrades when there are security vulnerabilities anywhere in the browser stack (i.e. Blink/V8 all the way to the browser chrome)
* DevTools-like feature
* Search and navigation bar like the Omnibox
* State-of-the-art development practices and optimization work via static-analysis tooling and testing infrastructure (ungoogled-chromium borrows this work from Chromium)
* Browser automation, such as via Selenium (though one could use Electron or NodeJS)
* WebAssembly
* WebRTC
* Autofill
* Printing
* Multiple languages for the UI

There are also many smaller features that I'm probably missing, but these are the main ones I can think off the top of my head.

**Comment by maverick74** [comment]
@Eloston i can only answer a few of your questions:

Falkon does have:

- Search and navigation bar like the Omnibox
- Autofill
- Printing (at least it from what i understand of it)

And it certainly does not have:

- Fast upgrades when there are security vulnerabilities anywhere in the browser stack 

The rest, either i'm not sure or i don't know about.

This is not a which is better question... it was more of a way for me to understand the differences because, as i see it, Falkon is also Ungoogled. 
However from what we can see they also removed other parts of the browser that could be important, that you have kept...

Have you ever considered renaming your project to something more "catchy" and try to bring in more attention to it?

Many people are searching for a no-spy-chrome!!!

**Comment by Eloston** [comment]
> This is not a which is better question... it was more of a way for me to understand the differences because, as i see it, Falkon is also Ungoogled.

You asked for the differences in terms of "privacy and features" between Falkon and ungoogled-chromium. Because ungoogled-chromium is almost Google Chromium, I included those features from Chromium in the comparison.

I think the better question to ask are the differences between Falkon and Chromium, because Falkon needs to basically replicate everything that Chromium has, except the business incentives (hopefully).

**Comment by Eloston** [comment]
> However from what we can see they also removed other parts of the browser that could be important, that you have kept...

Falkon didn't remove what's important, Qt WebEngine did because Qt WebEngine's purpose is not to be a full-fleged browser.

> Have you ever considered renaming your project to something more "catchy" and try to bring in more attention to it?

#759, and make sure to read https://github.com/Eloston/ungoogled-chromium/issues/759#issuecomment-493640088. You ignore most of the issue because it does not discuss what is actually blocking us from choosing a "better" name; what's blocking us is the process by which to choose a name. We currently think a vote is the best way to decide, but we don't have the means to execute a fair vote; see the issues if you want more context.

**Comment by maverick74** [comment]
Ui... I just wrote it out of thin air and did not searched for a bug on it (sorry - lack of time).

That seems a pretty hot discussion!!! I think I'll leave that to you guys!!! But I do agree that the project - and specially the developer - should be taken into account and protected.

Developer protection against legal problems should have the top attention. It can cause a very great deal of headaches (and google ain't playing around!!!)

Thank you for all your time and clarifications, by the way!!! They helped a lot :)

**Comment by Eloston** [comment]
Closing because question is resolved.

**Comment by didlie** [comment]
@maverick74 are you still active? I noticed your research activity in the search engine space. Please email me at arvinsmail@gmail.com
