### ISSUE TITLE
FR: Add two convenience buttons to extensions page

### ISSUE THREAD

**Issue by sixtyfive** [Eloston/ungoogled-chromium#83]
Downloading manually and then drag-and-dropping the `crx` file works just fine, of course, but is a little inconvenient. I suggest two buttons, one named _"Install from file"_, the other named _"Install via id"_ in the extensions page. Perhaps the link named "Download more extensions" could be renamed to read _"Find more extensions at the Google Chrome Web Store"_ to make it clear who the site you're about to click a link to is owned by.

**Comment by Eloston** [comment]
I like your "*Install from file*" button idea. Though I don't know where in the code that extensions are installed, so I'll have to do some digging around.

Though how would "*Install via id*" work? Would that attempt to install an extension from the Web Store?

BTW, the "Download more extensions" link doesn't work because of domain substitution. The Web Store doesn't work because of other patches.

**Comment by sixtyfive** [comment]
Perhaps you can identify the point in the code where it starts the installation by searching for things related to drag-and-drop? Even though I guess the browser does a lot of other drag-and-drop as well.

As for the _"Install via id"_ button, I was thinking:

1. User enters id (as found in the appstore or sent by someone else like @stfnhrrs did in another ticket) in a text input field and clicks the button next to it.
2. Browser inserts the id into the URL found at https://github.com/Eloston/ungoogled-chromium/blob/master/FAQ.md#can-i-install-extensions-from-the-chrome-webstore
3. Browser opens that URL in the background trying to download a `.crx` file from there, e.g. to `/tmp/extension-foi4ntjrnk2kjjew.crx`
4. Browser tries to install that file the same way it would if the _"Install from file"_ button had been clicked

That might be over-complicated or nonsensical. You know the code and might have a better idea.

As for the "Download more extensions" link: shouldn't it be possible to visit a Google domain if the user explicitly requests the browser to do so? As for the web store not working, I personally don't care. Perhaps it's a good thing it doesn't work, because that requires you to think a little more about whether you really need an extension...

**Comment by Eloston** [comment]
> Perhaps you can identify the point in the code where it starts the installation by searching for things related to drag-and-drop? Even though I guess the browser does a lot of other drag-and-drop as well.

Yeah that's what I was thinking, but I also need to figure out how to add the button and bring up a dialog button. I don't expect it to be too difficult, but it will take some time.

> As for the "Install via id" button, I was thinking:

I guess I could implement something like that. But there are already external programs that can download the crx file for you; all you would need to do is use Install from file. I thought that many users of ungoogled-chromium would rather get the extension from the developer's GitHub page instead of getting it from the Web Store, but I'm not sure.

> As for the "Download more extensions" link: shouldn't it be possible to visit a Google domain if the user explicitly requests the browser to do so?

That's true, but I don't have a system in place to exclude domain substitution on parts of a file. Considering the Web Store doesn't work for installing extensions, its use is kind of limited.

**Comment by sixtyfive** [comment]
Sounds awesome! I'll remain subscribed! :smile: 

I didn't think of there being any other place than Google's store to get crx files from. It's a good point. A more sophisticated solution might be to try and parse a _URL_ given by the user. I.e. figure out whether it's a web store address or a GitHub address or whatever. But that'd need too much work I guess. Just a thought.

> That's true, but I don't have a system in place to exclude domain substitution on parts of a file. Considering the Web Store doesn't work for installing extensions, its use is kind of limited.

How about just removing it (and other things that don't work) then?

**Comment by Eloston** [comment]
> How about just removing it (and other things that don't work) then?

I could, but that would be more patches to maintain. It doesn't confuse the user too much, and no one's really complained about them.

**Comment by sixtyfive** [comment]
Just out of curiosity: isn't the tool used to apply patches sort-of smart about where to apply them? Such a string seems like a very easy thing to track automatically and remove from wherever it is...

**Comment by Eloston** [comment]
Yes it is, but not all users use domain substitution. So those patches would fail to apply. Right now there's no system in place to include additional patches when domain substitution is used.

**Comment by Eloston** [comment]
Some extension conveniences were added or noted in 63. If those aren't satisfactory, let me know here.
