### ISSUE TITLE
no condition to compile & and hard to trust the bin

### ISSUE THREAD

**Issue by playgithub** [Eloston/ungoogled-chromium#846]
Google is block by the government.
Using VPN/SS/VPS to download so many stuff is very slow and at risk of blocking,
and a lot of money for a fast proxy.
Still it's somehow hard to trust the third party pre-built binaries. BTW, using AUR.
Any help?
Thanks

**Comment by jstkdng** [comment]
there is literally no way to prove a pre-built isn't compromised, only thing left is to trust the packager, or to compile it yourself.
You could try to setup my repo if that somehow reduces your paranoia.
https://github.com/jstkdng/ungoogled-chromium-archlinux

**Comment by Eloston** [comment]
@playgithub All you need to know is documented:

* If you want source code and GitHub is blocked: https://github.com/Eloston/ungoogled-chromium#mirrors. However, you will still need access to Google to download the Chromium source code.
* Regarding trust of pre-built binaries: See the section right after the download pages link (or the top of the downloads website): https://github.com/Eloston/ungoogled-chromium#downloads. The solution to decentralized trust of binaries is *reproducibility*, because then anyone can build it and verify that the binaries are the same byte-by-byte (in fact, all decentralized systems have this property of "reproducibility". Take blockchain for example). We aren't guaranteeing reproducibility yet, but it should be close.

If you have a sufficiently powerful computer, you can build the browser from source.

**Comment by Eloston** [comment]
Also, there isn't much we can do about the Chromium source code downloading, unless someone re-uploads them to a server that we can all access.

**Comment by jstkdng** [comment]
@Eloston 
even then you are still required to compile the resulting package and check if its all good, and even then the binary could still be compromised, like what happened to transmission.
And under arch you can point to sources using the file:// handle instead of an url, then the user could torrent the chromium sources and use them inside the pkgbuild.

**Comment by Eloston** [comment]
@jstkdng

> even then you are still required to compile the resulting package and check if its all good

Yes, you can't be 100% certain that the binary is trustworthy even if people report that the binary is reproducible (or report when it is not reproducible). But that still increases the user's trust in the binaries.

> and even then the binary could still be compromised, like what happened to transmission

I'm not familiar with Transmission's situation, but that can only happen if the source code that was downloaded is compromised, or the process of building the source code gets compromised. We can change who hosts the source code, but otherwise there isn't anything we can do about the other issues; that's the user's responsibility. If there is any specific guidance you have to reduce the risks, then let us know.

> And under arch you can point to sources using the file:// handle instead of an url, then the user could torrent the chromium sources and use them inside the pkgbuild.

Torrenting is a good point. Could be useful if people are willing to host torrents of the source code.

**Comment by jstkdng** [comment]
@Eloston 
I'm using my phone so I cant properly quote, sorry for that.
What happened to transmission is that their release binaries were compromised after they were published, and many people were hit with a ransomware. One way to avoid that is to have some way to automatically check the sources/binaries. Arch checks the sha sums before compiling and after that it creates gpg signatures of the resulting binary (only done when using a repository). So then, the first stages should be protected and further tries to replace the binaries with compromised ones are impossible unless they get a hold of the packager's private key (dunno if it is the same for other distros). But the issue of trust still remains, the user has to trust the packager that he didn't do anything nasty when compiling, and just saying: "trust me bro" won't help. Maybe livestreaming the compilation process could help reduce the paranoia lmao.

**Comment by playgithub** [comment]
@Eloston @jstkdng 
Thanks, you are so serious .
Without source code, it's almost impossible to prove the binaries are not compromised, however binary is another form of source code, so does assembly, but it's impossible to verify, event they are reverse engineered to human friendly C++ code, too much code. When binaries are not necessarily reproducible, fake reproducible can be in, paranoia.
If there are **official ungoogled-chromium**, I'd like to trust it more :)

**Comment by jstkdng** [comment]
@playgithub 
first you have to define official. Official as in built by the team behind ungoogled chromium? that would be @Eloston , but that guy uses debian, and I dont think he is willing to switch to arch.
And just changing the name from unofficial to official wont change the fact that the binaries can still be compromised. That is why I fucking hate "privacy focused" companies, like m*zilla or n*rdvpn, that just tell its customers "trust us your data bro, we totally promise not to sell it or anything, tehe" and giving them a false sense of security.

**Comment by playgithub** [comment]
@jstkdng 

> first you have to define official. Official as in built by the team behind ungoogled chromium? that would be @Eloston

Yes

> but that guy uses debian, and I dont think he is willing to switch to arch.

Building needs much more disk spaces than the source code, and time, and with precondition trusting the builder.
For me, the key problem is I can get all the source code for building chromium.
An arch PKGBUILD that use mirrors is the best way. But I can't see it is easy, chromium is so self contained.
arch for simpliticy :)

> like m*zilla or n*rdvpn

and Apple :(

**Comment by Eloston** [comment]
@jstkdng @playgithub Let me try to be more clear about my perspective.

I am *not* saying that reproducibility will give users absolute confidence in the pre-built binaries. Reproducibility is a property of the build process that can **increase** user's trust in pre-built binaries. This page describes how reproducibility can increase trust: https://reproducible-builds.org/. I will highlight some concepts of this page below.

To make reproducibility useful, you need a **distributed system of users** who can verify the binaries. More specifically, these users should have three aspects:

1. They should be independent
2. Most should act in good faith
3. There should be a lot of them. The more people that are verifying the binaries, the faster that malicious binaries can be caught.

Note that these three properties are common to many distributed systems, such as blockchains.

Without those three aspects, the distributed system does not work effectively. When the system does not work effectively, then reproducibility is not useful.

With this distributed system in place, it changes who we need to trust. There is no longer a single entity we have to trust (the packager), because we can also trust everyone that has verified the binaries.

Does this system actually work? Will it work for ungoogled-chromium? I don't know. But, it's theoretically better than the current situation, where we tell users that binaries *could* be compromised and they should trust an anonymous packager.

**Comment by playgithub** [comment]
The reproducibility system is more trustful than an official one.

It's awesome if it could be cross *nix :)

Thanks
