### ISSUE TITLE
On the OS X  version there are default extensions that cannot be disabled

### ISSUE THREAD

**Issue by jgoldgh** [Eloston/ungoogled-chromium#86]
First, thanks for creating this. You're providing a valuable service.  I use Chrome on OSX because Firefox is so buggy it's unusable.  I really hate using Chrome because of all the data collection activities.  If this works, I'll be very grateful.

I just installed version for the Mac "ungoogled-chromium_53.0.2785.116-1.2_macos.dmg".  When I checked the extensions there are three;

Bookmark Manager 0.1
Chromium PDF viewer
CryptoTokenExtensions.

These are all enabled and cannot be disabled.  Why?  I don't use bookmarks.  If I want to see a PDF I'll download it and open it.  I don't know what the CryptoTokenExtension is or why I would want it.

Is there a reason these are forced on?

**Comment by Eloston** [comment]
These are components that are built-in to Chrome/Chromium that cannot normally be disabled. They are actually hidden by default, but there is a patch to make them show up. I think these are components that happen to use the extensions API, but they are tightly integrated, so they won't be easy to make toggleable.

If you don't want to use the built-in PDF viewer, I think there's a way to force it to download.

Closing since this answers the question. Feel free to ask follow-up questions though.

**Comment by jgoldgh** [comment]
That explains it. Thank you very much for the response and for all the work you put in doing this! I'm going to use it as my main browser.

**Comment by MrOCR** [comment]
@Eloston But what about CryptoTokenExtension? How to delete/ remove it?

**Comment by antonin-lebrard** [comment]
@MrOCR 
There is an issue about the CryptoTokenExtension on the inox patchet repository that have some useful informations: https://github.com/gcarq/inox-patchset/issues/25

It seems to be related only to the U2F keys like Yubikeys. So it seems to be an important extension to keep, but maybe having the options to disable it could be cool. But I suspect it is more coupled with the chromium code base than others extensions, hence the non-disable status of it
