### ISSUE TITLE
New optional feature - 'DRM loader'

### ISSUE THREAD

**Issue by GildedHonour** [Eloston/ungoogled-chromium#875]
Hey. We’re about to begin to develop an open source project based on ‘ungoogled-chromium’. In it the ‘DRM loader code’ will be eliminated.

We’re wondering, once we’ve developed it or during the process, would you guys consider incorporating our version into ‘ungoogled-chromium’ as an optional feature that could be enabled and disabled? ‘Disabled’ could be by default.

Thus ‘ungoogled-chromium’ would have the feature that attracts additional audience, and for us it’d be easier to deal with the code, potential merge conflicts that may arise, keep the code in sync and so on.

**Comment by Eloston** [comment]
Yeah I don't mind. It might be useful in some cases.

How would this be configured? Will it be a flag in `chrome://flags`, or a setting in `chrome://settings`?

**Comment by GildedHonour** [comment]
Alright.

None of those. It'll run at a lower level. DRM loader will be removed by python scripts from the source code of Chromium, the same way the python scripts of 'ungoogled-chromium' remove the original functionality that's not needed in this project. A binary Chromium thus will be produced with no DRM functionality in it.

**Comment by GildedHonour** [comment]
this 

`
Chromium original -> ungoogled-chromium python scripts -> ungoogled-chromium
`

will become this


`
Chromium original -> ungoogled-chromium python scripts > No-DRM python scripts -> ungoogled-chromium-no-drum
`

**Comment by GildedHonour** [comment]
Chromium original -> ungoogled-chromium python scripts -> (No-DRM python scripts, optional) -> ungoogled-chromium(-no-DRM)

**Comment by jstkdng** [comment]
Afaik, chromium doesn't have drm support (widevine), and you have to download a libray from google chrome in order to have drm functionality on chromium.
Now, if you want to remove the support altogether you could use the already existing patching toolchain, no need to complicate yourself by creating more scripts, though, I don't think removing DRM support completly is a good idea. Some people have already complained that the DRM thingy is not working/present.

**Comment by Eloston** [comment]
@GildedHonour I see, that isn't what I had in mind for an optional feature. We don't implement features like you propose in ungoogled-chromium because it sets a bad precedent for any new feature; I don't think anyone wants to deal with 2^N variants of N optional features (even `N = 1` is already a bit annoying for the user).

If you decide to write the change as a patch, let me know here. Depending on how you implement the change, I might be able to convert it to a command-line flag and include it in ungoogled-chromium. For now, I'll close the issue.
