### ISSUE TITLE
[linux 18.0.4] Cannot enable microphone

### ISSUE THREAD

**Issue by Ph0rkoz** [Eloston/ungoogled-chromium#887]
Using uChromium v 78. When I try google hangouts or even a microphone test the sites complain the microphone is blocked. When I explicitly allow the permission the sites still think the mic is blocked.

I also have a webcam and the issue doesn't duplicate there. Sites can use it.

Anything else I should check? I upgraded from v 72 to v 78 and the issue persisted. I can see the microphone in my sound settings and it is working.

**Comment by mbakke** [comment]
This is likely because your Chromium preferences have audio capture disabled.

Debian had this problem in the official Chromium package, and Guix in their `ungoogled-chromium` package which cargo-culted the Debian setting.

Assuming your Chromium profile was created by either of those packages, the way to fix it is to close the browser and run:

```
sed -i 's/"audio_capture_enabled":false/"audio_capture_enabled":true/' ~/.config/chromium/Default/Preferences 
```

**Comment by Ph0rkoz** [comment]
Yes, this was it. i found it inside the preferences file set to false.

**Comment by SteelChickens** [comment]
I was able to use the microphone but get no sound in talk phonecalls... for some reason video calls work fine.

**Comment by Eloston** [comment]
@SteelChickens If this FAQ section doesn't help you, please open a new issue: https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#why-is-my-microphone-not-working

Closing.
