### ISSUE TITLE
googleapis font patch contains a file which gets removed

### ISSUE THREAD

**Issue by berkley4** [Eloston/ungoogled-chromium#899]
patches/core/ungoogled-chromium/disable-fonts-googleapis-references.patch includes a change to third_party/catapult/third_party/polymer/components/font-roboto/roboto.html

roboto.html gets removed (presumably after the above patch is applied) via third_party/catapult/third_party/polymer/components getting overwritten by a symlink to third_party/polymer/v1_0/components-chromium.

Directly extracting third_party/polymer/v1_0/components-chromium/font-roboto/roboto.html from the chromium xz tar archive reveals one line of code....

`<link rel="stylesheet" href="chrome://resources/css/roboto.css">`

Since this is identical to what the patch would have produced, the hunk relating to roboto.html can be removed from disable-fonts-googleapis-references.patch.

On debian there wouldn't normally have been any build errors unless one did a rebuild (in my case doing a pgo phase 2 rebuild), which throws an error about trying to patch a symlinked file.

**Comment by Eloston** [comment]
First, please state the platform you're using or post your issues to ungoogled-chromium-debian. It's a bit confusing without any context.

Secondly, I don't want to change the patch because `disable-fonts-googleapis-references.patch` is a global patch, and symlinking is Debian-specific. We can just disable the symlink, since other Linux platforms are working fine.
