### ISSUE TITLE
[Question] profile picture

### ISSUE THREAD

**Issue by aelisya** [Eloston/ungoogled-chromium#912]
Hello i want to know where is stocked the default picture for profile, because i want to edit it to modify one with my own profile picture thanks.

I have tested to add with the curent name of my picture in local state (before open the browser) it didn't work

I have tested to add the picture in default/Avatars (created folder) it didn't work either.

**Comment by cattai-lorenzo** [comment]
I see this has been closed as "completed", am I missing something?
It would be quite handy to be able to change the profile picture when using multiple profiles, is there a way to do it now?

**Comment by tomasz1986** [comment]
> I see this has been closed as "completed", am I missing something?

Yes, it seems that the user simply closed their own issue (maybe due to a lack of any response). The whole "completed" thing is something that GitHub added much later, i.e. the issue was originally just "closed" (without any "as").

When it comes to the profile pictures themselves, unfortunately there is still no easy way to use custom images. It does seem possible with some hackery, e.g. see https://superuser.com/questions/449244/how-do-i-access-edit-the-chrome-user-avatar-images/639248#639248, although I haven't tested the method myself.

**Comment by cattai-lorenzo** [comment]
Thank you for the explanation and help, will definately checkout the hacky way for now.
