### ISSUE TITLE
Can't play Hulu videos.

### ISSUE THREAD

**Issue by Chilcout** [Eloston/ungoogled-chromium#917]
Everyt video I try to open, I get this error code: P-Dev302. I'm on windows 7 64

**Comment by wchen342** [comment]
A quick search on Google shows this happened on all kinds of platforms (Smart TV, Apple TV, etc.) so I suspect this is a Hulu problem.

**Comment by seanking2919** [comment]
That is most likely due to Widevine plugin not being installed. For your knowledge, Widevine is a proprietary DRM technology from Google. It's widely used by many streaming platforms like Netflix, Hulu, and Amazon. It can only be installed on Chromium-based browser that have proper licensing for using it. For instance, Brave doesn't include it by default, but they do show a prompt which will warn you about the site requiring Widevine and asking you if you want to install it. And the process for them to get licensing for using Widevine in Brave was pretty difficult. See here: https://github.com/brave/browser-laptop/issues/10449

For this reason, I presume that's why Widevine is not included in Ungoogled Chromium.

**Comment by Eloston** [comment]
I think it's possible to install Widevine on ungoogled-chromium for Windows right now, but we're lacking instructions in the Wiki: https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#how-do-i-install-widevine-cdm

It sounds plausible that this is a Widevine issue. Since the OP hasn't responded in a while, closing.
