### ISSUE TITLE
Stable Windows Version of Ungoogled Chromium (V 67)

### ISSUE THREAD

**Issue by PlazmaKG** [Eloston/ungoogled-chromium#922]
I've noticed that this is the latest version of the stable branch of Ungoogled Chromium. Is it still safe to use this? I do like the old style of the browser more, and if it's safe to use, I'd like to use this instead. Thanks in advance.

**Comment by kramred** [comment]
I don't think it is safe in the sense that it __will__ contain all vulnerabilities that have been discovered since the release of v67 (some quite serious ones as well) – as far as I know no one is back-porting security fixes from later releases (Google/Chrome/Chromium often delivers security fixes in a new major release of the browser)

As far as I understand the "development" version is supposed to be promoted to "stable" after some time as long as there are no (major) glitches; but this needs to be done manually and often only happens irregularly.

So, with ungoogled chromium v67 you might gain a bit of privacy but with a lot of security issues. I'd recommend that you try the "development" version (i.e. 79.0.3945.117-1 as of now – and even that one contains some known vulnerabilities)

**Comment by Eloston** [comment]
Yeah the newer Windows versions should be promoted, even though they have a few bugs. It's not recommended to stick to an old version of Chromium.
