### ISSUE TITLE
Option to use WinRAR in the unpack script instead of 7-Zip

### ISSUE THREAD

**Issue by dabockster** [Eloston/ungoogled-chromium#956]
Hey everyone,

I downloaded the source code using the download.py script and tried to unpack it when I noticed that the script tried to call 7-Zip. I don't have 7-Zip installed on my computer, nor plan to, due to a conflict between my country's upcoming election (United States) and the Russian Federation (where the 7-Zip maintainer is located). Please respect my beliefs in this matter and not try to convince me to use 7-Zip just because it's FOSS.

Anyways, I wanted to put in a request for WinRAR support in the unpack script as an alternative since WinRAR has a CLI and is made in Germany/the European Union. I figured WinRAR would be the next common archiving tool on Windows after 7-Zip.

**Comment by PF4Public** [comment]
So, did I get it right: your beliefs preclude your usage of an opensource software, if the maintainer is located in Russia, but are fine with a closedsource software, whose  maintainer was born in Russia?

**Comment by wchen342** [comment]
_Disclaimer: all my claims in this thread are my personal opinions. They do not represent this project or any other person involved._

I think despite the seemingly controversial reasoning, the request itself is reasonable. Back when I was using Windows I did use WinRAR all the time.

But remember one thing: freedom and respect work both ways. You are free to choose whatever tool you want to use, and the maintainers have the freedom to select the tools they prefer. This is why the project is open sourced, because you can easily fork it and modify it to suit you need, with very little efforts.
And one last thing, please remember even in authoritarianism countries there are people who respect the western world and fight for their freedoms. I understand it is hard to trust someone from those counties, and I totally agree you should use cautions, but I do wish there will be less prejudice just because of the country they were born, which was not their choice. (_Disclaimer2: I am from mainland China._)

**Comment by Eloston** [comment]
@dabockster I do not want politics to get involved in this project. As a result, I do not consider your reason a valid justification for this feature in the context of this project.

However, I think @wchen342 raises a valid reason which is convenience; it would be nice to not have to install 7-zip if you already have WinRAR.

To anyone interested, feel free to submit a PR for this feature.

**Comment by dabockster** [comment]
@PF4Public RARLabs is in Germany, though. So I would think it would fall under EU jurisdiction.

@wchen342 I get both points you're trying to make. The current situation between the US and RU is an awful shame (let alone the issues in your own home country). That being said, though, not all of us have the time/resources to audit every repo we want to use. And because a lot of internet conversations are through pseudonyms (usernames), it's difficult to verify someone's credentials and intentions.

I also feel that telling someone to fork the repo is either passing the buck or politely telling someone to go away. Forking for a minor build feature only contributes to clutter and would have a hard time gaining traction by the community.

@Eloston I totally understand trying to keep things neutral. So maybe it is better to frame it from a convenience standpoint. Maybe frame it as a "support the top 3 _______ programs" issue so the build isn't necessarily tied to one particular third party executable or build system. Super hard issue to solve, though.

**Comment by emanruse** [comment]
@dabockster

> Please respect my beliefs in this matter and not try to convince me to use 7-Zip just because it's FOSS.

This project is not about your, Trump's or Putin's beliefs, so there is nothing really to respect in regards to that. The only thing worth respecting is the freedom of others, so do not try to convince them to use or work for a proprietary software/format (Windows, WinRAR, unrar or whatever-non-FOSS). This is a FOSS project and it is just unfair to request a limitation to other's freedoms for your own convenience or personal inclinations.

I am fully against any proprietary format/tool. I hope @Eloston will close this as "wontfix" as such suggestions are bad for the whole community around this project.

**Comment by emanruse** [comment]
FYI the developer if WinRAR is Russian:

https://en.wikipedia.org/wiki/Eugene_Roshal

**Comment by tangalbert919** [comment]
Using WinRAR instead of 7-zip is fine if that is their preference. Perhaps I'll take a look at this.
