### ISSUE TITLE
"Aw Snap" Tabs Crashing constantly since updating.

### ISSUE THREAD

**Issue by mag1c64** [Eloston/ungoogled-chromium#962]
Ungoogled-Chromium 79.0.3945.130-1: for Arch Linux

I just updated from ungoogled-chromium-bin to this latest arch binary. 
Now i'm getting tabs crashing constantly. 
"Aw Snap" tab crashing regardless of website.
Running Arch Linux
Tried incognito and disable addons extensions. 
Tried reverting to older version and it continues happening

I renamed ~/.config/chromium folder thinking it was some settings but still same issue.
Any help to diagnose the issue

**Comment by PF4Public** [comment]
First of all, you should look in dmesg, this should've been logged there.

If that information is not helpful, then, try attaching `gdb` to chromium, make it crash and see the backtrace, this could potentially shed some light on the issue, although I suppose that binary release may miss debug symbols.

**Comment by pegasusearl** [comment]
Hello, just adding extra info. I got similiar problem. But I always used chromium 70.0.3538.77-1 and never updated it since then.
In the past, when I got this problem, clearing browsing data would work but now it does not.
I have been clearing out cache, history, login, and everything from `All Time` but I'm still facing that problem.
I'm not sure if it has something to do with new version.

**Comment by mbakke** [comment]
@pegasusearl running an ancient chromium with --no-sandbox sounds like a recipe for getting pwned.  I hope you are not browsing any untrusted sites!

For those on Linux I can recommend installing GNU Guix and use that to install the latest ungoogled-chromium.  The maintainer is very active around here.  ;-)

**Comment by Eloston** [comment]
@mag1c64 You should try updating to version 80 and seeing if you have the same issue. If you do, you should post a new issue to ungoogled-chromium-archlinux.
