### ISSUE TITLE
Building still fails with Python 3.4?

### ISSUE THREAD

**Issue by tonowoe** [Eloston/ungoogled-chromium#98]
Sorry for bothering you again with the python version 3.4. But I still can't build it.

[Here is the current error what I see](http://pastebin.com/raw/thPiWbyE) when running `build.py`:

I wouldn't like to run testing distribution yet, so no version 3.5. :-(

**Comment by tonowoe** [comment]
It's working! I love this.

The building itself took over 1 hour even though I have pretty decent PC. It's going to be a pain in the ass in the future when building for the updated versions. By the way, is there some reason why there aren't pre-built packages available for the new releases to download (e.g. for Debian/Ubuntu)?

**Comment by Eloston** [comment]
Glad to hear it's working now.

> By the way, is there some reason why there aren't pre-built packages available for the new releases to download (e.g. for Debian/Ubuntu)?

That's because I haven't released a new version yet. I use tags to denote snapshots of the master branch that I deem stable or "good enough" for general use.

As to why I haven't tagged a new version yet: there are a few things I wanted to fix related to buildlib, but I guess they can wait. I might tag a new version soon.

**Comment by tonowoe** [comment]
Yeah no hurry man, better safe than sorry, it's all good. Keep up the good work.
